/* =====================================================================
   41_FinalSettlement_Labels.sql  -  HRMS: English + Arabic labels of Final Settlement
   ---------------------------------------------------------------------
   Run after 33 (Core.UiLabels) and 39 / 40. Idempotent: new keys are
   inserted; existing keys are only completed (an empty ArabicText /
   SourceText is filled in) - text already edited in the table is never
   overwritten by a re-run. Edit any of these in Core.UiLabels and the
   screens show the change within 30 seconds, no code change.

     fs.*      Final Settlement screens and the settlement statement
               (the statement prints every label in English AND Arabic)
     js.fs_*   texts used by wwwroot/js/settlement.js
     msg.fs_*  messages of Payroll.usp_FinalSettlement_Manage (db/40) and
               FinalSettlementController - matched by their SourceText, so
               {0} values are carried into Arabic
   ===================================================================== */
SET NOCOUNT ON;
GO
IF OBJECT_ID(N'tempdb..#Seed') IS NOT NULL DROP TABLE #Seed;
CREATE TABLE #Seed (
    LabelKey    VARCHAR(150)   COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
    Module      VARCHAR(30)    COLLATE DATABASE_DEFAULT NOT NULL,
    EnglishText NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL,
    ArabicText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
    SourceText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL
);
INSERT INTO #Seed (LabelKey, Module, EnglishText, ArabicText, SourceText) VALUES
    ('fs.title_final_settlement', 'fs', N'Final Settlement', N'التسوية النهائية', NULL),
    ('fs.title_settlements', 'fs', N'Settlements', N'التسويات', NULL),
    ('fs.title_new_settlement', 'fs', N'New Settlement', N'تسوية جديدة', NULL),
    ('fs.title_leave_encashment', 'fs', N'Leave Encashment', N'صرف بدل الإجازات', NULL),
    ('fs.title_statement', 'fs', N'Settlement Statement', N'كشف التسوية', NULL),
    ('fs.list_subtitle', 'fs', N'End-of-service settlements: pending salary, leave, indemnity and recoveries', N'تسويات نهاية الخدمة: الراتب المستحق والإجازات ومكافأة نهاية الخدمة والاستقطاعات', NULL),
    ('fs.encashment_subtitle', 'fs', N'Leave encashment without exit, paid through payroll', N'صرف بدل رصيد الإجازات دون إنهاء الخدمة، عبر مسير الرواتب', NULL),
    ('fs.new_subtitle', 'fs', N'Choose the employee and the separation - the settlement is calculated for you', N'اختر الموظف ونوع إنهاء الخدمة - تُحسب التسوية تلقائياً', NULL),
    ('fs.type', 'fs', N'Type', N'النوع', NULL),
    ('fs.type_resignation', 'fs', N'Resignation', N'استقالة', NULL),
    ('fs.type_termination', 'fs', N'Termination', N'إنهاء خدمة', NULL),
    ('fs.type_contract_end', 'fs', N'End of contract', N'انتهاء العقد', NULL),
    ('fs.type_retirement', 'fs', N'Retirement', N'تقاعد', NULL),
    ('fs.type_death', 'fs', N'Death', N'وفاة', NULL),
    ('fs.type_disability', 'fs', N'Disability', N'عجز', NULL),
    ('fs.type_encashment', 'fs', N'Leave encashment', N'صرف بدل إجازة', NULL),
    ('fs.exit_settlements', 'fs', N'Exit settlements', N'تسويات نهاية الخدمة', NULL),
    ('fs.status_open', 'fs', N'Open (not paid)', N'مفتوحة (غير مدفوعة)', NULL),
    ('fs.status_draft', 'fs', N'Draft', N'مسودة', NULL),
    ('fs.status_pending', 'fs', N'Pending approval', N'بانتظار الاعتماد', NULL),
    ('fs.status_pending_hr', 'fs', N'Waiting for HR', N'بانتظار الموارد البشرية', NULL),
    ('fs.status_pending_finance', 'fs', N'Waiting for Finance', N'بانتظار المالية', NULL),
    ('fs.status_approved', 'fs', N'Approved - to pay', N'معتمدة - للدفع', NULL),
    ('fs.status_paid', 'fs', N'Paid', N'مدفوعة', NULL),
    ('fs.status_cancelled', 'fs', N'Cancelled', N'ملغاة', NULL),
    ('fs.method_bank', 'fs', N'Bank transfer', N'تحويل بنكي', NULL),
    ('fs.method_cheque', 'fs', N'Cheque', N'شيك', NULL),
    ('fs.method_cash', 'fs', N'Cash', N'نقداً', NULL),
    ('fs.method_payroll', 'fs', N'Through payroll', N'عبر مسير الرواتب', NULL),
    ('fs.settlement', 'fs', N'Settlement', N'التسوية', NULL),
    ('fs.settlements', 'fs', N'Settlements', N'التسويات', NULL),
    ('fs.1_settlement', 'fs', N'1 settlement', N'تسوية واحدة', NULL),
    ('fs.0_settlements', 'fs', N'{0} settlements', N'{0} تسويات', NULL),
    ('fs.last_day', 'fs', N'Last day', N'آخر يوم', NULL),
    ('fs.service', 'fs', N'Service', N'مدة الخدمة', NULL),
    ('fs.payable_kwd', 'fs', N'Payable (KWD)', N'المستحق (د.ك)', NULL),
    ('fs.no_settlements_match', 'fs', N'No settlements match the filters', N'لا توجد تسويات مطابقة للتصفية', NULL),
    ('fs.no_settlements_yet', 'fs', N'No settlements yet', N'لا توجد تسويات بعد', NULL),
    ('fs.no_settlements_text', 'fs', N'Start one with New Settlement when an employee resigns or leaves.', N'ابدأ تسوية جديدة عند استقالة موظف أو انتهاء خدمته.', NULL),
    ('fs.open', 'fs', N'Open', N'فتح', NULL),
    ('fs.open_0', 'fs', N'Open {0}', N'فتح {0}', NULL),
    ('fs.statement', 'fs', N'Statement', N'الكشف', NULL),
    ('fs.statement_0', 'fs', N'Statement {0}', N'كشف {0}', NULL),
    ('fs.search_placeholder', 'fs', N'Search employee or settlement no.', N'ابحث باسم الموظف أو رقم التسوية', NULL),
    ('fs.new_settlement', 'fs', N'New settlement', N'تسوية جديدة', NULL),
    ('fs.n_days', 'fs', N'{0} days', N'{0} يوم', NULL),
    ('fs.service_short', 'fs', N'{0}y {1}m', N'{0}س {1}ش', NULL),
    ('fs.service_ymd', 'fs', N'{0} years {1} months {2} days', N'{0} سنة {1} شهر {2} يوم', NULL),
    ('fs.kpi_drafts', 'fs', N'Drafts', N'المسودات', NULL),
    ('fs.kpi_drafts_note', 'fs', N'not sent for approval yet', N'لم تُرسل للاعتماد بعد', NULL),
    ('fs.kpi_pending', 'fs', N'Waiting for approval', N'بانتظار الاعتماد', NULL),
    ('fs.kpi_pending_note', 'fs', N'{0} with HR · {1} with Finance', N'{0} لدى الموارد البشرية · {1} لدى المالية', NULL),
    ('fs.kpi_to_pay', 'fs', N'Approved, to pay (KWD)', N'معتمدة للدفع (د.ك)', NULL),
    ('fs.kpi_to_pay_note', 'fs', N'{0} settlements', N'{0} تسويات', NULL),
    ('fs.kpi_paid_year', 'fs', N'Paid this year (KWD)', N'المدفوع هذا العام (د.ك)', NULL),
    ('fs.kpi_paid_year_note', 'fs', N'{0} settlements', N'{0} تسويات', NULL),
    ('fs.encashment_banner_title', 'fs', N'Leave encashment without exit.', N'صرف بدل الإجازة دون إنهاء الخدمة.', NULL),
    ('fs.encashment_banner_text', 'fs', N'Enter the leave balance (from the leave records until the Leave module is connected) and the days to encash. Once HR and Finance approve, it becomes a one-time Leave Encashment earning paid by the payroll of the month chosen.', N'أدخل رصيد الإجازات (من سجلات الإجازات إلى أن يُربط نظام الإجازات) والأيام المطلوب صرفها. بعد اعتماد الموارد البشرية والمالية يُضاف كاستحقاق لمرة واحدة باسم بدل رصيد الإجازات ويُصرف في مسير الشهر المختار.', NULL),
    ('fs.new_leave_encashment', 'fs', N'New leave encashment', N'صرف بدل إجازة جديد', NULL),
    ('fs.balance_on', 'fs', N'Balance on', N'الرصيد في', NULL),
    ('fs.paid_in_payroll_of', 'fs', N'Paid in the payroll of', N'يُصرف في مسير', NULL),
    ('fs.encashment_reason_placeholder', 'fs', N'Why the leave is encashed', N'سبب صرف بدل الإجازة', NULL),
    ('fs.separation', 'fs', N'Separation', N'إنهاء الخدمة', NULL),
    ('fs.leave_encashment', 'fs', N'Leave encashment', N'بدل رصيد الإجازات', NULL),
    ('fs.select_employee', 'fs', N'Select an employee', N'اختر موظفاً', NULL),
    ('fs.separation_type', 'fs', N'Separation type', N'نوع إنهاء الخدمة', NULL),
    ('fs.last_working_day', 'fs', N'Last working day', N'آخر يوم عمل', NULL),
    ('fs.notice_date', 'fs', N'Notice date', N'تاريخ الإشعار', NULL),
    ('fs.salary_unpaid_from', 'fs', N'Salary unpaid from', N'الراتب غير مدفوع من', NULL),
    ('fs.leave_balance_days', 'fs', N'Leave balance (days)', N'رصيد الإجازات (أيام)', NULL),
    ('fs.days_to_encash', 'fs', N'Days to encash', N'الأيام المطلوب صرفها', NULL),
    ('fs.days_to_encash_hint', 'fs', N'Empty = the whole balance', N'فارغ = كامل الرصيد', NULL),
    ('fs.reason', 'fs', N'Reason', N'السبب', NULL),
    ('fs.reason_placeholder', 'fs', N'Resignation letter, termination decision ...', N'خطاب الاستقالة، قرار إنهاء الخدمة ...', NULL),
    ('fs.employee_has_settlement', 'fs', N'This employee already has a final settlement:', N'لدى هذا الموظف تسوية نهائية بالفعل:', NULL),
    ('fs.joined', 'fs', N'Joined', N'تاريخ الالتحاق', NULL),
    ('fs.monthly_salary', 'fs', N'Monthly salary', N'الراتب الشهري', NULL),
    ('fs.indemnity_salary', 'fs', N'Indemnity salary', N'راتب احتساب المكافأة', NULL),
    ('fs.leave_salary', 'fs', N'Leave salary', N'راتب احتساب الإجازة', NULL),
    ('fs.salary_paid_through', 'fs', N'Salary paid up to', N'الراتب مدفوع حتى', NULL),
    ('fs.indemnity_rules', 'fs', N'Indemnity rules', N'قواعد المكافأة', NULL),
    ('fs.calculate_settlement', 'fs', N'Calculate settlement', N'احتساب التسوية', NULL),
    ('fs.save_and_recalculate', 'fs', N'Save and recalculate', N'حفظ وإعادة الاحتساب', NULL),
    ('fs.step_1_employee', 'fs', N'1 · Employee and separation', N'1 · الموظف وإنهاء الخدمة', NULL),
    ('fs.step_employee', 'fs', N'Employee', N'الموظف', NULL),
    ('fs.step_calculation', 'fs', N'Calculation', N'الاحتساب', NULL),
    ('fs.step_approval', 'fs', N'Approval', N'الاعتماد', NULL),
    ('fs.step_payment', 'fs', N'Payment', N'الدفع', NULL),
    ('fs.how_it_is_calculated', 'fs', N'How it is calculated', N'طريقة الاحتساب', NULL),
    ('fs.howto_pending', 'fs', N'Every salary item from the day after the last closed payroll to the last working day, by calendar days.', N'كل بنود الراتب من اليوم التالي لآخر مسير مغلق حتى آخر يوم عمل، بالأيام التقويمية.', NULL),
    ('fs.howto_leave', 'fs', N'Days to encash × leave salary ÷ the daily divisor of the indemnity rules (26).', N'الأيام المطلوب صرفها × راتب الإجازة ÷ قاسم اليوم في قواعد المكافأة (26).', NULL),
    ('fs.howto_indemnity', 'fs', N'Labour Law 6/2010: 15 days a year for the first 5 years, a month a year after, capped at 18 months, times the % for the separation type.', N'قانون العمل 6/2010: 15 يوماً عن كل سنة من السنوات الخمس الأولى وشهر عن كل سنة بعدها، بحد أقصى 18 شهراً، مضروبة في نسبة الاستحقاق لنوع إنهاء الخدمة.', NULL),
    ('fs.howto_recoveries', 'fs', N'Loan and advance balances, unpaid deductions, PIFSS on the pending salary and salary paid after the last day.', N'أرصدة القروض والسلف، والاستقطاعات غير المدفوعة، والتأمينات الاجتماعية على الراتب المستحق، والراتب المدفوع بعد آخر يوم.', NULL),
    ('fs.howto_note', 'fs', N'Every figure can be checked on the next page; lines can be added or waived before it is sent for approval.', N'يمكن مراجعة كل رقم في الصفحة التالية، وإضافة بنود أو إعفاؤها قبل إرسالها للاعتماد.', NULL),
    ('fs.hero_draft', 'fs', N'Draft - check it and send it for approval', N'مسودة - راجعها وأرسلها للاعتماد', NULL),
    ('fs.hero_to_pay', 'fs', N'Approved - ready to be paid', N'معتمدة - جاهزة للدفع', NULL),
    ('fs.settlement_details_hint', 'fs', N'Separation, last working day, salary unpaid from and leave balance', N'إنهاء الخدمة وآخر يوم عمل وتاريخ الراتب غير المدفوع ورصيد الإجازات', NULL),
    ('fs.other_earnings_hint', 'fs', N'Unpaid earnings of the last months and earnings added by hand', N'استحقاقات الأشهر الأخيرة غير المدفوعة والاستحقاقات المضافة يدوياً', NULL),
    ('fs.recoveries_hint', 'fs', N'Loans, advances, unpaid deductions and amounts added by hand', N'القروض والسلف والاستقطاعات غير المدفوعة والمبالغ المضافة يدوياً', NULL),
    ('fs.all_settlements', 'fs', N'All settlements', N'كل التسويات', NULL),
    ('fs.settlement_details', 'fs', N'Settlement details', N'تفاصيل التسوية', NULL),
    ('fs.change_details', 'fs', N'Change details', N'تعديل التفاصيل', NULL),
    ('fs.notice_period_n', 'fs', N'notice period {0} days', N'فترة الإشعار {0} يوم', NULL),
    ('fs.cancelled_banner', 'fs', N'This settlement is cancelled.', N'هذه التسوية ملغاة.', NULL),
    ('fs.returned_banner', 'fs', N'Returned by {0}:', N'أعادها {0}:', NULL),
    ('fs.rule_set_unverified', 'fs', N'The indemnity rule set {0} is not verified yet. Confirm it in Payroll Settings, or tick the confirmation when you send this settlement for approval.', N'قواعد المكافأة {0} غير مؤكدة بعد. أكدها في إعدادات الرواتب، أو ضع علامة التأكيد عند إرسال هذه التسوية للاعتماد.', NULL),
    ('fs.no_rule_set', 'fs', N'No indemnity rule set is in force on the last working day - the indemnity cannot be calculated. Add one in Payroll Settings.', N'لا توجد قواعد مكافأة سارية في آخر يوم عمل - لا يمكن احتساب المكافأة. أضفها في إعدادات الرواتب.', NULL),
    ('fs.salary_from_profile', 'fs', N'The employee has no salary items yet, so the basic salary and allowances on the employee profile are used.', N'لا توجد بنود راتب للموظف بعد، لذلك يُستخدم الراتب الأساسي والبدلات من ملف الموظف.', NULL),
    ('fs.net_negative', 'fs', N'The recoveries are more than the dues: the employee owes KWD {0}.', N'الاستقطاعات أكبر من المستحقات: على الموظف سداد {0} د.ك.', NULL),
    ('fs.pending_salary', 'fs', N'Pending salary', N'الراتب المستحق', NULL),
    ('fs.unpaid_from_to', 'fs', N'Salary not paid by any payroll from {0} to {1}.', N'راتب لم يُصرف في أي مسير من {0} إلى {1}.', NULL),
    ('fs.no_pending_salary', 'fs', N'No pending salary - payrolls have paid up to the last working day.', N'لا يوجد راتب مستحق - صُرف الراتب في المسيرات حتى آخر يوم عمل.', NULL),
    ('fs.paid_through_by', 'fs', N'paid up to {0} by {1}', N'مدفوع حتى {0} في {1}', NULL),
    ('fs.full_month', 'fs', N'full month', N'شهر كامل', NULL),
    ('fs.other_earnings', 'fs', N'Other earnings', N'استحقاقات أخرى', NULL),
    ('fs.no_other_earnings', 'fs', N'No unpaid earnings.', N'لا توجد استحقاقات غير مدفوعة.', NULL),
    ('fs.leave_balance_on', 'fs', N'Leave balance on {0}', N'رصيد الإجازات في {0}', NULL),
    ('fs.leave_balance_manual', 'fs', N'Entered by hand until the Leave module is connected', N'يُدخل يدوياً إلى أن يُربط نظام الإجازات', NULL),
    ('fs.daily_rate', 'fs', N'Daily rate', N'الأجر اليومي', NULL),
    ('fs.no_leave_salary', 'fs', N'No leave salary - check the salary items.', N'لا يوجد راتب لاحتساب الإجازة - راجع بنود الراتب.', NULL),
    ('fs.leave_encashment_n_days', 'fs', N'Leave encashment · {0} days', N'بدل إجازة · {0} يوم', NULL),
    ('fs.indemnity', 'fs', N'End-of-service indemnity', N'مكافأة نهاية الخدمة', NULL),
    ('fs.service_years_n', 'fs', N'{0} years of service', N'{0} سنة خدمة', NULL),
    ('fs.years_x_y_days_per_year', 'fs', N'Years {0}–{1} · {2} days per year', N'السنوات {0}–{1} · {2} يوماً عن كل سنة', NULL),
    ('fs.years_x_y_months_per_year', 'fs', N'Years {0}–{1} · {2} month per year', N'السنوات {0}–{1} · {2} شهر عن كل سنة', NULL),
    ('fs.years_x_plus_days_per_year', 'fs', N'Years {0}+ · {1} days per year', N'السنوات {0} فأكثر · {1} يوماً عن كل سنة', NULL),
    ('fs.years_x_plus_months_per_year', 'fs', N'Years {0}+ · {1} month per year', N'السنوات {0} فأكثر · {1} شهر عن كل سنة', NULL),
    ('fs.gross_indemnity', 'fs', N'Gross indemnity', N'إجمالي المكافأة', NULL),
    ('fs.cap_reached', 'fs', N'Capped at KWD {0}', N'بحد أقصى {0} د.ك', NULL),
    ('fs.cap_not_reached', 'fs', N'Cap KWD {0} not reached', N'لم يبلغ الحد الأقصى {0} د.ك', NULL),
    ('fs.no_cap', 'fs', N'No cap', N'بلا حد أقصى', NULL),
    ('fs.entitlement_for_0', 'fs', N'Entitlement for {0}', N'نسبة الاستحقاق عند {0}', NULL),
    ('fs.entitlement_rule', 'fs', N'By separation type and {0} years of service', N'حسب نوع إنهاء الخدمة و{0} سنة خدمة', NULL),
    ('fs.indemnity_payable', 'fs', N'Indemnity payable', N'المكافأة المستحقة', NULL),
    ('fs.below_min_service', 'fs', N'Service is shorter than the minimum of the rule set - no indemnity.', N'مدة الخدمة أقل من الحد الأدنى في القواعد - لا تستحق مكافأة.', NULL),
    ('fs.recoveries', 'fs', N'Recoveries', N'الاستقطاعات', NULL),
    ('fs.no_recoveries', 'fs', N'Nothing to recover.', N'لا توجد مبالغ للاستقطاع.', NULL),
    ('fs.salary_paid_after_last_day', 'fs', N'Salary paid after the last working day', N'راتب مدفوع بعد آخر يوم عمل', NULL),
    ('fs.balance_of_0_1_of_2_left', 'fs', N'Balance of {0} · {1} of {2} instalments left', N'الرصيد من {0} · متبقٍ {1} من {2} أقساط', NULL),
    ('fs.added_by_hand', 'fs', N'Added by hand', N'أُضيف يدوياً', NULL),
    ('fs.waived', 'fs', N'Waived', N'معفى', NULL),
    ('fs.waive', 'fs', N'Waive', N'إعفاء', NULL),
    ('fs.waive_0', 'fs', N'Waive {0}', N'إعفاء {0}', NULL),
    ('fs.include_again', 'fs', N'Include again', N'إعادة الإدراج', NULL),
    ('fs.include_again_0', 'fs', N'Include {0} again', N'إعادة إدراج {0}', NULL),
    ('fs.remove_0', 'fs', N'Remove {0}', N'حذف {0}', NULL),
    ('fs.add_earning', 'fs', N'Add an earning', N'إضافة استحقاق', NULL),
    ('fs.add_recovery', 'fs', N'Add a recovery', N'إضافة استقطاع', NULL),
    ('fs.description', 'fs', N'Description', N'الوصف', NULL),
    ('fs.earning_placeholder', 'fs', N'Air ticket, notice pay in lieu ...', N'تذكرة سفر، بدل فترة الإشعار ...', NULL),
    ('fs.recovery_placeholder', 'fs', N'Company asset not returned ...', N'عهدة لم تُسلّم ...', NULL),
    ('fs.sugg_ticket', 'fs', N'Air ticket', N'تذكرة سفر', NULL),
    ('fs.sugg_notice_pay', 'fs', N'Notice period pay in lieu', N'بدل فترة الإشعار', NULL),
    ('fs.sugg_bonus', 'fs', N'Bonus', N'مكافأة', NULL),
    ('fs.sugg_asset', 'fs', N'Company asset not returned', N'عهدة لم تُسلّم', NULL),
    ('fs.sugg_notice_shortfall', 'fs', N'Notice period not served', N'فترة إشعار لم تُستكمل', NULL),
    ('fs.sugg_advance', 'fs', N'Salary advance', N'سلفة راتب', NULL),
    ('fs.add', 'fs', N'Add', N'إضافة', NULL),
    ('fs.summary', 'fs', N'Summary', N'الملخص', NULL),
    ('fs.net_payable', 'fs', N'Net payable', N'صافي المستحق', NULL),
    ('fs.calculated_on', 'fs', N'Calculated {0}', N'احتُسبت في {0}', NULL),
    ('fs.ack_unverified', 'fs', N'I have checked the indemnity - the rule set is not verified yet.', N'راجعت مكافأة نهاية الخدمة - القواعد غير مؤكدة بعد.', NULL),
    ('fs.recalculate', 'fs', N'Recalculate', N'إعادة الاحتساب', NULL),
    ('fs.own_submission', 'fs', N'You sent this settlement for approval, so another approver must decide.', N'أرسلت هذه التسوية للاعتماد، لذا يجب أن يقرر معتمِد آخر.', NULL),
    ('fs.approve_hr', 'fs', N'HR approval', N'اعتماد الموارد البشرية', NULL),
    ('fs.approve_finance', 'fs', N'Finance approval', N'اعتماد المالية', NULL),
    ('fs.approve_hr_text', 'fs', N'Approve the settlement. The Finance Manager approves it next.', N'اعتماد التسوية. يعتمدها المدير المالي بعد ذلك.', NULL),
    ('fs.approve_finance_text', 'fs', N'Final approval: the employee is marked as left on the last working day, recovered loans are closed and the settlement is ready to be paid.', N'الاعتماد النهائي: يُسجّل الموظف كمنتهي الخدمة في آخر يوم عمل، وتُقفل القروض المستقطعة، وتصبح التسوية جاهزة للدفع.', NULL),
    ('fs.approve_finance_text_enc', 'fs', N'Final approval: the encashment is added as a one-time earning to the payroll of the month chosen.', N'الاعتماد النهائي: يُضاف بدل الإجازة كاستحقاق لمرة واحدة إلى مسير الشهر المختار.', NULL),
    ('fs.return', 'fs', N'Return', N'إعادة', NULL),
    ('fs.return_title', 'fs', N'Return to draft', N'إعادة إلى المسودة', NULL),
    ('fs.return_text', 'fs', N'The settlement goes back to the preparer to correct. Say what needs to change.', N'تعود التسوية إلى المُعدّ للتصحيح. وضّح ما يجب تغييره.', NULL),
    ('fs.reject_title', 'fs', N'Reject settlement', N'رفض التسوية', NULL),
    ('fs.reject_text', 'fs', N'The settlement is cancelled and keeps its number. Enter the reason.', N'تُلغى التسوية وتحتفظ برقمها. أدخل السبب.', NULL),
    ('fs.record_payment', 'fs', N'Record payment', N'تسجيل الدفع', NULL),
    ('fs.record_payment_text', 'fs', N'Record how the net payable of KWD {0} was paid. The settlement is then closed.', N'سجّل طريقة دفع صافي المستحق {0} د.ك. ثم تُقفل التسوية.', NULL),
    ('fs.payment_date', 'fs', N'Payment date', N'تاريخ الدفع', NULL),
    ('fs.paid_by', 'fs', N'Paid by', N'طريقة الدفع', NULL),
    ('fs.payment_reference', 'fs', N'Reference', N'المرجع', NULL),
    ('fs.payment_reference_placeholder', 'fs', N'Transfer or cheque number', N'رقم التحويل أو الشيك', NULL),
    ('fs.statement_en_ar', 'fs', N'Settlement statement (EN/AR)', N'كشف التسوية (عربي/إنجليزي)', NULL),
    ('fs.cancel_settlement', 'fs', N'Cancel settlement', N'إلغاء التسوية', NULL),
    ('fs.cancel_title', 'fs', N'Cancel settlement', N'إلغاء التسوية', NULL),
    ('fs.cancel_text', 'fs', N'The settlement is cancelled and keeps its number. The employee is not changed.', N'تُلغى التسوية وتحتفظ برقمها. لا يتغير شيء في بيانات الموظف.', NULL),
    ('fs.approval_route', 'fs', N'Approval route', N'مسار الاعتماد', NULL),
    ('fs.prepared', 'fs', N'Prepared', N'الإعداد', NULL),
    ('fs.level_hr_hint', 'fs', N'Level 1 - HR Manager', N'المستوى 1 - مدير الموارد البشرية', NULL),
    ('fs.level_finance_hint', 'fs', N'Level 2 - Finance Manager', N'المستوى 2 - المدير المالي', NULL),
    ('fs.payment', 'fs', N'Payment', N'الدفع', NULL),
    ('fs.paid_by_payroll', 'fs', N'Paid by payroll', N'يُصرف عبر المسير', NULL),
    ('fs.in_payroll_of', 'fs', N'In the payroll of {0}', N'في مسير {0}', NULL),
    ('fs.payment_hint', 'fs', N'Bank transfer, cheque or cash once approved', N'تحويل بنكي أو شيك أو نقداً بعد الاعتماد', NULL),
    ('fs.h_created', 'fs', N'Created', N'أُنشئت', NULL),
    ('fs.h_changed', 'fs', N'Changed', N'عُدّلت', NULL),
    ('fs.h_line_added', 'fs', N'Line added', N'أُضيف بند', NULL),
    ('fs.h_line_removed', 'fs', N'Line removed', N'حُذف بند', NULL),
    ('fs.h_line_waived', 'fs', N'Line waived', N'أُعفي بند', NULL),
    ('fs.h_line_restored', 'fs', N'Line included again', N'أُعيد إدراج بند', NULL),
    ('fs.h_submitted', 'fs', N'Sent for approval', N'أُرسلت للاعتماد', NULL),
    ('fs.h_approved_hr', 'fs', N'Approved by HR', N'اعتمدتها الموارد البشرية', NULL),
    ('fs.h_approved_finance', 'fs', N'Approved by Finance', N'اعتمدتها المالية', NULL),
    ('fs.h_returned', 'fs', N'Returned to draft', N'أُعيدت إلى المسودة', NULL),
    ('fs.h_rejected', 'fs', N'Rejected', N'رُفضت', NULL),
    ('fs.h_paid', 'fs', N'Paid', N'دُفعت', NULL),
    ('fs.h_cancelled', 'fs', N'Cancelled', N'أُلغيت', NULL),
    ('fs.back_to_settlement', 'fs', N'Back to the settlement', N'العودة إلى التسوية', NULL),
    ('fs.print', 'fs', N'Print', N'طباعة', NULL),
    ('fs.st_title', 'fs', N'Final Settlement Statement', N'كشف التسوية النهائية لمستحقات نهاية الخدمة', NULL),
    ('fs.st_title_encashment', 'fs', N'Leave Encashment Statement', N'كشف صرف بدل رصيد الإجازات', NULL),
    ('fs.st_not_final', 'fs', N'DRAFT - NOT APPROVED', N'مسودة - غير معتمدة', NULL),
    ('fs.st_settlement_no', 'fs', N'Settlement no.', N'رقم التسوية', NULL),
    ('fs.st_date', 'fs', N'Date', N'التاريخ', NULL),
    ('fs.st_employee', 'fs', N'Employee', N'الموظف', NULL),
    ('fs.st_employee_no', 'fs', N'Employee no.', N'الرقم الوظيفي', NULL),
    ('fs.st_department', 'fs', N'Department', N'الإدارة', NULL),
    ('fs.st_designation', 'fs', N'Designation', N'المسمى الوظيفي', NULL),
    ('fs.st_nationality', 'fs', N'Nationality', N'الجنسية', NULL),
    ('fs.st_type', 'fs', N'Separation', N'سبب انتهاء الخدمة', NULL),
    ('fs.st_joined', 'fs', N'Date joined', N'تاريخ الالتحاق', NULL),
    ('fs.st_last_day', 'fs', N'Last working day', N'آخر يوم عمل', NULL),
    ('fs.st_balance_on', 'fs', N'Leave balance on', N'رصيد الإجازات في', NULL),
    ('fs.st_service', 'fs', N'Service', N'مدة الخدمة', NULL),
    ('fs.st_monthly_salary', 'fs', N'Monthly salary', N'الراتب الشهري', NULL),
    ('fs.st_indemnity_salary', 'fs', N'Indemnity salary', N'راتب احتساب المكافأة', NULL),
    ('fs.st_leave_salary', 'fs', N'Leave salary', N'راتب احتساب الإجازة', NULL),
    ('fs.st_pay_month', 'fs', N'Paid in payroll', N'يُصرف في مسير', NULL),
    ('fs.st_entitlement', 'fs', N'Entitlement', N'البيان', NULL),
    ('fs.st_amount_kwd', 'fs', N'Amount (KWD)', N'المبلغ (د.ك)', NULL),
    ('fs.st_total_entitlements', 'fs', N'Total entitlements', N'إجمالي المستحقات', NULL),
    ('fs.st_details', 'fs', N'Details', N'التفاصيل', NULL),
    ('fs.st_paid_on', 'fs', N'Paid on {0} · {1}', N'دُفعت في {0} · {1}', NULL),
    ('fs.st_declaration', 'fs', N'I, the undersigned, acknowledge receipt of KWD {0} in full and final settlement of all my dues from the company, and that I have no further claims against it.', N'أقر أنا الموقع أدناه باستلامي مبلغ {0} د.ك تسويةً نهائية وكاملة لجميع مستحقاتي لدى الشركة، وأنه لا توجد لي أي مطالبات أخرى تجاهها.', NULL),
    ('fs.st_declaration_encashment', 'fs', N'I, the undersigned, acknowledge that KWD {0} is paid to me as encashment of the leave days stated above, which are deducted from my leave balance.', N'أقر أنا الموقع أدناه بأن مبلغ {0} د.ك يُصرف لي بدلاً عن أيام الإجازة المذكورة أعلاه، والتي تُخصم من رصيد إجازاتي.', NULL),
    ('fs.st_sign_employee', 'fs', N'Employee signature', N'توقيع الموظف', NULL),
    ('fs.st_generated', 'fs', N'Printed {0}', N'طُبع في {0}', NULL),
    ('js.fs_failed', 'js', N'The request could not be completed.', N'تعذّر إكمال الطلب.', NULL),
    ('js.fs_fill_required', 'js', N'Fill in the fields marked *.', N'املأ الحقول المعلّمة بـ *.', NULL),
    ('js.fs_from_hint', 'js', N'Paid up to {0} by payroll {1}.', N'مدفوع حتى {0} في المسير {1}.', NULL),
    ('js.fs_from_hint_none', 'js', N'No closed payroll has paid this employee - check the date.', N'لم يُصرف للموظف في أي مسير مغلق - تحقق من التاريخ.', NULL),
    ('js.fs_no_payroll_yet', 'js', N'No closed payroll yet', N'لا يوجد مسير مغلق بعد', NULL),
    ('js.fs_no_rules', 'js', N'None in force', N'لا توجد قواعد سارية', NULL),
    ('js.fs_not_verified', 'js', N'not verified', N'غير مؤكدة', NULL),
    ('js.fs_service', 'js', N'{0} years {1} months {2} days', N'{0} سنة {1} شهر {2} يوم', NULL),
    ('js.fs_tick_ack', 'js', N'Tick the box to confirm you have checked the indemnity.', N'ضع علامة في المربع لتأكيد مراجعة المكافأة.', NULL),
    ('msg.fs_this_settlement_no_longer_exists', 'msg', N'This settlement no longer exists.', N'هذه التسوية لم تعد موجودة.', N'This settlement no longer exists.'),
    ('msg.fs_only_a_draft_settlement_can_be_changed_return_it_to_draft_first', 'msg', N'Only a draft settlement can be changed. Return it to draft first.', N'لا يمكن تعديل إلا التسوية في حالة المسودة. أعدها إلى المسودة أولاً.', N'Only a draft settlement can be changed. Return it to draft first.'),
    ('msg.fs_the_employee_of_a_settlement_cannot_be_changed_cancel_it_and_st', 'msg', N'The employee of a settlement cannot be changed. Cancel it and start a new one.', N'لا يمكن تغيير موظف التسوية. ألغها وابدأ تسوية جديدة.', N'The employee of a settlement cannot be changed. Cancel it and start a new one.'),
    ('msg.fs_a_leave_encashment_cannot_be_turned_into_an_exit_settlement_or', 'msg', N'A leave encashment cannot be turned into an exit settlement (or back). Cancel it and start a new one.', N'لا يمكن تحويل صرف بدل الإجازة إلى تسوية نهاية خدمة (أو العكس). ألغها وابدأ تسوية جديدة.', N'A leave encashment cannot be turned into an exit settlement (or back). Cancel it and start a new one.'),
    ('msg.fs_select_an_employee', 'msg', N'Select an employee.', N'اختر موظفاً.', N'Select an employee.'),
    ('msg.fs_the_employee_has_no_hire_date_enter_it_on_the_employment_tab_of', 'msg', N'The employee has no hire date. Enter it on the Employment tab of the employee profile first.', N'لا يوجد تاريخ التحاق للموظف. أدخله في تبويب التوظيف في ملف الموظف أولاً.', N'The employee has no hire date. Enter it on the Employment tab of the employee profile first.'),
    ('msg.fs_select_the_separation_type', 'msg', N'Select the separation type.', N'اختر نوع إنهاء الخدمة.', N'Select the separation type.'),
    ('msg.fs_enter_the_last_working_day', 'msg', N'Enter the last working day.', N'أدخل آخر يوم عمل.', N'Enter the last working day.'),
    ('msg.fs_the_last_working_day_cannot_be_before_the_hire_date', 'msg', N'The last working day cannot be before the hire date.', N'لا يمكن أن يكون آخر يوم عمل قبل تاريخ الالتحاق.', N'The last working day cannot be before the hire date.'),
    ('msg.fs_the_last_working_day_cannot_be_more_than_a_year_ahead', 'msg', N'The last working day cannot be more than a year ahead.', N'لا يمكن أن يكون آخر يوم عمل بعد أكثر من سنة من اليوم.', N'The last working day cannot be more than a year ahead.'),
    ('msg.fs_the_notice_date_cannot_be_after_the_last_working_day', 'msg', N'The notice date cannot be after the last working day.', N'لا يمكن أن يكون تاريخ الإشعار بعد آخر يوم عمل.', N'The notice date cannot be after the last working day.'),
    ('msg.fs_this_employee_already_has_a_final_settlement_open_it_from_the_l', 'msg', N'This employee already has a final settlement. Open it from the list, or cancel it to start again.', N'لدى هذا الموظف تسوية نهائية بالفعل. افتحها من القائمة، أو ألغها للبدء من جديد.', N'This employee already has a final settlement. Open it from the list, or cancel it to start again.'),
    ('msg.fs_this_employee_has_left_encash_the_leave_in_the_final_settlement', 'msg', N'This employee has left. Encash the leave in the final settlement instead.', N'انتهت خدمة هذا الموظف. اصرف بدل الإجازة ضمن التسوية النهائية بدلاً من ذلك.', N'This employee has left. Encash the leave in the final settlement instead.'),
    ('msg.fs_enter_a_leave_balance_between_0_and_999_days', 'msg', N'Enter a leave balance between 0 and 999 days.', N'أدخل رصيد إجازات بين 0 و999 يوماً.', N'Enter a leave balance between 0 and 999 days.'),
    ('msg.fs_the_days_to_encash_cannot_be_more_than_the_leave_balance', 'msg', N'The days to encash cannot be more than the leave balance.', N'لا يمكن أن تزيد الأيام المطلوب صرفها عن رصيد الإجازات.', N'The days to encash cannot be more than the leave balance.'),
    ('msg.fs_enter_the_number_of_days_to_encash', 'msg', N'Enter the number of days to encash.', N'أدخل عدد الأيام المطلوب صرفها.', N'Enter the number of days to encash.'),
    ('msg.fs_select_the_payroll_month_that_pays_the_encashment', 'msg', N'Select the payroll month that pays the encashment.', N'اختر شهر المسير الذي يُصرف فيه البدل.', N'Select the payroll month that pays the encashment.'),
    ('msg.fs_the_payroll_of_that_month_is_already_closed_choose_a_later_mont', 'msg', N'The payroll of that month is already closed. Choose a later month.', N'مسير ذلك الشهر مغلق بالفعل. اختر شهراً لاحقاً.', N'The payroll of that month is already closed. Choose a later month.'),
    ('msg.fs_salary_unpaid_from_cannot_be_before_the_hire_date', 'msg', N'Salary unpaid from cannot be before the hire date.', N'لا يمكن أن يكون تاريخ «الراتب غير مدفوع من» قبل تاريخ الالتحاق.', N'Salary unpaid from cannot be before the hire date.'),
    ('msg.fs_salary_is_already_paid_up_to_0_by_payroll_1_salary_unpaid_from', 'msg', N'Salary is already paid up to {0} by payroll {1}. Salary unpaid from must be after it.', N'الراتب مدفوع حتى {0} في المسير {1}. يجب أن يكون «الراتب غير مدفوع من» بعده.', N'Salary is already paid up to {0} by payroll {1}. Salary unpaid from must be after it.'),
    ('msg.fs_salary_unpaid_from_cannot_be_after_the_day_following_the_last_w', 'msg', N'Salary unpaid from cannot be after the day following the last working day.', N'لا يمكن أن يكون «الراتب غير مدفوع من» بعد اليوم التالي لآخر يوم عمل.', N'Salary unpaid from cannot be after the day following the last working day.'),
    ('msg.fs_salary_unpaid_from_cannot_be_more_than_12_months_before_the_las', 'msg', N'Salary unpaid from cannot be more than 12 months before the last working day.', N'لا يمكن أن يكون «الراتب غير مدفوع من» قبل آخر يوم عمل بأكثر من 12 شهراً.', N'Salary unpaid from cannot be more than 12 months before the last working day.'),
    ('msg.fs_settlement_created_and_calculated', 'msg', N'Settlement created and calculated.', N'أُنشئت التسوية واحتُسبت.', N'Settlement created and calculated.'),
    ('msg.fs_settlement_saved_and_recalculated', 'msg', N'Settlement saved and recalculated.', N'حُفظت التسوية وأُعيد احتسابها.', N'Settlement saved and recalculated.'),
    ('msg.fs_settlement_recalculated', 'msg', N'Settlement recalculated.', N'أُعيد احتساب التسوية.', N'Settlement recalculated.'),
    ('msg.fs_choose_whether_the_line_is_paid_to_the_employee_or_recovered', 'msg', N'Choose whether the line is paid to the employee or recovered.', N'حدد إن كان البند يُصرف للموظف أم يُستقطع منه.', N'Choose whether the line is paid to the employee or recovered.'),
    ('msg.fs_enter_a_description_what_is_paid_or_recovered_and_why', 'msg', N'Enter a description - what is paid or recovered and why.', N'أدخل وصفاً - ما الذي يُصرف أو يُستقطع ولماذا.', N'Enter a description - what is paid or recovered and why.'),
    ('msg.fs_enter_an_amount_greater_than_zero', 'msg', N'Enter an amount greater than zero.', N'أدخل مبلغاً أكبر من صفر.', N'Enter an amount greater than zero.'),
    ('msg.fs_this_line_no_longer_exists', 'msg', N'This line no longer exists.', N'هذا البند لم يعد موجوداً.', N'This line no longer exists.'),
    ('msg.fs_calculated_lines_cannot_be_removed_change_the_inputs_or_waive_a', 'msg', N'Calculated lines cannot be removed. Change the inputs, or waive a pay item or loan line.', N'لا يمكن حذف البنود المحتسبة. غيّر المدخلات، أو أعفِ بند راتب أو قرض.', N'Calculated lines cannot be removed. Change the inputs, or waive a pay item or loan line.'),
    ('msg.fs_only_pay_item_and_loan_lines_can_be_waived', 'msg', N'Only pay item and loan lines can be waived.', N'لا يمكن الإعفاء إلا من بنود الرواتب والقروض.', N'Only pay item and loan lines can be waived.'),
    ('msg.fs_line_added', 'msg', N'Line added.', N'تمت إضافة البند.', N'Line added.'),
    ('msg.fs_line_removed', 'msg', N'Line removed.', N'حُذف البند.', N'Line removed.'),
    ('msg.fs_line_waived_it_is_not_recovered_or_paid', 'msg', N'Line waived - it is not recovered or paid.', N'أُعفي البند - لن يُستقطع ولن يُصرف.', N'Line waived - it is not recovered or paid.'),
    ('msg.fs_line_included_again', 'msg', N'Line included again.', N'أُعيد إدراج البند.', N'Line included again.'),
    ('msg.fs_payroll_0_has_already_paid_salary_for_days_this_settlement_pays', 'msg', N'Payroll {0} has already paid salary for days this settlement pays. Change Salary unpaid from and recalculate.', N'المسير {0} صرف بالفعل راتب أيام تشملها هذه التسوية. غيّر «الراتب غير مدفوع من» وأعد الاحتساب.', N'Payroll {0} has already paid salary for days this settlement pays. Change Salary unpaid from and recalculate.'),
    ('msg.fs_no_indemnity_rule_set_is_in_force_on_the_last_working_day_add_o', 'msg', N'No indemnity rule set is in force on the last working day. Add one in Payroll Settings first.', N'لا توجد قواعد مكافأة سارية في آخر يوم عمل. أضفها في إعدادات الرواتب أولاً.', N'No indemnity rule set is in force on the last working day. Add one in Payroll Settings first.'),
    ('msg.fs_the_indemnity_rule_set_is_not_verified_yet_confirm_that_you_hav', 'msg', N'The indemnity rule set is not verified yet. Confirm that you have checked the indemnity, then submit again.', N'قواعد المكافأة غير مؤكدة بعد. أكّد أنك راجعت المكافأة ثم أعد الإرسال.', N'The indemnity rule set is not verified yet. Confirm that you have checked the indemnity, then submit again.'),
    ('msg.fs_payroll_0_still_includes_this_employee_for_days_this_settlement', 'msg', N'Payroll {0} still includes this employee for days this settlement pays. Recalculate it on the Payroll Register (or cancel it) first.', N'المسير {0} ما زال يشمل هذا الموظف عن أيام تدفعها هذه التسوية. أعد احتسابه في سجل الرواتب (أو ألغه) أولاً.', N'Payroll {0} still includes this employee for days this settlement pays. Recalculate it on the Payroll Register (or cancel it) first.'),
    ('msg.fs_sent_for_approval_to_the_hr_manager', 'msg', N'Sent for approval to the HR Manager.', N'أُرسلت للاعتماد إلى مدير الموارد البشرية.', N'Sent for approval to the HR Manager.'),
    ('msg.fs_this_settlement_is_not_waiting_for_approval', 'msg', N'This settlement is not waiting for approval.', N'هذه التسوية ليست بانتظار الاعتماد.', N'This settlement is not waiting for approval.'),
    ('msg.fs_this_settlement_was_approved_by_someone_else_meanwhile_the_page', 'msg', N'This settlement was approved by someone else meanwhile. The page has been refreshed.', N'اعتمد شخص آخر هذه التسوية في هذه الأثناء. تم تحديث الصفحة.', N'This settlement was approved by someone else meanwhile. The page has been refreshed.'),
    ('msg.fs_you_cannot_approve_a_settlement_you_sent_for_approval_or_alread', 'msg', N'You cannot approve a settlement you sent for approval or already approved at the previous level.', N'لا يمكنك اعتماد تسوية أرسلتها للاعتماد أو اعتمدتها في المستوى السابق.', N'You cannot approve a settlement you sent for approval or already approved at the previous level.'),
    ('msg.fs_the_settlement_now_calculates_to_0_instead_of_1_payroll_or_pay', 'msg', N'The settlement now calculates to {0} instead of {1} (payroll or pay items changed since it was submitted). Return it to draft, check it and submit it again.', N'أصبحت التسوية تُحتسب {0} بدلاً من {1} (تغيرت المسيرات أو بنود الرواتب منذ إرسالها). أعدها إلى المسودة وراجعها ثم أرسلها مجدداً.', N'The settlement now calculates to {0} instead of {1} (payroll or pay items changed since it was submitted). Return it to draft, check it and submit it again.'),
    ('msg.fs_approved_waiting_for_the_finance_manager', 'msg', N'Approved. Waiting for the Finance Manager.', N'تم الاعتماد. بانتظار المدير المالي.', N'Approved. Waiting for the Finance Manager.'),
    ('msg.fs_the_payroll_of_the_month_chosen_for_the_encashment_is_already_c', 'msg', N'The payroll of the month chosen for the encashment is already closed. Return the settlement and choose a later month.', N'مسير الشهر المختار لصرف البدل مغلق بالفعل. أعد التسوية واختر شهراً لاحقاً.', N'The payroll of the month chosen for the encashment is already closed. Return the settlement and choose a later month.'),
    ('msg.fs_approved_the_encashment_is_paid_by_the_payroll_of_the_month_cho', 'msg', N'Approved. The encashment is paid by the payroll of the month chosen.', N'تم الاعتماد. يُصرف البدل في مسير الشهر المختار.', N'Approved. The encashment is paid by the payroll of the month chosen.'),
    ('msg.fs_approved_the_employee_is_marked_as_left_and_the_settlement_is_r', 'msg', N'Approved. The employee is marked as left and the settlement is ready to be paid.', N'تم الاعتماد. سُجّل الموظف كمنتهي الخدمة والتسوية جاهزة للدفع.', N'Approved. The employee is marked as left and the settlement is ready to be paid.'),
    ('msg.fs_enter_a_comment_explaining_what_needs_to_be_corrected', 'msg', N'Enter a comment explaining what needs to be corrected.', N'أدخل تعليقاً يوضح ما يجب تصحيحه.', N'Enter a comment explaining what needs to be corrected.'),
    ('msg.fs_enter_the_reason_for_rejecting_it', 'msg', N'Enter the reason for rejecting it.', N'أدخل سبب الرفض.', N'Enter the reason for rejecting it.'),
    ('msg.fs_returned_to_draft_with_your_comment', 'msg', N'Returned to draft with your comment.', N'أُعيدت إلى المسودة مع تعليقك.', N'Returned to draft with your comment.'),
    ('msg.fs_settlement_rejected_and_cancelled', 'msg', N'Settlement rejected and cancelled.', N'رُفضت التسوية وأُلغيت.', N'Settlement rejected and cancelled.'),
    ('msg.fs_only_an_approved_settlement_can_be_marked_as_paid', 'msg', N'Only an approved settlement can be marked as paid.', N'لا يمكن تسجيل الدفع إلا لتسوية معتمدة.', N'Only an approved settlement can be marked as paid.'),
    ('msg.fs_enter_the_payment_date_today_or_earlier', 'msg', N'Enter the payment date (today or earlier).', N'أدخل تاريخ الدفع (اليوم أو قبله).', N'Enter the payment date (today or earlier).'),
    ('msg.fs_select_how_it_was_paid', 'msg', N'Select how it was paid.', N'اختر طريقة الدفع.', N'Select how it was paid.'),
    ('msg.fs_enter_the_bank_transfer_or_cheque_reference', 'msg', N'Enter the bank transfer or cheque reference.', N'أدخل مرجع التحويل البنكي أو الشيك.', N'Enter the bank transfer or cheque reference.'),
    ('msg.fs_payment_recorded_the_settlement_is_closed', 'msg', N'Payment recorded. The settlement is closed.', N'سُجّل الدفع. أُقفلت التسوية.', N'Payment recorded. The settlement is closed.'),
    ('msg.fs_an_approved_or_paid_settlement_cannot_be_cancelled', 'msg', N'An approved or paid settlement cannot be cancelled.', N'لا يمكن إلغاء تسوية معتمدة أو مدفوعة.', N'An approved or paid settlement cannot be cancelled.'),
    ('msg.fs_enter_the_reason_for_cancelling_this_settlement', 'msg', N'Enter the reason for cancelling this settlement.', N'أدخل سبب إلغاء هذه التسوية.', N'Enter the reason for cancelling this settlement.'),
    ('msg.fs_settlement_cancelled_it_keeps_its_number', 'msg', N'Settlement cancelled. It keeps its number.', N'أُلغيت التسوية. تحتفظ برقمها.', N'Settlement cancelled. It keeps its number.'),
    ('msg.fs_check_the_dates_and_numbers_one_of_them_is_not_a_valid_value', 'msg', N'Check the dates and numbers - one of them is not a valid value.', N'تحقق من التواريخ والأرقام - إحدى القيم غير صحيحة.', N'Check the dates and numbers - one of them is not a valid value.'),
    ('msg.fs_you_are_not_an_approver_for_this_level', 'msg', N'You are not an approver for this level.', N'لست معتمِداً لهذا المستوى.', N'You are not an approver for this level.'),
    ('msg.fs_unsupported_action', 'msg', N'Unsupported action.', N'إجراء غير مدعوم.', N'Unsupported action.');
INSERT INTO [Core].[UiLabels] (LabelKey, Module, EnglishText, ArabicText, SourceText)
SELECT s.LabelKey, s.Module, s.EnglishText, s.ArabicText, s.SourceText
FROM   #Seed AS s
WHERE  NOT EXISTS (SELECT 1 FROM [Core].[UiLabels] AS l WHERE l.LabelKey = s.LabelKey AND l.Deleted = 0);

DECLARE @Inserted INT = @@ROWCOUNT;

UPDATE l
   SET l.ArabicText = ISNULL(NULLIF(l.ArabicText, N''), s.ArabicText),
       l.SourceText = ISNULL(l.SourceText, s.SourceText)
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.LabelKey = l.LabelKey
WHERE  l.Deleted = 0
  AND (   (NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL)
       OR (l.SourceText IS NULL AND s.SourceText IS NOT NULL));

DECLARE @Completed INT = @@ROWCOUNT;

/* procedure messages of db/40 harvested by an earlier run of db/33 (msg.auto_*) get their Arabic too */
UPDATE l
   SET l.ArabicText = s.ArabicText
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.Module = 'msg' AND l.EnglishText = s.EnglishText COLLATE Latin1_General_BIN
WHERE  l.Deleted = 0 AND l.LabelKey LIKE 'msg.auto[_]%' AND NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL;

PRINT CONCAT(N'Final settlement labels inserted: ', @Inserted, N', completed: ', @Completed);
DROP TABLE #Seed;
GO
