/* =====================================================================
   46_Payroll_Settings_Labels.sql  -  HRMS: English + Arabic labels of the
   Payroll Settings screens (Payroll > Payroll Settings)
   ---------------------------------------------------------------------
   Run after 33 (Core.UiLabels). Only labels - the screens use the
   procedures of db/30 (and later db/47+). Idempotent: new keys are
   inserted, existing keys only completed (text already edited in
   Core.UiLabels is never overwritten).

     st.*       Payroll Settings screens
     js.st_*    wwwroot/js/payroll-settings.js
     msg.st_*   messages of the settings procedures - matched by SourceText
   ===================================================================== */
SET NOCOUNT ON;
GO
IF OBJECT_ID(N'tempdb..#Seed') IS NOT NULL DROP TABLE #Seed;
CREATE TABLE #Seed (
    LabelKey    VARCHAR(150)   COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
    Module      VARCHAR(30)    COLLATE DATABASE_DEFAULT NOT NULL,
    EnglishText NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL,
    ArabicText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
    SourceText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL
);
INSERT INTO #Seed (LabelKey, Module, EnglishText, ArabicText, SourceText) VALUES
    ('js.st_failed', 'js', N'The request could not be completed.', N'تعذّر إتمام الطلب.', NULL),
    ('st.title_pay_item_types', 'st', N'Pay Item Types', N'أنواع بنود الرواتب', N'Pay Item Types'),
    ('st.item_types_subtitle', 'st', N'The earnings and deductions offered when adding a pay item, and how the payroll treats them', N'الاستحقاقات والاستقطاعات المتاحة عند إضافة بند راتب، وكيف يعاملها مسير الرواتب', NULL),
    ('st.item_types_banner_title', 'st', N'Data-driven.', N'تُدار من البيانات.', NULL),
    ('st.item_types_banner_text', 'st', N'Add, rename or deactivate item types without any code change. Standard types (Basic Salary, PIFSS, Loan ...) are known to the payroll engine: they can be renamed and re-flagged but not deleted.', N'أضف أنواع البنود أو أعد تسميتها أو أوقفها دون أي تعديل برمجي. الأنواع القياسية (الراتب الأساسي، التأمينات، القرض ...) يعرفها محرك الرواتب: يمكن إعادة تسميتها وتعديل خصائصها دون حذفها.', NULL),
    ('st.add_item_type', 'st', N'Add item type', N'إضافة نوع بند', NULL),
    ('st.edit_item_type', 'st', N'Edit item type', N'تعديل نوع البند', NULL),
    ('st.delete_item_type_text', 'st', N'Delete this item type? It can only be deleted while no salary structure uses it.', N'حذف نوع البند هذا؟ لا يمكن حذفه إلا إذا لم يُستخدم في أي هيكل رواتب.', NULL),
    ('st.add_standard_types', 'st', N'Add standard types', N'إضافة الأنواع القياسية', NULL),
    ('st.add_standard_types_hint', 'st', N'Adds the standard item types this company is missing (Basic Salary, PIFSS, Loan ...)', N'يضيف الأنواع القياسية الناقصة لهذه الشركة (الراتب الأساسي، التأمينات، القرض ...)', NULL),
    ('st.search_item_types', 'st', N'Search code, name or GL account', N'ابحث بالرمز أو الاسم أو حساب الأستاذ', NULL),
    ('st.type', 'st', N'Type', N'النوع', NULL),
    ('st.all_types', 'st', N'All types', N'جميع الأنواع', NULL),
    ('st.earnings', 'st', N'Earnings', N'الاستحقاقات', NULL),
    ('st.deductions', 'st', N'Deductions', N'الاستقطاعات', NULL),
    ('st.1_item_type', 'st', N'1 item type', N'نوع بند واحد', NULL),
    ('st.0_item_types', 'st', N'{0} item types', N'{0} أنواع بنود', NULL),
    ('st.no_item_types_match', 'st', N'No item type matches your search', N'لا يوجد نوع بند يطابق البحث', NULL),
    ('st.no_item_types_yet', 'st', N'No item types yet', N'لا توجد أنواع بنود بعد', NULL),
    ('st.no_item_types_text', 'st', N'Use Add standard types to load Basic Salary, PIFSS, Loan and the other standard types, then add your own.', N'استخدم إضافة الأنواع القياسية لتحميل الراتب الأساسي والتأمينات والقرض وغيرها، ثم أضف أنواعك.', NULL),
    ('st.pay_item_types', 'st', N'Pay item types', N'أنواع بنود الرواتب', NULL),
    ('st.item_type', 'st', N'Item type', N'نوع البند', NULL),
    ('st.class', 'st', N'Class', N'الفئة', NULL),
    ('st.class_salary', 'st', N'Salary', N'راتب', NULL),
    ('st.class_earning', 'st', N'Earning', N'استحقاق', NULL),
    ('st.class_deduction', 'st', N'Deduction', N'استقطاع', NULL),
    ('st.class_loan', 'st', N'Loan / advance', N'قرض / سلفة', NULL),
    ('st.class_statutory', 'st', N'Statutory', N'نظامي', NULL),
    ('st.calculation', 'st', N'Calculation', N'طريقة الحساب', NULL),
    ('st.included_in', 'st', N'Included in', N'يدخل في', NULL),
    ('st.gl_account', 'st', N'GL account', N'حساب الأستاذ العام', NULL),
    ('st.gl_account_name', 'st', N'GL account name', N'اسم حساب الأستاذ العام', NULL),
    ('st.standard', 'st', N'Standard', N'قياسي', NULL),
    ('st.standard_hint', 'st', N'A standard type the payroll engine relies on', N'نوع قياسي يعتمد عليه محرك الرواتب', NULL),
    ('st.standard_type', 'st', N'Standard type.', N'نوع قياسي.', NULL),
    ('st.standard_type_text', 'st', N'The payroll engine knows it by its code and type, so those cannot change; name, flags and accounting can.', N'يعرفه محرك الرواتب برمزه ونوعه، لذا لا يمكن تغييرهما؛ أما الاسم والخصائص والحسابات فيمكن تعديلها.', NULL),
    ('st.of', 'st', N'of', N'من', NULL),
    ('st.recurring', 'st', N'Recurring', N'متكرر', NULL),
    ('st.one_time', 'st', N'One-time', N'لمرة واحدة', NULL),
    ('st.fixed', 'st', N'Fixed', N'ثابت', NULL),
    ('st.variable', 'st', N'Variable', N'متغير', NULL),
    ('st.method', 'st', N'Method', N'الطريقة', NULL),
    ('st.method_amount', 'st', N'Amount', N'مبلغ', NULL),
    ('st.method_percentage', 'st', N'Percentage', N'نسبة مئوية', NULL),
    ('st.method_days', 'st', N'Days', N'أيام', NULL),
    ('st.method_hours', 'st', N'Hours', N'ساعات', NULL),
    ('st.method_formula', 'st', N'Formula', N'معادلة', NULL),
    ('st.method_system', 'st', N'Calculated by the payroll', N'يحتسبه مسير الرواتب', NULL),
    ('st.base', 'st', N'Base', N'الأساس', NULL),
    ('st.base_basic', 'st', N'Basic salary', N'الراتب الأساسي', NULL),
    ('st.base_fixed_gross', 'st', N'Fixed gross', N'الإجمالي الثابت', NULL),
    ('st.base_overtime', 'st', N'Overtime base', N'أساس العمل الإضافي', NULL),
    ('st.base_indemnity', 'st', N'Indemnity base', N'أساس مكافأة نهاية الخدمة', NULL),
    ('st.flag_pifss', 'st', N'PIFSS', N'التأمينات', NULL),
    ('st.flag_eos', 'st', N'End of service', N'نهاية الخدمة', NULL),
    ('st.flag_overtime', 'st', N'Overtime', N'العمل الإضافي', NULL),
    ('st.flag_leave', 'st', N'Leave salary', N'راتب الإجازة', NULL),
    ('st.flag_prorated', 'st', N'Prorated', N'يُحتسب بالتناسب', NULL),
    ('st.flag_taxable', 'st', N'Taxable', N'خاضع للضريبة', NULL),
    ('st.name_english', 'st', N'Name (English)', N'الاسم (إنجليزي)', NULL),
    ('st.name_arabic', 'st', N'Name (Arabic)', N'الاسم (عربي)', NULL),
    ('st.payslip_label', 'st', N'Payslip label', N'التسمية في كشف الراتب', NULL),
    ('st.payslip_label_hint', 'st', N'Leave empty to use the name', N'اتركه فارغاً لاستخدام الاسم', NULL),
    ('st.display_order', 'st', N'Display order', N'ترتيب العرض', NULL),
    ('st.earning', 'st', N'Earning', N'استحقاق', NULL),
    ('st.earning_hint', 'st', N'Adds to the pay', N'يُضاف إلى الراتب', NULL),
    ('st.deduction', 'st', N'Deduction', N'استقطاع', NULL),
    ('st.deduction_hint', 'st', N'Taken from the pay', N'يُخصم من الراتب', NULL),
    ('st.value_type', 'st', N'Value', N'القيمة', NULL),
    ('st.default_amount', 'st', N'Default amount (KWD)', N'المبلغ الافتراضي (د.ك)', NULL),
    ('st.default_percentage', 'st', N'Default percentage', N'النسبة الافتراضية', NULL),
    ('st.formula', 'st', N'Formula', N'المعادلة', NULL),
    ('st.min_amount', 'st', N'Minimum amount', N'الحد الأدنى', NULL),
    ('st.max_amount', 'st', N'Maximum amount', N'الحد الأقصى', NULL),
    ('st.behaviour', 'st', N'Behaviour', N'السلوك', NULL),
    ('st.recurring_hint', 'st', N'Paid or taken every month until ended', N'يُصرف أو يُخصم كل شهر حتى إيقافه', NULL),
    ('st.prorated_hint', 'st', N'Paid for the days worked in a partial month', N'يُصرف عن أيام العمل في الشهر الجزئي', NULL),
    ('st.show_on_payslip', 'st', N'Show on payslip', N'يظهر في كشف الراتب', NULL),
    ('st.show_on_payslip_hint', 'st', N'Listed as its own line on the payslip', N'يظهر كسطر مستقل في كشف الراتب', NULL),
    ('st.taxable_hint', 'st', N'Counted as taxable income', N'يُحتسب دخلاً خاضعاً للضريبة', NULL),
    ('st.included_in_bases', 'st', N'Included in the bases of (earnings only)', N'يدخل في أساس احتساب (للاستحقاقات فقط)', NULL),
    ('st.pifss_hint', 'st', N'Part of the PIFSS contribution salary', N'جزء من راتب الاشتراك في التأمينات', NULL),
    ('st.eos_hint', 'st', N'Part of the end-of-service indemnity salary', N'جزء من راتب مكافأة نهاية الخدمة', NULL),
    ('st.overtime_hint', 'st', N'Part of the overtime hourly rate base', N'جزء من أساس أجر ساعة العمل الإضافي', NULL),
    ('st.leave_hint', 'st', N'Part of the leave salary', N'جزء من راتب الإجازة', NULL),
    ('st.accounting', 'st', N'Accounting', N'المحاسبة', NULL),
    ('st.cost_center', 'st', N'Cost center', N'مركز التكلفة', NULL),
    ('st.employee_cost_center', 'st', N'The employee''s cost center', N'مركز تكلفة الموظف', NULL),
    ('st.description', 'st', N'Description', N'الوصف', NULL),
    ('msg.st_pc_created_earning', 'msg', N'Earning component created successfully.', N'تم إنشاء نوع الاستحقاق بنجاح.', N'Earning component created successfully.'),
    ('msg.st_pc_created_deduction', 'msg', N'Deduction component created successfully.', N'تم إنشاء نوع الاستقطاع بنجاح.', N'Deduction component created successfully.'),
    ('msg.st_pc_updated', 'msg', N'Component updated successfully.', N'تم تحديث نوع البند بنجاح.', N'Component updated successfully.'),
    ('msg.st_pc_deleted', 'msg', N'Component deleted successfully.', N'تم حذف نوع البند بنجاح.', N'Component deleted successfully.'),
    ('msg.st_pc_activated', 'msg', N'Component activated.', N'تم تفعيل نوع البند.', N'Component activated.'),
    ('msg.st_pc_deactivated', 'msg', N'Component deactivated.', N'تم إيقاف نوع البند.', N'Component deactivated.'),
    ('msg.st_pc_seed_none', 'msg', N'This company already has all the standard components.', N'لدى هذه الشركة جميع الأنواع القياسية.', N'This company already has all the standard components.'),
    ('msg.st_pc_seed_n', 'msg', N'{0} standard component(s) added.', N'أُضيف {0} من الأنواع القياسية.', N'{0} standard component(s) added.'),
    ('msg.st_pc_basic', 'msg', N'Basic Salary is required by the payroll engine and cannot be deactivated.', N'الراتب الأساسي مطلوب لمحرك الرواتب ولا يمكن إيقافه.', N'Basic Salary is required by the payroll engine and cannot be deactivated.'),
    ('msg.st_pc_basic_delete', 'msg', N'Basic Salary is required by the payroll engine and cannot be deleted.', N'الراتب الأساسي مطلوب لمحرك الرواتب ولا يمكن حذفه.', N'Basic Salary is required by the payroll engine and cannot be deleted.'),
    ('msg.st_pc_std_delete', 'msg', N'This is a standard component the payroll engine relies on. Deactivate it instead of deleting it.', N'هذا نوع قياسي يعتمد عليه محرك الرواتب. أوقفه بدلاً من حذفه.', N'This is a standard component the payroll engine relies on. Deactivate it instead of deleting it.'),
    ('msg.st_pc_in_use', 'msg', N'This component is used in a salary structure and cannot be deleted. Remove it from the structure or deactivate it instead.', N'هذا النوع مستخدم في هيكل رواتب ولا يمكن حذفه. أزله من الهيكل أو أوقفه.', N'This component is used in a salary structure and cannot be deleted. Remove it from the structure or deactivate it instead.'),
    ('msg.st_pc_dup', 'msg', N'That code is already in use. Enter a different code.', N'هذا الرمز مستخدم. أدخل رمزاً آخر.', N'That code is already in use. Enter a different code.'),
    ('msg.st_pc_earn_flags', 'msg', N'Social security, end-of-service, overtime and leave-salary flags apply to earnings only.', N'خصائص التأمينات ونهاية الخدمة والعمل الإضافي وراتب الإجازة تخص الاستحقاقات فقط.', N'Social security, end-of-service, overtime and leave-salary flags apply to earnings only.'),
    ('msg.st_pc_need_base', 'msg', N'Percentage, Days and Hours methods need a calculation base (Basic, Fixed gross, Overtime base or Indemnity base).', N'طرق النسبة والأيام والساعات تحتاج إلى أساس احتساب (الأساسي، الإجمالي الثابت، أساس العمل الإضافي أو أساس نهاية الخدمة).', N'Percentage, Days and Hours methods need a calculation base (Basic, Fixed gross, Overtime base or Indemnity base).'),
    ('msg.st_pc_need_pct', 'msg', N'Enter the default percentage.', N'أدخل النسبة الافتراضية.', N'Enter the default percentage.'),
    ('msg.st_pc_need_formula', 'msg', N'Enter the formula.', N'أدخل المعادلة.', N'Enter the formula.'),
    ('msg.st_pc_minmax', 'msg', N'Maximum amount cannot be less than the minimum amount.', N'لا يمكن أن يقل الحد الأقصى عن الحد الأدنى.', N'Maximum amount cannot be less than the minimum amount.'),
    ('msg.st_pc_cc', 'msg', N'The selected cost center does not belong to this company.', N'مركز التكلفة المختار لا يتبع هذه الشركة.', N'The selected cost center does not belong to this company.'),
    ('st.title_payroll_rules', 'st', N'Payroll Rules', N'قواعد الرواتب', N'Payroll Rules'),
    ('st.rules_subtitle', 'st', N'Kuwait statutory settings - effective-dated, never hard-coded', N'الإعدادات النظامية في الكويت - مؤرخة بتاريخ سريان ولا تُكتب في البرمجة', NULL),
    ('st.unverified_title', 'st', N'{0} statutory settings in force are not verified.', N'{0} من الإعدادات النظامية السارية غير مؤكدة.', NULL),
    ('st.unverified_text', 'st', N'Seeded values must be confirmed by finance / legal before go-live: open each one, check it and tick Verified.', N'يجب أن تؤكد المالية / الشؤون القانونية القيم المبدئية قبل التشغيل: افتح كل إعداد وتحقق منه وفعّل خيار مؤكد.', NULL),
    ('st.all_verified_title', 'st', N'Every statutory setting in force is verified.', N'جميع الإعدادات النظامية السارية مؤكدة.', NULL),
    ('st.all_verified_text', 'st', N'To change a rate, end-date the current row and add a new one from the new date, so history is kept.', N'لتغيير نسبة، حدّد تاريخ انتهاء للسطر الحالي وأضف سطراً جديداً من التاريخ الجديد، ليبقى السجل محفوظاً.', NULL),
    ('st.pifss_rates', 'st', N'Social security (PIFSS) rates', N'نسب التأمينات الاجتماعية', NULL),
    ('st.indemnity_rules', 'st', N'End-of-service indemnity rules', N'قواعد مكافأة نهاية الخدمة', NULL),
    ('st.overtime_rates', 'st', N'Overtime multipliers', N'معاملات العمل الإضافي', NULL),
    ('st.add_rate', 'st', N'Add rate', N'إضافة نسبة', NULL),
    ('st.add_rule_set', 'st', N'Add rule set', N'إضافة مجموعة قواعد', NULL),
    ('st.add_pifss_rate', 'st', N'Add social security rate', N'إضافة نسبة تأمينات', NULL),
    ('st.edit_pifss_rate', 'st', N'Edit social security rate', N'تعديل نسبة التأمينات', NULL),
    ('st.add_indemnity_rules', 'st', N'Add indemnity rule set', N'إضافة قواعد نهاية الخدمة', NULL),
    ('st.edit_indemnity_rules', 'st', N'Edit indemnity rule set', N'تعديل قواعد نهاية الخدمة', NULL),
    ('st.add_overtime_rate', 'st', N'Add overtime multiplier', N'إضافة معامل عمل إضافي', NULL),
    ('st.edit_overtime_rate', 'st', N'Edit overtime multiplier', N'تعديل معامل العمل الإضافي', NULL),
    ('st.delete_rate_text', 'st', N'Delete this row? To change a rate that was already used, end-date it and add a new one instead.', N'حذف هذا السطر؟ لتغيير نسبة سبق استخدامها، حدّد لها تاريخ انتهاء وأضف سطراً جديداً بدلاً من ذلك.', NULL),
    ('st.in_force', 'st', N'In force', N'سارٍ', NULL),
    ('st.in_force_today', 'st', N'In force today', N'سارٍ اليوم', NULL),
    ('st.all_dates', 'st', N'All dates', N'كل التواريخ', NULL),
    ('st.1_rate', 'st', N'1 rate', N'نسبة واحدة', NULL),
    ('st.0_rates', 'st', N'{0} rates', N'{0} نسب', NULL),
    ('st.1_rule_set', 'st', N'1 rule set', N'مجموعة قواعد واحدة', NULL),
    ('st.0_rule_sets', 'st', N'{0} rule sets', N'{0} مجموعات قواعد', NULL),
    ('st.no_rates_match', 'st', N'Nothing matches your search', N'لا توجد نتائج مطابقة', NULL),
    ('st.no_rates_yet', 'st', N'No rates yet', N'لا توجد نسب بعد', NULL),
    ('st.no_rule_sets_yet', 'st', N'No indemnity rules yet', N'لا توجد قواعد نهاية خدمة بعد', NULL),
    ('st.contribution', 'st', N'Contribution', N'الاشتراك', NULL),
    ('st.applies_to', 'st', N'Applies to', N'ينطبق على', NULL),
    ('st.applies_kuwaiti', 'st', N'Kuwaitis', N'الكويتيون', NULL),
    ('st.applies_gcc', 'st', N'GCC nationals', N'مواطنو دول الخليج', NULL),
    ('st.applies_expat', 'st', N'Expatriates', N'الوافدون', NULL),
    ('st.applies_all', 'st', N'Everyone', N'الجميع', NULL),
    ('st.basis', 'st', N'Basis', N'الأساس', NULL),
    ('st.basis_capped', 'st', N'Salary up to the ceiling', N'الراتب حتى الحد الأعلى', NULL),
    ('st.basis_band', 'st', N'Salary band (floor to ceiling)', N'شريحة الراتب (من الحد الأدنى إلى الأعلى)', NULL),
    ('st.basis_hint', 'st', N'Band: only the part of the salary between floor and ceiling (e.g. the supplementary scheme).', N'الشريحة: فقط الجزء من الراتب بين الحدين الأدنى والأعلى (مثل النظام التكميلي).', NULL),
    ('st.employee_rate', 'st', N'Employee rate', N'نسبة الموظف', NULL),
    ('st.employer_rate', 'st', N'Employer rate', N'نسبة صاحب العمل', NULL),
    ('st.government_rate', 'st', N'Government rate', N'نسبة الحكومة', NULL),
    ('st.salary_range', 'st', N'Salary range (KWD)', N'نطاق الراتب (د.ك)', NULL),
    ('st.salary_floor', 'st', N'Salary floor (KWD)', N'الحد الأدنى للراتب (د.ك)', NULL),
    ('st.salary_ceiling', 'st', N'Salary ceiling (KWD)', N'الحد الأعلى للراتب (د.ك)', NULL),
    ('st.salary_ceiling_hint', 'st', N'Empty = no cap', N'فارغ = بلا حد أعلى', NULL),
    ('st.no_cap', 'st', N'no cap', N'بلا حد', NULL),
    ('st.rates_and_salary', 'st', N'Rates and salary', N'النسب والراتب', NULL),
    ('st.effective', 'st', N'Effective', N'السريان', NULL),
    ('st.effective_from', 'st', N'Effective from', N'ساري من', NULL),
    ('st.effective_to', 'st', N'Effective to', N'ساري حتى', NULL),
    ('st.effective_to_hint', 'st', N'Empty = until changed', N'فارغ = حتى يتم التغيير', NULL),
    ('st.open_ended', 'st', N'open-ended', N'مفتوح', NULL),
    ('st.verified', 'st', N'Verified', N'مؤكد', NULL),
    ('st.not_verified', 'st', N'Not verified', N'غير مؤكد', NULL),
    ('st.verified_hint', 'st', N'Confirmed by finance / legal', N'أكدته المالية / الشؤون القانونية', NULL),
    ('st.notes', 'st', N'Notes', N'ملاحظات', NULL),
    ('st.notes_hint', 'st', N'Source of the value (law, circular, date checked)', N'مصدر القيمة (القانون، التعميم، تاريخ التحقق)', NULL),
    ('st.rule_set', 'st', N'Rule set', N'مجموعة القواعد', NULL),
    ('st.daily_divisor', 'st', N'Daily wage divisor', N'قاسم الأجر اليومي', NULL),
    ('st.daily_divisor_hint', 'st', N'Days a month''s wage is divided by (26 in Kuwait)', N'عدد الأيام التي يُقسم عليها الأجر الشهري (26 في الكويت)', NULL),
    ('st.cap_months', 'st', N'Cap (months)', N'الحد الأقصى (أشهر)', NULL),
    ('st.min_service_months', 'st', N'Minimum service (months)', N'الحد الأدنى للخدمة (أشهر)', NULL),
    ('st.slabs_factors', 'st', N'Slabs / factors', N'الشرائح / النسب', NULL),
    ('st.n_slabs_n_factors', 'st', N'{0} slabs · {1} factors', N'{0} شرائح · {1} نسب', NULL),
    ('st.service_slabs', 'st', N'Service slabs', N'شرائح سنوات الخدمة', NULL),
    ('st.service_slabs_hint', 'st', N'What each year of service earns, by band - e.g. 0 to 5 years: 15 days per year; 5 years and above: 1 month per year.', N'ما تستحقه كل سنة خدمة حسب الشريحة - مثال: من 0 إلى 5 سنوات: 15 يوماً عن كل سنة؛ 5 سنوات فأكثر: شهر عن كل سنة.', NULL),
    ('st.from_years', 'st', N'From (years)', N'من (سنوات)', NULL),
    ('st.to_years', 'st', N'To (years)', N'إلى (سنوات)', NULL),
    ('st.and_above', 'st', N'and above', N'فأكثر', NULL),
    ('st.entitlement', 'st', N'Entitlement', N'الاستحقاق', NULL),
    ('st.unit', 'st', N'Unit', N'الوحدة', NULL),
    ('st.days_per_year', 'st', N'Days per year', N'أيام عن كل سنة', NULL),
    ('st.months_per_year', 'st', N'Months per year', N'أشهر عن كل سنة', NULL),
    ('st.add_slab', 'st', N'Add slab', N'إضافة شريحة', NULL),
    ('st.entitlement_factors', 'st', N'Entitlement by separation', N'الاستحقاق حسب نوع إنهاء الخدمة', NULL),
    ('st.entitlement_factors_hint', 'st', N'The % of the indemnity actually paid - e.g. resignation with 3 to 5 years of service: 50 %.', N'النسبة المدفوعة فعلاً من المكافأة - مثال: الاستقالة بخدمة من 3 إلى 5 سنوات: 50 %.', NULL),
    ('st.separation', 'st', N'Separation', N'نوع إنهاء الخدمة', NULL),
    ('st.separation_other', 'st', N'Other', N'أخرى', NULL),
    ('st.paid_percent', 'st', N'Paid %', N'النسبة المدفوعة', NULL),
    ('st.add_factor', 'st', N'Add factor', N'إضافة نسبة', NULL),
    ('st.overtime', 'st', N'Overtime', N'العمل الإضافي', NULL),
    ('st.when', 'st', N'When worked', N'وقت العمل', NULL),
    ('st.ot_normal_day', 'st', N'Normal working day', N'يوم عمل عادي', NULL),
    ('st.ot_rest_day', 'st', N'Weekly rest day', N'يوم الراحة الأسبوعية', NULL),
    ('st.ot_public_holiday', 'st', N'Public holiday', N'عطلة رسمية', NULL),
    ('st.ot_night', 'st', N'Night', N'ليلي', NULL),
    ('st.ot_other', 'st', N'Other', N'أخرى', NULL),
    ('st.multiplier', 'st', N'Multiplier', N'المعامل', NULL),
    ('st.hourly_rate', 'st', N'Hourly rate', N'أجر الساعة', NULL),
    ('st.hourly_rate_formula', 'st', N'Salary ÷ {0} days ÷ {1} h', N'الراتب ÷ {0} يوماً ÷ {1} ساعات', NULL),
    ('st.hourly_divisor_days', 'st', N'Days in the hourly rate', N'الأيام في حساب أجر الساعة', NULL),
    ('st.hours_per_day', 'st', N'Hours per day', N'ساعات اليوم', NULL),
    ('st.hourly_rate_explained', 'st', N'Hourly rate = overtime base salary ÷ days ÷ hours per day; overtime pay = hours × hourly rate × multiplier.', N'أجر الساعة = راتب أساس العمل الإضافي ÷ الأيام ÷ ساعات اليوم؛ أجر العمل الإضافي = الساعات × أجر الساعة × المعامل.', NULL),
    ('st.limits', 'st', N'Limits', N'الحدود', NULL),
    ('st.max_hours_day', 'st', N'Maximum hours per day', N'الحد الأقصى للساعات يومياً', NULL),
    ('st.max_hours_year', 'st', N'Maximum hours per year', N'الحد الأقصى للساعات سنوياً', NULL),
    ('st.n_hours_day', 'st', N'{0} h/day', N'{0} س/يوم', NULL),
    ('st.n_hours_year', 'st', N'{0} h/year', N'{0} س/سنة', NULL),
    ('st.statutory_default', 'st', N'Statutory default', N'الافتراضي النظامي', NULL),
    ('st.statutory_default_all', 'st', N'Statutory default - every company', N'الافتراضي النظامي - كل الشركات', NULL),
    ('st.overtime_company_hint', 'st', N'A company''s own (more generous) multiplier takes precedence over the default for that company.', N'المعامل الخاص بالشركة (الأفضل للموظف) يتقدم على الافتراضي لتلك الشركة.', NULL),
    ('msg.st_svc_slab_one', 'msg', N'Add at least one service slab.', N'أضف شريحة خدمة واحدة على الأقل.', N'Add at least one service slab.'),
    ('msg.st_pifss_overlap', 'msg', N'Another active rate for this contribution and nationality group overlaps these dates. End-date the existing rate first.', N'توجد نسبة سارية أخرى لهذا الاشتراك وهذه الفئة تتداخل مع هذه التواريخ. حدّد تاريخ انتهاء للنسبة الحالية أولاً.', N'Another active rate for this contribution and nationality group overlaps these dates. End-date the existing rate first.'),
    ('msg.st_reactivate_overlap', 'msg', N'Another active rate overlaps these dates, so this one cannot be re-activated.', N'توجد نسبة سارية أخرى تتداخل مع هذه التواريخ، لذا لا يمكن إعادة تفعيل هذه.', N'Another active rate overlaps these dates, so this one cannot be re-activated.'),
    ('msg.st_pifss_check', 'msg', N'Check the rates (0 - 100 %), the salary floor / ceiling and the effective dates.', N'تحقق من النسب (0 - 100 %) والحدين الأدنى والأعلى للراتب وتواريخ السريان.', N'Check the rates (0 - 100 %), the salary floor / ceiling and the effective dates.'),
    ('msg.st_pifss_required', 'msg', N'Code, name, employee rate, employer rate and effective-from date are required.', N'الرمز والاسم ونسبة الموظف ونسبة صاحب العمل وتاريخ بدء السريان مطلوبة.', N'Code, name, employee rate, employer rate and effective-from date are required.'),
    ('msg.st_pifss_created', 'msg', N'Social security rate created successfully.', N'تم إنشاء نسبة التأمينات بنجاح.', N'Social security rate created successfully.'),
    ('msg.st_pifss_deleted', 'msg', N'Social security rate deleted successfully.', N'تم حذف نسبة التأمينات بنجاح.', N'Social security rate deleted successfully.'),
    ('msg.st_pifss_updated', 'msg', N'Social security rate updated successfully.', N'تم تحديث نسبة التأمينات بنجاح.', N'Social security rate updated successfully.'),
    ('msg.st_not_found', 'msg', N'That record no longer exists. Refresh and try again.', N'هذا السجل لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That record no longer exists. Refresh and try again.'),
    ('msg.st_ind_overlap', 'msg', N'Another active indemnity rule set is in force for overlapping dates. End-date it first.', N'توجد قواعد نهاية خدمة سارية أخرى لتواريخ متداخلة. حدّد لها تاريخ انتهاء أولاً.', N'Another active indemnity rule set is in force for overlapping dates. End-date it first.'),
    ('msg.st_ind_reactivate', 'msg', N'Another active rule set overlaps these dates, so this one cannot be re-activated.', N'توجد قواعد سارية أخرى تتداخل مع هذه التواريخ، لذا لا يمكن إعادة تفعيل هذه.', N'Another active rule set overlaps these dates, so this one cannot be re-activated.'),
    ('msg.st_ind_check', 'msg', N'Check the daily-wage divisor (1 - 31), the cap and the effective dates.', N'تحقق من قاسم الأجر اليومي (1 - 31) والحد الأقصى وتواريخ السريان.', N'Check the daily-wage divisor (1 - 31), the cap and the effective dates.'),
    ('msg.st_ind_required', 'msg', N'Code, name and effective-from date are required.', N'الرمز والاسم وتاريخ بدء السريان مطلوبة.', N'Code, name and effective-from date are required.'),
    ('msg.st_ind_factors', 'msg', N'Entitlement factors need a valid separation type, non-overlapping year ranges and a percentage between 0 and 100.', N'نسب الاستحقاق تتطلب نوع إنهاء خدمة صحيحاً ونطاقات سنوات غير متداخلة ونسبة بين 0 و100.', N'Entitlement factors need a valid separation type, non-overlapping year ranges and a percentage between 0 and 100.'),
    ('msg.st_ind_created', 'msg', N'Indemnity rule set created successfully.', N'تم إنشاء قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set created successfully.'),
    ('msg.st_ind_deleted', 'msg', N'Indemnity rule set deleted successfully.', N'تم حذف قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set deleted successfully.'),
    ('msg.st_ind_updated', 'msg', N'Indemnity rule set updated successfully.', N'تم تحديث قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set updated successfully.'),
    ('msg.st_ind_on', 'msg', N'Rule set activated.', N'تم تفعيل مجموعة القواعد.', N'Rule set activated.'),
    ('msg.st_ind_off', 'msg', N'Rule set deactivated.', N'تم إيقاف مجموعة القواعد.', N'Rule set deactivated.'),
    ('msg.st_ind_slabs', 'msg', N'Service slabs need valid, non-overlapping year ranges and an entitlement in Days or Months.', N'شرائح الخدمة تتطلب نطاقات سنوات صحيحة وغير متداخلة واستحقاقاً بالأيام أو الأشهر.', N'Service slabs need valid, non-overlapping year ranges and an entitlement in Days or Months.'),
    ('msg.st_ind_factors_read', 'msg', N'The entitlement factors could not be read.', N'تعذّرت قراءة نسب الاستحقاق.', N'The entitlement factors could not be read.'),
    ('msg.st_ind_slabs_read', 'msg', N'The service slabs could not be read.', N'تعذّرت قراءة شرائح الخدمة.', N'The service slabs could not be read.'),
    ('msg.st_ot_overlap', 'msg', N'An active rate for this overtime type already covers overlapping dates. End-date it first.', N'توجد نسبة سارية لهذا النوع من العمل الإضافي لتواريخ متداخلة. حدّد لها تاريخ انتهاء أولاً.', N'An active rate for this overtime type already covers overlapping dates. End-date it first.'),
    ('msg.st_ot_check', 'msg', N'Check the multiplier, hours, divisor and effective dates.', N'تحقق من المعامل والساعات والقاسم وتواريخ السريان.', N'Check the multiplier, hours, divisor and effective dates.'),
    ('msg.st_ot_on', 'msg', N'Overtime rate activated.', N'تم تفعيل معامل العمل الإضافي.', N'Overtime rate activated.'),
    ('msg.st_ot_created', 'msg', N'Overtime rate created successfully.', N'تم إنشاء معامل العمل الإضافي بنجاح.', N'Overtime rate created successfully.'),
    ('msg.st_ot_off', 'msg', N'Overtime rate deactivated.', N'تم إيقاف معامل العمل الإضافي.', N'Overtime rate deactivated.'),
    ('msg.st_ot_deleted', 'msg', N'Overtime rate deleted successfully.', N'تم حذف معامل العمل الإضافي بنجاح.', N'Overtime rate deleted successfully.'),
    ('msg.st_ot_updated', 'msg', N'Overtime rate updated successfully.', N'تم تحديث معامل العمل الإضافي بنجاح.', N'Overtime rate updated successfully.'),
    ('msg.st_ot_required', 'msg', N'Overtime type, name, multiplier and effective-from date are required.', N'نوع العمل الإضافي والاسم والمعامل وتاريخ بدء السريان مطلوبة.', N'Overtime type, name, multiplier and effective-from date are required.'),
    ('st.title_banks', 'st', N'Banks & Accounts', N'البنوك والحسابات', N'Banks & Accounts'),
    ('st.banks_subtitle', 'st', N'The bank master and the company''s own salary accounts', N'البنوك وحسابات الرواتب الخاصة بالشركة', NULL),
    ('st.wps_banner_title', 'st', N'WPS codes come from the banks.', N'رموز نظام حماية الأجور تأتي من البنوك.', NULL),
    ('st.wps_banner_text', 'st', N'Leave a bank''s WPS code empty until the bank confirms it in its WPS file specification; payroll warns about banks without one.', N'اترك رمز البنك لنظام حماية الأجور فارغاً حتى يؤكده البنك في مواصفات ملفه؛ وينبّه مسير الرواتب إلى البنوك التي تفتقده.', NULL),
    ('st.company_accounts', 'st', N'Company salary accounts', N'حسابات رواتب الشركة', NULL),
    ('st.banks', 'st', N'Banks', N'البنوك', NULL),
    ('st.bank', 'st', N'Bank', N'البنك', NULL),
    ('st.add_bank', 'st', N'Add bank', N'إضافة بنك', NULL),
    ('st.edit_bank', 'st', N'Edit bank', N'تعديل البنك', NULL),
    ('st.add_company_account', 'st', N'Add account', N'إضافة حساب', NULL),
    ('st.edit_company_account', 'st', N'Edit company account', N'تعديل حساب الشركة', NULL),
    ('st.delete_bank_text', 'st', N'Delete this bank? It cannot be deleted while a company account uses it - deactivate it instead.', N'حذف هذا البنك؟ لا يمكن حذفه ما دام حساب شركة يستخدمه - أوقفه بدلاً من ذلك.', NULL),
    ('st.delete_account_text', 'st', N'Delete this company account?', N'حذف حساب الشركة هذا؟', NULL),
    ('st.search_banks', 'st', N'Search code, name or SWIFT', N'ابحث بالرمز أو الاسم أو رمز السويفت', NULL),
    ('st.search_accounts', 'st', N'Search account, IBAN or bank', N'ابحث بالحساب أو الآيبان أو البنك', NULL),
    ('st.1_bank', 'st', N'1 bank', N'بنك واحد', NULL),
    ('st.0_banks', 'st', N'{0} banks', N'{0} بنوك', NULL),
    ('st.1_account', 'st', N'1 account', N'حساب واحد', NULL),
    ('st.0_accounts', 'st', N'{0} accounts', N'{0} حسابات', NULL),
    ('st.no_banks_yet', 'st', N'No banks yet', N'لا توجد بنوك بعد', NULL),
    ('st.no_accounts_yet', 'st', N'No company accounts yet', N'لا توجد حسابات للشركة بعد', NULL),
    ('st.no_accounts_text', 'st', N'Add the account salaries are paid from - the WPS salary file is made for it.', N'أضف الحساب الذي تُصرف منه الرواتب - يُعد ملف حماية الأجور له.', NULL),
    ('st.swift', 'st', N'SWIFT / BIC', N'سويفت / BIC', NULL),
    ('st.iban_code', 'st', N'IBAN bank code', N'رمز البنك في الآيبان', NULL),
    ('st.iban_code_hint', 'st', N'The 4 letters after KWkk in an IBAN', N'الأحرف الأربعة بعد KWkk في الآيبان', NULL),
    ('st.wps_code', 'st', N'WPS code', N'رمز حماية الأجور', NULL),
    ('st.wps_code_hint', 'st', N'From the bank''s WPS file specification', N'من مواصفات ملف حماية الأجور لدى البنك', NULL),
    ('st.wps_missing', 'st', N'Not set', N'غير محدد', NULL),
    ('st.accounts', 'st', N'Accounts', N'الحسابات', NULL),
    ('st.short_name', 'st', N'Short name', N'الاسم المختصر', NULL),
    ('st.country', 'st', N'Country', N'الدولة', NULL),
    ('st.bank_codes', 'st', N'Codes', N'الرموز', NULL),
    ('st.account', 'st', N'Account', N'الحساب', NULL),
    ('st.account_title', 'st', N'Account title', N'اسم الحساب', NULL),
    ('st.account_number', 'st', N'Account number', N'رقم الحساب', NULL),
    ('st.select_bank', 'st', N'Select the bank', N'اختر البنك', NULL),
    ('st.iban', 'st', N'IBAN', N'الآيبان', NULL),
    ('st.iban_hint', 'st', N'With or without spaces - checked before saving', N'مع أو بدون مسافات - يتم التحقق منه قبل الحفظ', NULL),
    ('st.currency', 'st', N'Currency', N'العملة', NULL),
    ('st.branch', 'st', N'Branch', N'الفرع', NULL),
    ('st.wps', 'st', N'Wage Protection System (WPS)', N'نظام حماية الأجور', NULL),
    ('st.wps_employer_code', 'st', N'WPS employer code', N'رمز صاحب العمل في حماية الأجور', NULL),
    ('st.pam_file_no', 'st', N'PAM file no.', N'رقم ملف الهيئة العامة للقوى العاملة', NULL),
    ('st.default', 'st', N'Default', N'افتراضي', NULL),
    ('st.default_account', 'st', N'Default account', N'الحساب الافتراضي', NULL),
    ('st.default_account_hint', 'st', N'Salaries are paid from it unless another is chosen', N'تُصرف منه الرواتب ما لم يُختر غيره', NULL),
    ('msg.st_bk_swift', 'msg', N'A SWIFT / BIC code is 8 or 11 letters and digits.', N'رمز السويفت يتكون من 8 أو 11 حرفاً ورقماً.', N'A SWIFT / BIC code is 8 or 11 letters and digits.'),
    ('msg.st_bk_in_use', 'msg', N'A company bank account uses this bank, so it cannot be deleted. Deactivate it instead.', N'حساب شركة يستخدم هذا البنك لذا لا يمكن حذفه. أوقفه بدلاً من ذلك.', N'A company bank account uses this bank, so it cannot be deleted. Deactivate it instead.'),
    ('msg.st_ac_on', 'msg', N'Bank account activated.', N'تم تفعيل الحساب البنكي.', N'Bank account activated.'),
    ('msg.st_ac_off', 'msg', N'Bank account deactivated.', N'تم إيقاف الحساب البنكي.', N'Bank account deactivated.'),
    ('msg.st_bk_on', 'msg', N'Bank activated.', N'تم تفعيل البنك.', N'Bank activated.'),
    ('msg.st_bk_required', 'msg', N'Bank code and name are required.', N'رمز البنك واسمه مطلوبان.', N'Bank code and name are required.'),
    ('msg.st_bk_created', 'msg', N'Bank created successfully.', N'تم إنشاء البنك بنجاح.', N'Bank created successfully.'),
    ('msg.st_bk_off', 'msg', N'Bank deactivated.', N'تم إيقاف البنك.', N'Bank deactivated.'),
    ('msg.st_bk_deleted', 'msg', N'Bank deleted successfully.', N'تم حذف البنك بنجاح.', N'Bank deleted successfully.'),
    ('msg.st_bk_updated', 'msg', N'Bank updated successfully.', N'تم تحديث البنك بنجاح.', N'Bank updated successfully.'),
    ('msg.st_ac_created', 'msg', N'Company bank account created successfully.', N'تم إنشاء حساب الشركة بنجاح.', N'Company bank account created successfully.'),
    ('msg.st_ac_deleted', 'msg', N'Company bank account deleted successfully.', N'تم حذف حساب الشركة بنجاح.', N'Company bank account deleted successfully.'),
    ('msg.st_ac_updated', 'msg', N'Company bank account updated successfully.', N'تم تحديث حساب الشركة بنجاح.', N'Company bank account updated successfully.'),
    ('msg.st_ac_required', 'msg', N'Company, bank, account code and account title are required.', N'الشركة والبنك ورمز الحساب واسمه مطلوبة.', N'Company, bank, account code and account title are required.'),
    ('msg.st_ac_number', 'msg', N'Enter the IBAN or the account number.', N'أدخل الآيبان أو رقم الحساب.', N'Enter the IBAN or the account number.'),
    ('msg.st_ac_bank', 'msg', N'Select a valid bank.', N'اختر بنكاً صحيحاً.', N'Select a valid bank.'),
    ('msg.st_ac_iban', 'msg', N'That IBAN is not valid. Kuwait IBANs are 30 characters starting with KW - check for a mistyped digit.', N'هذا الآيبان غير صحيح. الآيبان الكويتي 30 خانة يبدأ بـ KW - تحقق من الأرقام.', N'That IBAN is not valid. Kuwait IBANs are 30 characters starting with KW - check for a mistyped digit.'),
    ('msg.st_ac_iban_dup', 'msg', N'This IBAN is already registered as a company account.', N'هذا الآيبان مسجل مسبقاً كحساب للشركة.', N'This IBAN is already registered as a company account.'),
    ('st.0_routes', 'st', N'{0} routes', N'{0} مسارات', NULL),
    ('st.0_rules', 'st', N'{0} rules', N'{0} قواعد', NULL),
    ('st.1_calendar', 'st', N'1 calendar', N'تقويم واحد', NULL),
    ('st.1_format', 'st', N'1 format', N'صيغة واحدة', NULL),
    ('st.1_mapping', 'st', N'1 mapping', N'ربط واحد', NULL),
    ('st.1_route', 'st', N'1 route', N'مسار واحد', NULL),
    ('st.1_rule', 'st', N'1 rule', N'قاعدة واحدة', NULL),
    ('st.account_name', 'st', N'Account name', N'اسم الحساب', NULL),
    ('st.above_kwd_0', 'st', N'Above KWD {0}', N'أعلى من {0} د.ك', NULL),
    ('st.add_approval_route', 'st', N'Add approval route', N'إضافة مسار اعتماد', NULL),
    ('st.add_company_route', 'st', N'Add company route', N'إضافة مسار للشركة', NULL),
    ('st.add_deduction_rule', 'st', N'Add deduction rule', N'إضافة قاعدة استقطاع', NULL),
    ('st.add_field', 'st', N'Add field', N'إضافة حقل', NULL),
    ('st.add_priority', 'st', N'Add deduction group', N'إضافة مجموعة استقطاع', NULL),
    ('st.align_right', 'st', N'Right-align', N'محاذاة لليمين', NULL),
    ('st.all_calendars', 'st', N'All payroll calendars', N'جميع تقاويم الرواتب', NULL),
    ('st.all_processes', 'st', N'All processes', N'جميع العمليات', NULL),
    ('st.allowed', 'st', N'Allowed', N'مسموح', NULL),
    ('st.any_cost_center', 'st', N'Any cost center', N'أي مركز تكلفة', NULL),
    ('st.approval_routes', 'st', N'Approval routes', N'مسارات الاعتماد', NULL),
    ('st.approval_subtitle', 'st', N'Who approves each payroll process - two levels, delegates when away, and the amount above which level 2 is needed.', N'من يعتمد كل عملية رواتب - مستويان، ومفوضون عند الغياب، والمبلغ الذي يلزم فوقه المستوى الثاني.', NULL),
    ('st.bank_formats', 'st', N'Bank file formats', N'صيغ ملفات البنوك', NULL),
    ('st.basis_calendar', 'st', N'Calendar days', N'أيام التقويم', NULL),
    ('st.basis_calendar_text', 'st', N'The actual days in the period (28 to 31) - the daily rate changes from month to month.', N'الأيام الفعلية في الفترة (28 إلى 31) - يتغير الأجر اليومي من شهر لآخر.', NULL),
    ('st.basis_fixed', 'st', N'Fixed days', N'أيام ثابتة', NULL),
    ('st.basis_fixed_text', 'st', N'A fixed number of days every month (26 under the Kuwait Labour Law, or 30) - the same daily rate all year.', N'عدد ثابت من الأيام كل شهر (26 وفق قانون العمل الكويتي، أو 30) - أجر يومي ثابت طوال السنة.', NULL),
    ('st.basis_on_calendar_hint', 'st', N'The day basis is saved on the payroll calendar itself, so the calendar screen shows the same value.', N'يُحفظ أساس الأيام على تقويم الرواتب نفسه، لذا تعرض شاشة التقويم القيمة نفسها.', NULL),
    ('st.basis_working', 'st', N'Working days', N'أيام العمل', NULL),
    ('st.basis_working_text', 'st', N'The working days in the period, by the employee''s work schedule - weekly rest days are not paid days.', N'أيام العمل في الفترة حسب جدول عمل الموظف - أيام الراحة الأسبوعية ليست أيام مدفوعة.', NULL),
    ('st.beh_always', 'st', N'Always taken (never deferred)', N'تُستقطع دائماً (لا تؤجل)', NULL),
    ('st.beh_defer', 'st', N'Deferred to the next period', N'تؤجل إلى الفترة التالية', NULL),
    ('st.beh_taken', 'st', N'Taken while within the limit', N'تُستقطع ما دامت ضمن الحد', NULL),
    ('st.calendar_scope_hint', 'st', N'Leave on "All payroll calendars" for one rule for the whole company.', N'اتركها على "جميع تقاويم الرواتب" لقاعدة واحدة للشركة كلها.', NULL),
    ('st.company_route_hint', 'st', N'A company route replaces the default route for that company only.', N'مسار الشركة يحل محل المسار الافتراضي لتلك الشركة فقط.', NULL),
    ('st.cost_center_hint', 'st', N'Leave on "Any cost center" unless one cost center posts to different accounts - the most specific row wins.', N'اتركها على "أي مركز تكلفة" ما لم يُرحّل مركز تكلفة إلى حسابات مختلفة - الصف الأكثر تحديداً هو المعتمد.', NULL),
    ('st.days_per_month', 'st', N'Days per month', N'الأيام في الشهر', NULL),
    ('st.deduction_rules', 'st', N'Deduction rules', N'قواعد الاستقطاع', NULL),
    ('st.deduction_subtitle', 'st', N'The maximum total deductions in a period and the order deductions are recovered in - a default for every company, overridden per company or calendar.', N'الحد الأقصى لإجمالي الاستقطاعات في الفترة وترتيب استردادها - قاعدة افتراضية لكل الشركات يمكن تخصيصها لكل شركة أو تقويم.', NULL),
    ('st.default_all_companies', 'st', N'Default - every company', N'افتراضي - جميع الشركات', NULL),
    ('st.default_always_active', 'st', N'The default is always active.', N'القاعدة الافتراضية مفعّلة دائماً.', NULL),
    ('st.default_format', 'st', N'Default format', N'الصيغة الافتراضية', NULL),
    ('st.default_format_hint', 'st', N'Used for every bank that has no format of its own. Making this the default replaces the current default.', N'تُستخدم لكل بنك ليست له صيغة خاصة. جعلها افتراضية يستبدل الصيغة الافتراضية الحالية.', NULL),
    ('st.default_format_locked', 'st', N'To change the default, make another format the default.', N'لتغيير الصيغة الافتراضية، اجعل صيغة أخرى هي الافتراضية.', NULL),
    ('st.default_locked', 'st', N'Default - only users not tied to one company can change it', N'افتراضي - يمكن تعديله فقط للمستخدمين غير المرتبطين بشركة واحدة', NULL),
    ('st.default_rule_hint', 'st', N'Applies to every company and calendar without its own rule.', N'تنطبق على كل شركة وتقويم ليست له قاعدة خاصة.', NULL),
    ('st.delegate_0', 'st', N'Delegate: {0}', N'المفوض: {0}', NULL),
    ('st.delete_approval_route_text', 'st', N'The company goes back to the default route for this process.', N'ستعود الشركة إلى المسار الافتراضي لهذه العملية.', NULL),
    ('st.delete_deduction_rule_text', 'st', N'The company goes back to the default deduction rule.', N'ستعود الشركة إلى قاعدة الاستقطاع الافتراضية.', NULL),
    ('st.delete_format_text', 'st', N'The bank''s salary files will use the default format.', N'ستستخدم ملفات رواتب هذا البنك الصيغة الافتراضية.', NULL),
    ('st.delete_mapping_text', 'st', N'The pay item type posts to its own GL code again.', N'سيُرحّل نوع البند إلى رمز دفتر الأستاذ الخاص به مجدداً.', NULL),
    ('st.delimiter', 'st', N'Delimiter', N'الفاصل', NULL),
    ('st.delimiter_hint', 'st', N'\t = tab', N'\t = مسافة جدولة', NULL),
    ('st.dg_absence', 'st', N'Absence / unpaid leave', N'الغياب / الإجازة بدون راتب', NULL),
    ('st.dg_advance', 'st', N'Salary advance', N'سلفة الراتب', NULL),
    ('st.dg_loan', 'st', N'Loan instalment', N'قسط القرض', NULL),
    ('st.dg_one_time', 'st', N'Other one-time deductions', N'استقطاعات أخرى لمرة واحدة', NULL),
    ('st.dg_standing', 'st', N'Insurance and standing deductions', N'التأمين والاستقطاعات الثابتة', NULL),
    ('st.dg_statutory', 'st', N'Social security (PIFSS)', N'التأمينات الاجتماعية', NULL),
    ('st.edit_approval_route', 'st', N'Edit approval route', N'تعديل مسار الاعتماد', NULL),
    ('st.edit_deduction_rule', 'st', N'Edit deduction rule', N'تعديل قاعدة الاستقطاع', NULL),
    ('st.edit_format', 'st', N'Edit format', N'تعديل الصيغة', NULL),
    ('st.edit_mapping', 'st', N'Edit mapping', N'تعديل الربط', NULL),
    ('st.edit_proration', 'st', N'Proration rule', N'قاعدة التناسب', NULL),
    ('st.engine_note_title', 'st', N'Saved and audited.', N'محفوظة ومدققة.', NULL),
    ('st.engine_note_text', 'st', N'These settings are kept as configuration; the payroll calculation starts applying them in its next update - until then it keeps its current behaviour.', N'تُحفظ هذه الإعدادات كتهيئة؛ ويبدأ احتساب الرواتب بتطبيقها في تحديثه القادم - وحتى ذلك الحين يحتفظ بسلوكه الحالي.', NULL),
    ('st.ev_joiners', 'st', N'Joiners', N'المنضمون الجدد', NULL),
    ('st.ev_joiners_hint', 'st', N'Pay from the joining date, not the whole period.', N'الدفع من تاريخ الالتحاق وليس عن كامل الفترة.', NULL),
    ('st.ev_leavers', 'st', N'Leavers', N'المغادرون', NULL),
    ('st.ev_leavers_hint', 'st', N'Pay up to the last working day.', N'الدفع حتى آخر يوم عمل.', NULL),
    ('st.ev_revisions', 'st', N'Mid-period salary revisions', N'تعديلات الراتب خلال الفترة', NULL),
    ('st.ev_revisions_hint', 'st', N'The old and new salary are each paid for their days.', N'يُدفع الراتب القديم والجديد كلٌّ عن أيامه.', NULL),
    ('st.ev_unpaid_leave', 'st', N'Unpaid leave', N'الإجازة بدون راتب', NULL),
    ('st.ev_unpaid_leave_hint', 'st', N'Days of unpaid leave are deducted at the daily rate.', N'تُخصم أيام الإجازة بدون راتب بالأجر اليومي.', NULL),
    ('st.exceeded_defer', 'st', N'Defer in reverse priority order', N'التأجيل بعكس ترتيب الأولوية', NULL),
    ('st.exceeded_defer_hint', 'st', N'Deductions at the bottom of the list move to the next period first.', N'تنتقل الاستقطاعات في أسفل القائمة إلى الفترة التالية أولاً.', NULL),
    ('st.exceeded_warn', 'st', N'Warn only', N'تنبيه فقط', NULL),
    ('st.exceeded_warn_hint', 'st', N'Every deduction is taken; the payroll shows a warning to review.', N'تُستقطع كل الاستقطاعات ويُظهر الراتب تنبيهاً للمراجعة.', NULL),
    ('st.fields', 'st', N'Fields', N'الحقول', NULL),
    ('st.fields_hint', 'st', N'The columns of the file in order - top = first. Fixed-width files need the width of every field.', N'أعمدة الملف بالترتيب - الأعلى = الأول. تحتاج الملفات ثابتة العرض إلى عرض كل حقل.', NULL),
    ('st.file_name', 'st', N'File name', N'اسم الملف', NULL),
    ('st.file_name_hint', 'st', N'{EMPLOYER} = WPS employer code, {PERIOD} = YYYYMM, {DATE} = pay date.', N'{EMPLOYER} = رمز صاحب العمل، {PERIOD} = السنة والشهر، {DATE} = تاريخ الدفع.', NULL),
    ('st.fixed_value', 'st', N'Fixed value', N'قيمة ثابتة', NULL),
    ('st.fixed_value_hint', 'st', N'For "Fixed value" only', N'لـ "قيمة ثابتة" فقط', NULL),
    ('st.formats_subtitle', 'st', N'The salary (WPS) file layout of each bank - one default format serves every bank without its own.', N'تخطيط ملف الرواتب (حماية الأجور) لكل بنك - صيغة افتراضية واحدة لكل بنك ليست له صيغة خاصة.', NULL),
    ('st.ft_csv', 'st', N'CSV', N'CSV', NULL),
    ('st.ft_fixed', 'st', N'Fixed width', N'عرض ثابت', NULL),
    ('st.ft_txt', 'st', N'Delimited text', N'نص مفصول', NULL),
    ('st.gl_accounts', 'st', N'GL accounts', N'حسابات دفتر الأستاذ', NULL),
    ('st.gl_company_hint', 'st', N'The pay item types and cost centers of this company.', N'أنواع البنود ومراكز التكلفة لهذه الشركة.', NULL),
    ('st.gl_mappings', 'st', N'GL mappings', N'ربط دفتر الأستاذ', NULL),
    ('st.gl_subtitle', 'st', N'The debit and credit GL accounts each pay item type posts to - per cost center or for any.', N'حسابات المدين والدائن التي يُرحّل إليها كل نوع بند - لكل مركز تكلفة أو لأيٍّ منها.', NULL),
    ('st.header_no', 'st', N'No header', N'بدون ترويسة', NULL),
    ('st.header_row', 'st', N'Header row', N'صف الترويسة', NULL),
    ('st.header_row_hint', 'st', N'The first line holds the field names.', N'السطر الأول يحتوي أسماء الحقول.', NULL),
    ('st.header_yes', 'st', N'Header', N'ترويسة', NULL),
    ('st.level2_amount_hint', 'st', N'Leave empty for both levels always; enter an amount for level 2 only above it.', N'اتركه فارغاً للمستويين دائماً؛ أو أدخل مبلغاً ليلزم المستوى الثاني فوقه فقط.', NULL),
    ('st.level_1', 'st', N'Level 1', N'المستوى 1', NULL),
    ('st.level_2', 'st', N'Level 2', N'المستوى 2', NULL),
    ('st.move_down', 'st', N'Move down', N'تحريك لأسفل', NULL),
    ('st.move_up', 'st', N'Move up', N'تحريك لأعلى', NULL),
    ('st.no_calendars_text', 'st', N'Add a payroll calendar first (Payroll Processing > Payroll Calendar).', N'أضف تقويم رواتب أولاً (معالجة الرواتب > تقويم الرواتب).', NULL),
    ('st.no_calendars_yet', 'st', N'No payroll calendars yet', N'لا توجد تقاويم رواتب بعد', NULL),
    ('st.no_delegate', 'st', N'No delegate', N'بدون مفوض', NULL),
    ('st.no_formats_yet', 'st', N'No bank formats yet', N'لا توجد صيغ بنوك بعد', NULL),
    ('st.no_mappings_yet', 'st', N'No GL mappings yet', N'لا يوجد ربط لدفتر الأستاذ بعد', NULL),
    ('st.no_routes_yet', 'st', N'No approval routes yet', N'لا توجد مسارات اعتماد بعد', NULL),
    ('st.no_rules_yet', 'st', N'No deduction rules yet', N'لا توجد قواعد استقطاع بعد', NULL),
    ('st.not_set', 'st', N'Not set', N'غير محدد', NULL),
    ('st.not_set_defaults', 'st', N'Defaults', N'افتراضي', NULL),
    ('st.nothing_prorated', 'st', N'Nothing prorated', N'لا يوجد تناسب', NULL),
    ('st.of_gross', 'st', N'of gross', N'من الإجمالي', NULL),
    ('st.one_level_only', 'st', N'One level only', N'مستوى واحد فقط', NULL),
    ('st.pad', 'st', N'Pad', N'الحشو', NULL),
    ('st.payroll_calendars', 'st', N'Payroll calendars', N'تقاويم الرواتب', NULL),
    ('st.priority_hint', 'st', N'Statutory deductions are always taken. When the limit is exceeded, deductions are deferred from the bottom of the list up.', N'الاستقطاعات القانونية تُستقطع دائماً. عند تجاوز الحد تؤجل الاستقطاعات من أسفل القائمة صعوداً.', NULL),
    ('st.proc_final_settlement', 'st', N'Final settlement', N'التسوية النهائية', NULL),
    ('st.proc_loan', 'st', N'Loan', N'القرض', NULL),
    ('st.proc_payroll_adjustment', 'st', N'Payroll adjustment', N'تعديل الرواتب', NULL),
    ('st.proc_payroll_run', 'st', N'Payroll run', N'تشغيل الرواتب', NULL),
    ('st.proc_salary_advance', 'st', N'Salary advance', N'سلفة الراتب', NULL),
    ('st.proc_salary_revision', 'st', N'Salary revision', N'تعديل الراتب', NULL),
    ('st.proration_example', 'st', N'Example: an employee joining on the 11th of a 30-day month with a basic of KWD 780 on a fixed 26-day basis is paid 780 / 26 x 18 working days = KWD 540.000.', N'مثال: موظف التحق في اليوم 11 من شهر 30 يوماً براتب أساسي 780 د.ك على أساس 26 يوماً ثابتاً يُدفع له 780 / 26 × 18 يوم عمل = 540.000 د.ك.', NULL),
    ('st.proration_subtitle', 'st', N'How a partial period is paid, per payroll calendar - the day basis and which events are prorated.', N'كيف تُدفع الفترة الجزئية لكل تقويم رواتب - أساس الأيام والأحداث التي يُطبق عليها التناسب.', NULL),
    ('st.rest_days', 'st', N'Rest days', N'أيام الراحة', NULL),
    ('st.rest_days_counted', 'st', N'Counted as paid days', N'تُحسب أيام مدفوعة', NULL),
    ('st.rest_days_excluded', 'st', N'Rest days not counted', N'أيام الراحة لا تُحسب', NULL),
    ('st.rest_days_hint', 'st', N'On a working-days basis, weekly rest days inside a partial period are not paid days.', N'على أساس أيام العمل، أيام الراحة الأسبوعية داخل الفترة الجزئية ليست أيام مدفوعة.', NULL),
    ('st.sample_trailer', 'st', N'(trailer: record count and total amount)', N'(التذييل: عدد السجلات والمبلغ الإجمالي)', NULL),
    ('st.select_item_type', 'st', N'Select a pay item type', N'اختر نوع البند', NULL),
    ('st.select_role', 'st', N'Select a role', N'اختر الدور', NULL),
    ('st.self_approval_hint', 'st', N'The person who prepared a request may also approve it.', N'يمكن لمن أعدّ الطلب أن يعتمده أيضاً.', NULL),
    ('st.src_account_no', 'st', N'Employee account number', N'رقم حساب الموظف', NULL),
    ('st.src_allowances', 'st', N'Allowances', N'البدلات', NULL),
    ('st.src_bank_swift', 'st', N'Bank SWIFT code', N'رمز سويفت للبنك', NULL),
    ('st.src_bank_wps_code', 'st', N'Bank WPS code', N'رمز البنك في حماية الأجور', NULL),
    ('st.src_basic_amount', 'st', N'Basic salary', N'الراتب الأساسي', NULL),
    ('st.src_civil_id', 'st', N'Civil ID', N'الرقم المدني', NULL),
    ('st.src_constant', 'st', N'Fixed value', N'قيمة ثابتة', NULL),
    ('st.src_debit_iban', 'st', N'Company (debit) IBAN', N'آيبان الشركة (المدين)', NULL),
    ('st.src_deductions', 'st', N'Deductions', N'الاستقطاعات', NULL),
    ('st.src_employee_code', 'st', N'Employee code', N'رمز الموظف', NULL),
    ('st.src_employee_name', 'st', N'Employee name', N'اسم الموظف', NULL),
    ('st.src_employer_code', 'st', N'WPS employer code', N'رمز صاحب العمل', NULL),
    ('st.src_iban', 'st', N'Employee IBAN', N'آيبان الموظف', NULL),
    ('st.src_net_amount', 'st', N'Net salary', N'صافي الراتب', NULL),
    ('st.src_pam_file_no', 'st', N'PAM file number', N'رقم ملف الهيئة العامة للقوى العاملة', NULL),
    ('st.src_pay_date', 'st', N'Pay date', N'تاريخ الدفع', NULL),
    ('st.src_period_yyyymm', 'st', N'Period (YYYYMM)', N'الفترة (سنة وشهر)', NULL),
    ('st.trailer_no', 'st', N'no trailer', N'بدون تذييل', NULL),
    ('st.trailer_row', 'st', N'Trailer row', N'صف التذييل', NULL),
    ('st.trailer_row_hint', 'st', N'A last line with the record count and total amount.', N'سطر أخير بعدد السجلات والمبلغ الإجمالي.', NULL),
    ('st.trailer_yes', 'st', N'trailer', N'تذييل', NULL),
    ('st.width', 'st', N'Width', N'العرض', NULL),
    ('msg.st_dp_company', 'msg', N'Select the company the rule is for (the default already exists).', N'اختر الشركة التي تخصها القاعدة (القاعدة الافتراضية موجودة).', N'Select the company the rule is for (the default already exists).'),
    ('msg.st_dp_max', 'msg', N'Enter the maximum deductions as a percentage above 0 and up to 100.', N'أدخل الحد الأقصى للاستقطاعات كنسبة أكبر من 0 وحتى 100.', N'Enter the maximum deductions as a percentage above 0 and up to 100.'),
    ('msg.st_dp_when', 'msg', N'Choose what happens when the limit is exceeded.', N'اختر ما يحدث عند تجاوز الحد.', N'Choose what happens when the limit is exceeded.'),
    ('msg.st_dp_calendar', 'msg', N'The payroll calendar does not belong to the selected company.', N'تقويم الرواتب لا يتبع الشركة المختارة.', N'The payroll calendar does not belong to the selected company.'),
    ('msg.st_dp_dup', 'msg', N'A deduction rule already exists for this company and calendar. Edit that one instead.', N'توجد قاعدة استقطاع لهذه الشركة والتقويم. عدّلها بدلاً من ذلك.', N'A deduction rule already exists for this company and calendar. Edit that one instead.'),
    ('msg.st_dp_lines', 'msg', N'Add the deduction priorities.', N'أضف أولويات الاستقطاع.', N'Add the deduction priorities.'),
    ('msg.st_dp_line', 'msg', N'Every priority needs a deduction group and what happens to it.', N'تحتاج كل أولوية إلى مجموعة استقطاع وما يحدث لها.', N'Every priority needs a deduction group and what happens to it.'),
    ('msg.st_dp_once', 'msg', N'Each deduction group can be listed once only.', N'يمكن إدراج كل مجموعة استقطاع مرة واحدة فقط.', N'Each deduction group can be listed once only.'),
    ('msg.st_dp_statutory', 'msg', N'Statutory deductions (PIFSS) are always taken - they cannot be deferred.', N'الاستقطاعات القانونية (التأمينات) تُستقطع دائماً ولا يمكن تأجيلها.', N'Statutory deductions (PIFSS) are always taken - they cannot be deferred.'),
    ('msg.st_dp_created', 'msg', N'Deduction rule created successfully.', N'تم إنشاء قاعدة الاستقطاع بنجاح.', N'Deduction rule created successfully.'),
    ('msg.st_dp_updated', 'msg', N'Deduction rule updated successfully.', N'تم تحديث قاعدة الاستقطاع بنجاح.', N'Deduction rule updated successfully.'),
    ('msg.st_dp_default', 'msg', N'The default rule applies to every company without its own - it can be edited, not removed or deactivated.', N'القاعدة الافتراضية تنطبق على كل شركة ليست لها قاعدة خاصة - يمكن تعديلها ولا يمكن حذفها أو إيقافها.', N'The default rule applies to every company without its own - it can be edited, not removed or deactivated.'),
    ('msg.st_dp_deleted', 'msg', N'Deduction rule deleted successfully.', N'تم حذف قاعدة الاستقطاع بنجاح.', N'Deduction rule deleted successfully.'),
    ('msg.st_dp_on', 'msg', N'Deduction rule activated.', N'تم تفعيل قاعدة الاستقطاع.', N'Deduction rule activated.'),
    ('msg.st_dp_off', 'msg', N'Deduction rule deactivated.', N'تم إيقاف قاعدة الاستقطاع.', N'Deduction rule deactivated.'),
    ('msg.st_pr_missing', 'msg', N'That payroll calendar no longer exists. Refresh and try again.', N'تقويم الرواتب لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That payroll calendar no longer exists. Refresh and try again.'),
    ('msg.st_pr_basis', 'msg', N'Choose the day basis; a fixed basis needs the days per month (1 to 31).', N'اختر أساس الأيام؛ الأساس الثابت يحتاج عدد الأيام في الشهر (1 إلى 31).', N'Choose the day basis; a fixed basis needs the days per month (1 to 31).'),
    ('msg.st_pr_saved', 'msg', N'Proration rule saved successfully.', N'تم حفظ قاعدة التناسب بنجاح.', N'Proration rule saved successfully.'),
    ('msg.st_ap_process', 'msg', N'Select the process.', N'اختر العملية.', N'Select the process.'),
    ('msg.st_ap_company', 'msg', N'Select the company the route is for (the default already exists).', N'اختر الشركة التي يخصها المسار (المسار الافتراضي موجود).', N'Select the company the route is for (the default already exists).'),
    ('msg.st_ap_level1', 'msg', N'Select the level 1 approver role.', N'اختر دور المعتمد في المستوى 1.', N'Select the level 1 approver role.'),
    ('msg.st_ap_level2', 'msg', N'Select the level 2 approver role, or clear the level 2 amount and delegate.', N'اختر دور المعتمد في المستوى 2، أو امسح مبلغ ومفوض المستوى 2.', N'Select the level 2 approver role, or clear the level 2 amount and delegate.'),
    ('msg.st_ap_same', 'msg', N'Level 2 must be a different role from level 1.', N'يجب أن يكون المستوى 2 دوراً مختلفاً عن المستوى 1.', N'Level 2 must be a different role from level 1.'),
    ('msg.st_ap_amount', 'msg', N'Enter an amount of 0 or more.', N'أدخل مبلغاً قيمته 0 أو أكثر.', N'Enter an amount of 0 or more.'),
    ('msg.st_ap_role', 'msg', N'An approver role is not available for this company.', N'أحد أدوار الاعتماد غير متاح لهذه الشركة.', N'An approver role is not available for this company.'),
    ('msg.st_ap_delegate', 'msg', N'A delegate is not an active user.', N'أحد المفوضين ليس مستخدماً نشطاً.', N'A delegate is not an active user.'),
    ('msg.st_ap_dup', 'msg', N'This company already has its own route for this process. Edit that one instead.', N'لهذه الشركة مسار خاص لهذه العملية. عدّله بدلاً من ذلك.', N'This company already has its own route for this process. Edit that one instead.'),
    ('msg.st_ap_created', 'msg', N'Approval route created successfully.', N'تم إنشاء مسار الاعتماد بنجاح.', N'Approval route created successfully.'),
    ('msg.st_ap_updated', 'msg', N'Approval route updated successfully.', N'تم تحديث مسار الاعتماد بنجاح.', N'Approval route updated successfully.'),
    ('msg.st_ap_default', 'msg', N'The default route applies to every company without its own - it can be edited, not removed or deactivated.', N'المسار الافتراضي ينطبق على كل شركة ليس لها مسار خاص - يمكن تعديله ولا يمكن حذفه أو إيقافه.', N'The default route applies to every company without its own - it can be edited, not removed or deactivated.'),
    ('msg.st_ap_deleted', 'msg', N'Approval route deleted successfully.', N'تم حذف مسار الاعتماد بنجاح.', N'Approval route deleted successfully.'),
    ('msg.st_ap_on', 'msg', N'Approval route activated.', N'تم تفعيل مسار الاعتماد.', N'Approval route activated.'),
    ('msg.st_ap_off', 'msg', N'Approval route deactivated.', N'تم إيقاف مسار الاعتماد.', N'Approval route deactivated.'),
    ('msg.st_bf_required', 'msg', N'Code and name are required.', N'الرمز والاسم مطلوبان.', N'Code and name are required.'),
    ('msg.st_bf_type', 'msg', N'Choose the file type; a CSV or text file needs a delimiter.', N'اختر نوع الملف؛ ملف CSV أو النص يحتاج إلى فاصل.', N'Choose the file type; a CSV or text file needs a delimiter.'),
    ('msg.st_bf_bank', 'msg', N'Select a valid bank.', N'اختر بنكاً صحيحاً.', N'Select a valid bank.'),
    ('msg.st_bf_bank_dup', 'msg', N'This bank already has an active format. Deactivate it first, or edit it.', N'لهذا البنك صيغة مفعّلة. أوقفها أولاً أو عدّلها.', N'This bank already has an active format. Deactivate it first, or edit it.'),
    ('msg.st_bf_fields', 'msg', N'Add the fields of the file.', N'أضف حقول الملف.', N'Add the fields of the file.'),
    ('msg.st_bf_field', 'msg', N'Every field needs a name and a source (a fixed value needs the value); widths are 1 to 500.', N'يحتاج كل حقل إلى اسم ومصدر (القيمة الثابتة تحتاج القيمة)؛ والعرض من 1 إلى 500.', N'Every field needs a name and a source (a fixed value needs the value); widths are 1 to 500.'),
    ('msg.st_bf_width', 'msg', N'A fixed-width file needs the width of every field.', N'الملف ثابت العرض يحتاج إلى عرض كل حقل.', N'A fixed-width file needs the width of every field.'),
    ('msg.st_bf_min', 'msg', N'A salary file needs at least the employee''s IBAN (or account number) and the net amount.', N'يحتاج ملف الرواتب على الأقل إلى آيبان الموظف (أو رقم الحساب) وصافي المبلغ.', N'A salary file needs at least the employee''s IBAN (or account number) and the net amount.'),
    ('msg.st_bf_created', 'msg', N'Bank file format created successfully.', N'تم إنشاء صيغة ملف البنك بنجاح.', N'Bank file format created successfully.'),
    ('msg.st_bf_updated', 'msg', N'Bank file format updated successfully.', N'تم تحديث صيغة ملف البنك بنجاح.', N'Bank file format updated successfully.'),
    ('msg.st_bf_default', 'msg', N'This is the default format. Make another format the default first.', N'هذه هي الصيغة الافتراضية. اجعل صيغة أخرى افتراضية أولاً.', N'This is the default format. Make another format the default first.'),
    ('msg.st_bf_deleted', 'msg', N'Bank file format deleted successfully.', N'تم حذف صيغة ملف البنك بنجاح.', N'Bank file format deleted successfully.'),
    ('msg.st_bf_other', 'msg', N'This bank already has another active format, so this one cannot be re-activated.', N'لهذا البنك صيغة أخرى مفعّلة، لذا لا يمكن إعادة تفعيل هذه الصيغة.', N'This bank already has another active format, so this one cannot be re-activated.'),
    ('msg.st_bf_on', 'msg', N'Format activated.', N'تم تفعيل الصيغة.', N'Format activated.'),
    ('msg.st_bf_off', 'msg', N'Format deactivated.', N'تم إيقاف الصيغة.', N'Format deactivated.'),
    ('msg.st_gl_item', 'msg', N'Select the pay item type.', N'اختر نوع البند.', N'Select the pay item type.'),
    ('msg.st_gl_accounts', 'msg', N'Enter the debit and the credit account.', N'أدخل الحساب المدين والحساب الدائن.', N'Enter the debit and the credit account.'),
    ('msg.st_gl_same', 'msg', N'The debit and credit accounts must be different.', N'يجب أن يختلف الحساب المدين عن الدائن.', N'The debit and credit accounts must be different.'),
    ('msg.st_gl_cc', 'msg', N'The cost center does not belong to the pay item type''s company.', N'مركز التكلفة لا يتبع شركة نوع البند.', N'The cost center does not belong to the pay item type''s company.'),
    ('msg.st_gl_dup', 'msg', N'This pay item type is already mapped for this cost center. Edit that mapping instead.', N'نوع البند مربوط لمركز التكلفة هذا. عدّل الربط بدلاً من ذلك.', N'This pay item type is already mapped for this cost center. Edit that mapping instead.'),
    ('msg.st_gl_created', 'msg', N'GL mapping created successfully.', N'تم إنشاء ربط دفتر الأستاذ بنجاح.', N'GL mapping created successfully.'),
    ('msg.st_gl_updated', 'msg', N'GL mapping updated successfully.', N'تم تحديث ربط دفتر الأستاذ بنجاح.', N'GL mapping updated successfully.'),
    ('msg.st_gl_deleted', 'msg', N'GL mapping deleted successfully.', N'تم حذف ربط دفتر الأستاذ بنجاح.', N'GL mapping deleted successfully.'),
    ('msg.st_gl_on', 'msg', N'GL mapping activated.', N'تم تفعيل ربط دفتر الأستاذ.', N'GL mapping activated.'),
    ('msg.st_gl_off', 'msg', N'GL mapping deactivated.', N'تم إيقاف ربط دفتر الأستاذ.', N'GL mapping deactivated.'),
    ('msg.st_v_pct', 'msg', N'Enter a percentage above 0 and up to 100.', N'أدخل نسبة أكبر من 0 وحتى 100.', N'Enter a percentage above 0 and up to 100.'),
    ('msg.st_v_days', 'msg', N'Enter the days per month (1 to 31).', N'أدخل عدد الأيام في الشهر (1 إلى 31).', N'Enter the days per month (1 to 31).'),
    ('msg.st_v_debit', 'msg', N'Enter the debit account.', N'أدخل الحساب المدين.', N'Enter the debit account.'),
    ('msg.st_v_credit', 'msg', N'Enter the credit account.', N'أدخل الحساب الدائن.', N'Enter the credit account.'),
    ('msg.st_v_width', 'msg', N'Enter a width from 1 to 500.', N'أدخل عرضاً من 1 إلى 500.', N'Enter a width from 1 to 500.');
INSERT INTO [Core].[UiLabels] (LabelKey, Module, EnglishText, ArabicText, SourceText)
SELECT s.LabelKey, s.Module, s.EnglishText, s.ArabicText, s.SourceText
FROM   #Seed AS s
WHERE  NOT EXISTS (SELECT 1 FROM [Core].[UiLabels] AS l WHERE l.LabelKey = s.LabelKey AND l.Deleted = 0);

DECLARE @Inserted INT = @@ROWCOUNT;

UPDATE l
   SET l.ArabicText = ISNULL(NULLIF(l.ArabicText, N''), s.ArabicText),
       l.SourceText = ISNULL(l.SourceText, s.SourceText)
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.LabelKey = l.LabelKey
WHERE  l.Deleted = 0
  AND (   (NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL)
       OR (l.SourceText IS NULL AND s.SourceText IS NOT NULL));

DECLARE @Completed INT = @@ROWCOUNT;

/* messages harvested by an earlier run of db/33 (msg.auto_*) get their Arabic too */
UPDATE l
   SET l.ArabicText = s.ArabicText
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.Module = 'msg' AND l.EnglishText = s.EnglishText COLLATE Latin1_General_BIN
WHERE  l.Deleted = 0 AND l.LabelKey LIKE 'msg.auto[_]%' AND NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL;

PRINT CONCAT(N'Payroll Settings labels inserted: ', @Inserted, N', completed: ', @Completed);
DROP TABLE #Seed;
GO
