/* =====================================================================
   46_Payroll_Settings_Labels.sql  -  HRMS: English + Arabic labels of the
   Payroll Settings screens (Payroll > Payroll Settings)
   ---------------------------------------------------------------------
   Run after 33 (Core.UiLabels). Only labels - the screens use the
   procedures of db/30 (and later db/47+). Idempotent: new keys are
   inserted, existing keys only completed (text already edited in
   Core.UiLabels is never overwritten).

     st.*       Payroll Settings screens
     js.st_*    wwwroot/js/payroll-settings.js
     msg.st_*   messages of the settings procedures - matched by SourceText
   ===================================================================== */
SET NOCOUNT ON;
GO
IF OBJECT_ID(N'tempdb..#Seed') IS NOT NULL DROP TABLE #Seed;
CREATE TABLE #Seed (
    LabelKey    VARCHAR(150)   COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
    Module      VARCHAR(30)    COLLATE DATABASE_DEFAULT NOT NULL,
    EnglishText NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL,
    ArabicText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
    SourceText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL
);
INSERT INTO #Seed (LabelKey, Module, EnglishText, ArabicText, SourceText) VALUES
    ('js.st_failed', 'js', N'The request could not be completed.', N'تعذّر إتمام الطلب.', NULL),
    ('st.title_pay_item_types', 'st', N'Pay Item Types', N'أنواع بنود الرواتب', N'Pay Item Types'),
    ('st.item_types_subtitle', 'st', N'The earnings and deductions offered when adding a pay item, and how the payroll treats them', N'الاستحقاقات والاستقطاعات المتاحة عند إضافة بند راتب، وكيف يعاملها مسير الرواتب', NULL),
    ('st.item_types_banner_title', 'st', N'Data-driven.', N'تُدار من البيانات.', NULL),
    ('st.item_types_banner_text', 'st', N'Add, rename or deactivate item types without any code change. Standard types (Basic Salary, PIFSS, Loan ...) are known to the payroll engine: they can be renamed and re-flagged but not deleted.', N'أضف أنواع البنود أو أعد تسميتها أو أوقفها دون أي تعديل برمجي. الأنواع القياسية (الراتب الأساسي، التأمينات، القرض ...) يعرفها محرك الرواتب: يمكن إعادة تسميتها وتعديل خصائصها دون حذفها.', NULL),
    ('st.add_item_type', 'st', N'Add item type', N'إضافة نوع بند', NULL),
    ('st.edit_item_type', 'st', N'Edit item type', N'تعديل نوع البند', NULL),
    ('st.delete_item_type_text', 'st', N'Delete this item type? It can only be deleted while no salary structure uses it.', N'حذف نوع البند هذا؟ لا يمكن حذفه إلا إذا لم يُستخدم في أي هيكل رواتب.', NULL),
    ('st.add_standard_types', 'st', N'Add standard types', N'إضافة الأنواع القياسية', NULL),
    ('st.add_standard_types_hint', 'st', N'Adds the standard item types this company is missing (Basic Salary, PIFSS, Loan ...)', N'يضيف الأنواع القياسية الناقصة لهذه الشركة (الراتب الأساسي، التأمينات، القرض ...)', NULL),
    ('st.search_item_types', 'st', N'Search code, name or GL account', N'ابحث بالرمز أو الاسم أو حساب الأستاذ', NULL),
    ('st.type', 'st', N'Type', N'النوع', NULL),
    ('st.all_types', 'st', N'All types', N'جميع الأنواع', NULL),
    ('st.earnings', 'st', N'Earnings', N'الاستحقاقات', NULL),
    ('st.deductions', 'st', N'Deductions', N'الاستقطاعات', NULL),
    ('st.1_item_type', 'st', N'1 item type', N'نوع بند واحد', NULL),
    ('st.0_item_types', 'st', N'{0} item types', N'{0} أنواع بنود', NULL),
    ('st.no_item_types_match', 'st', N'No item type matches your search', N'لا يوجد نوع بند يطابق البحث', NULL),
    ('st.no_item_types_yet', 'st', N'No item types yet', N'لا توجد أنواع بنود بعد', NULL),
    ('st.no_item_types_text', 'st', N'Use Add standard types to load Basic Salary, PIFSS, Loan and the other standard types, then add your own.', N'استخدم إضافة الأنواع القياسية لتحميل الراتب الأساسي والتأمينات والقرض وغيرها، ثم أضف أنواعك.', NULL),
    ('st.pay_item_types', 'st', N'Pay item types', N'أنواع بنود الرواتب', NULL),
    ('st.item_type', 'st', N'Item type', N'نوع البند', NULL),
    ('st.class', 'st', N'Class', N'الفئة', NULL),
    ('st.class_salary', 'st', N'Salary', N'راتب', NULL),
    ('st.class_earning', 'st', N'Earning', N'استحقاق', NULL),
    ('st.class_deduction', 'st', N'Deduction', N'استقطاع', NULL),
    ('st.class_loan', 'st', N'Loan / advance', N'قرض / سلفة', NULL),
    ('st.class_statutory', 'st', N'Statutory', N'نظامي', NULL),
    ('st.calculation', 'st', N'Calculation', N'طريقة الحساب', NULL),
    ('st.included_in', 'st', N'Included in', N'يدخل في', NULL),
    ('st.gl_account', 'st', N'GL account', N'حساب الأستاذ العام', NULL),
    ('st.gl_account_name', 'st', N'GL account name', N'اسم حساب الأستاذ العام', NULL),
    ('st.standard', 'st', N'Standard', N'قياسي', NULL),
    ('st.standard_hint', 'st', N'A standard type the payroll engine relies on', N'نوع قياسي يعتمد عليه محرك الرواتب', NULL),
    ('st.standard_type', 'st', N'Standard type.', N'نوع قياسي.', NULL),
    ('st.standard_type_text', 'st', N'The payroll engine knows it by its code and type, so those cannot change; name, flags and accounting can.', N'يعرفه محرك الرواتب برمزه ونوعه، لذا لا يمكن تغييرهما؛ أما الاسم والخصائص والحسابات فيمكن تعديلها.', NULL),
    ('st.of', 'st', N'of', N'من', NULL),
    ('st.recurring', 'st', N'Recurring', N'متكرر', NULL),
    ('st.one_time', 'st', N'One-time', N'لمرة واحدة', NULL),
    ('st.fixed', 'st', N'Fixed', N'ثابت', NULL),
    ('st.variable', 'st', N'Variable', N'متغير', NULL),
    ('st.method', 'st', N'Method', N'الطريقة', NULL),
    ('st.method_amount', 'st', N'Amount', N'مبلغ', NULL),
    ('st.method_percentage', 'st', N'Percentage', N'نسبة مئوية', NULL),
    ('st.method_days', 'st', N'Days', N'أيام', NULL),
    ('st.method_hours', 'st', N'Hours', N'ساعات', NULL),
    ('st.method_formula', 'st', N'Formula', N'معادلة', NULL),
    ('st.method_system', 'st', N'Calculated by the payroll', N'يحتسبه مسير الرواتب', NULL),
    ('st.base', 'st', N'Base', N'الأساس', NULL),
    ('st.base_basic', 'st', N'Basic salary', N'الراتب الأساسي', NULL),
    ('st.base_fixed_gross', 'st', N'Fixed gross', N'الإجمالي الثابت', NULL),
    ('st.base_overtime', 'st', N'Overtime base', N'أساس العمل الإضافي', NULL),
    ('st.base_indemnity', 'st', N'Indemnity base', N'أساس مكافأة نهاية الخدمة', NULL),
    ('st.flag_pifss', 'st', N'PIFSS', N'التأمينات', NULL),
    ('st.flag_eos', 'st', N'End of service', N'نهاية الخدمة', NULL),
    ('st.flag_overtime', 'st', N'Overtime', N'العمل الإضافي', NULL),
    ('st.flag_leave', 'st', N'Leave salary', N'راتب الإجازة', NULL),
    ('st.flag_prorated', 'st', N'Prorated', N'يُحتسب بالتناسب', NULL),
    ('st.flag_taxable', 'st', N'Taxable', N'خاضع للضريبة', NULL),
    ('st.name_english', 'st', N'Name (English)', N'الاسم (إنجليزي)', NULL),
    ('st.name_arabic', 'st', N'Name (Arabic)', N'الاسم (عربي)', NULL),
    ('st.payslip_label', 'st', N'Payslip label', N'التسمية في كشف الراتب', NULL),
    ('st.payslip_label_hint', 'st', N'Leave empty to use the name', N'اتركه فارغاً لاستخدام الاسم', NULL),
    ('st.display_order', 'st', N'Display order', N'ترتيب العرض', NULL),
    ('st.earning', 'st', N'Earning', N'استحقاق', NULL),
    ('st.earning_hint', 'st', N'Adds to the pay', N'يُضاف إلى الراتب', NULL),
    ('st.deduction', 'st', N'Deduction', N'استقطاع', NULL),
    ('st.deduction_hint', 'st', N'Taken from the pay', N'يُخصم من الراتب', NULL),
    ('st.value_type', 'st', N'Value', N'القيمة', NULL),
    ('st.default_amount', 'st', N'Default amount (KWD)', N'المبلغ الافتراضي (د.ك)', NULL),
    ('st.default_percentage', 'st', N'Default percentage', N'النسبة الافتراضية', NULL),
    ('st.formula', 'st', N'Formula', N'المعادلة', NULL),
    ('st.min_amount', 'st', N'Minimum amount', N'الحد الأدنى', NULL),
    ('st.max_amount', 'st', N'Maximum amount', N'الحد الأقصى', NULL),
    ('st.behaviour', 'st', N'Behaviour', N'السلوك', NULL),
    ('st.recurring_hint', 'st', N'Paid or taken every month until ended', N'يُصرف أو يُخصم كل شهر حتى إيقافه', NULL),
    ('st.prorated_hint', 'st', N'Paid for the days worked in a partial month', N'يُصرف عن أيام العمل في الشهر الجزئي', NULL),
    ('st.show_on_payslip', 'st', N'Show on payslip', N'يظهر في كشف الراتب', NULL),
    ('st.show_on_payslip_hint', 'st', N'Listed as its own line on the payslip', N'يظهر كسطر مستقل في كشف الراتب', NULL),
    ('st.taxable_hint', 'st', N'Counted as taxable income', N'يُحتسب دخلاً خاضعاً للضريبة', NULL),
    ('st.included_in_bases', 'st', N'Included in the bases of (earnings only)', N'يدخل في أساس احتساب (للاستحقاقات فقط)', NULL),
    ('st.pifss_hint', 'st', N'Part of the PIFSS contribution salary', N'جزء من راتب الاشتراك في التأمينات', NULL),
    ('st.eos_hint', 'st', N'Part of the end-of-service indemnity salary', N'جزء من راتب مكافأة نهاية الخدمة', NULL),
    ('st.overtime_hint', 'st', N'Part of the overtime hourly rate base', N'جزء من أساس أجر ساعة العمل الإضافي', NULL),
    ('st.leave_hint', 'st', N'Part of the leave salary', N'جزء من راتب الإجازة', NULL),
    ('st.accounting', 'st', N'Accounting', N'المحاسبة', NULL),
    ('st.cost_center', 'st', N'Cost center', N'مركز التكلفة', NULL),
    ('st.employee_cost_center', 'st', N'The employee''s cost center', N'مركز تكلفة الموظف', NULL),
    ('st.description', 'st', N'Description', N'الوصف', NULL),
    ('msg.st_pc_created_earning', 'msg', N'Earning component created successfully.', N'تم إنشاء نوع الاستحقاق بنجاح.', N'Earning component created successfully.'),
    ('msg.st_pc_created_deduction', 'msg', N'Deduction component created successfully.', N'تم إنشاء نوع الاستقطاع بنجاح.', N'Deduction component created successfully.'),
    ('msg.st_pc_updated', 'msg', N'Component updated successfully.', N'تم تحديث نوع البند بنجاح.', N'Component updated successfully.'),
    ('msg.st_pc_deleted', 'msg', N'Component deleted successfully.', N'تم حذف نوع البند بنجاح.', N'Component deleted successfully.'),
    ('msg.st_pc_activated', 'msg', N'Component activated.', N'تم تفعيل نوع البند.', N'Component activated.'),
    ('msg.st_pc_deactivated', 'msg', N'Component deactivated.', N'تم إيقاف نوع البند.', N'Component deactivated.'),
    ('msg.st_pc_seed_none', 'msg', N'This company already has all the standard components.', N'لدى هذه الشركة جميع الأنواع القياسية.', N'This company already has all the standard components.'),
    ('msg.st_pc_seed_n', 'msg', N'{0} standard component(s) added.', N'أُضيف {0} من الأنواع القياسية.', N'{0} standard component(s) added.'),
    ('msg.st_pc_basic', 'msg', N'Basic Salary is required by the payroll engine and cannot be deactivated.', N'الراتب الأساسي مطلوب لمحرك الرواتب ولا يمكن إيقافه.', N'Basic Salary is required by the payroll engine and cannot be deactivated.'),
    ('msg.st_pc_basic_delete', 'msg', N'Basic Salary is required by the payroll engine and cannot be deleted.', N'الراتب الأساسي مطلوب لمحرك الرواتب ولا يمكن حذفه.', N'Basic Salary is required by the payroll engine and cannot be deleted.'),
    ('msg.st_pc_std_delete', 'msg', N'This is a standard component the payroll engine relies on. Deactivate it instead of deleting it.', N'هذا نوع قياسي يعتمد عليه محرك الرواتب. أوقفه بدلاً من حذفه.', N'This is a standard component the payroll engine relies on. Deactivate it instead of deleting it.'),
    ('msg.st_pc_in_use', 'msg', N'This component is used in a salary structure and cannot be deleted. Remove it from the structure or deactivate it instead.', N'هذا النوع مستخدم في هيكل رواتب ولا يمكن حذفه. أزله من الهيكل أو أوقفه.', N'This component is used in a salary structure and cannot be deleted. Remove it from the structure or deactivate it instead.'),
    ('msg.st_pc_dup', 'msg', N'That code is already in use. Enter a different code.', N'هذا الرمز مستخدم. أدخل رمزاً آخر.', N'That code is already in use. Enter a different code.'),
    ('msg.st_pc_earn_flags', 'msg', N'Social security, end-of-service, overtime and leave-salary flags apply to earnings only.', N'خصائص التأمينات ونهاية الخدمة والعمل الإضافي وراتب الإجازة تخص الاستحقاقات فقط.', N'Social security, end-of-service, overtime and leave-salary flags apply to earnings only.'),
    ('msg.st_pc_need_base', 'msg', N'Percentage, Days and Hours methods need a calculation base (Basic, Fixed gross, Overtime base or Indemnity base).', N'طرق النسبة والأيام والساعات تحتاج إلى أساس احتساب (الأساسي، الإجمالي الثابت، أساس العمل الإضافي أو أساس نهاية الخدمة).', N'Percentage, Days and Hours methods need a calculation base (Basic, Fixed gross, Overtime base or Indemnity base).'),
    ('msg.st_pc_need_pct', 'msg', N'Enter the default percentage.', N'أدخل النسبة الافتراضية.', N'Enter the default percentage.'),
    ('msg.st_pc_need_formula', 'msg', N'Enter the formula.', N'أدخل المعادلة.', N'Enter the formula.'),
    ('msg.st_pc_minmax', 'msg', N'Maximum amount cannot be less than the minimum amount.', N'لا يمكن أن يقل الحد الأقصى عن الحد الأدنى.', N'Maximum amount cannot be less than the minimum amount.'),
    ('msg.st_pc_cc', 'msg', N'The selected cost center does not belong to this company.', N'مركز التكلفة المختار لا يتبع هذه الشركة.', N'The selected cost center does not belong to this company.'),
    ('st.title_payroll_rules', 'st', N'Payroll Rules', N'قواعد الرواتب', N'Payroll Rules'),
    ('st.rules_subtitle', 'st', N'Kuwait statutory settings - effective-dated, never hard-coded', N'الإعدادات النظامية في الكويت - مؤرخة بتاريخ سريان ولا تُكتب في البرمجة', NULL),
    ('st.unverified_title', 'st', N'{0} statutory settings in force are not verified.', N'{0} من الإعدادات النظامية السارية غير مؤكدة.', NULL),
    ('st.unverified_text', 'st', N'Seeded values must be confirmed by finance / legal before go-live: open each one, check it and tick Verified.', N'يجب أن تؤكد المالية / الشؤون القانونية القيم المبدئية قبل التشغيل: افتح كل إعداد وتحقق منه وفعّل خيار مؤكد.', NULL),
    ('st.all_verified_title', 'st', N'Every statutory setting in force is verified.', N'جميع الإعدادات النظامية السارية مؤكدة.', NULL),
    ('st.all_verified_text', 'st', N'To change a rate, end-date the current row and add a new one from the new date, so history is kept.', N'لتغيير نسبة، حدّد تاريخ انتهاء للسطر الحالي وأضف سطراً جديداً من التاريخ الجديد، ليبقى السجل محفوظاً.', NULL),
    ('st.pifss_rates', 'st', N'Social security (PIFSS) rates', N'نسب التأمينات الاجتماعية', NULL),
    ('st.indemnity_rules', 'st', N'End-of-service indemnity rules', N'قواعد مكافأة نهاية الخدمة', NULL),
    ('st.overtime_rates', 'st', N'Overtime multipliers', N'معاملات العمل الإضافي', NULL),
    ('st.add_rate', 'st', N'Add rate', N'إضافة نسبة', NULL),
    ('st.add_rule_set', 'st', N'Add rule set', N'إضافة مجموعة قواعد', NULL),
    ('st.add_pifss_rate', 'st', N'Add social security rate', N'إضافة نسبة تأمينات', NULL),
    ('st.edit_pifss_rate', 'st', N'Edit social security rate', N'تعديل نسبة التأمينات', NULL),
    ('st.add_indemnity_rules', 'st', N'Add indemnity rule set', N'إضافة قواعد نهاية الخدمة', NULL),
    ('st.edit_indemnity_rules', 'st', N'Edit indemnity rule set', N'تعديل قواعد نهاية الخدمة', NULL),
    ('st.add_overtime_rate', 'st', N'Add overtime multiplier', N'إضافة معامل عمل إضافي', NULL),
    ('st.edit_overtime_rate', 'st', N'Edit overtime multiplier', N'تعديل معامل العمل الإضافي', NULL),
    ('st.delete_rate_text', 'st', N'Delete this row? To change a rate that was already used, end-date it and add a new one instead.', N'حذف هذا السطر؟ لتغيير نسبة سبق استخدامها، حدّد لها تاريخ انتهاء وأضف سطراً جديداً بدلاً من ذلك.', NULL),
    ('st.in_force', 'st', N'In force', N'سارٍ', NULL),
    ('st.in_force_today', 'st', N'In force today', N'سارٍ اليوم', NULL),
    ('st.all_dates', 'st', N'All dates', N'كل التواريخ', NULL),
    ('st.1_rate', 'st', N'1 rate', N'نسبة واحدة', NULL),
    ('st.0_rates', 'st', N'{0} rates', N'{0} نسب', NULL),
    ('st.1_rule_set', 'st', N'1 rule set', N'مجموعة قواعد واحدة', NULL),
    ('st.0_rule_sets', 'st', N'{0} rule sets', N'{0} مجموعات قواعد', NULL),
    ('st.no_rates_match', 'st', N'Nothing matches your search', N'لا توجد نتائج مطابقة', NULL),
    ('st.no_rates_yet', 'st', N'No rates yet', N'لا توجد نسب بعد', NULL),
    ('st.no_rule_sets_yet', 'st', N'No indemnity rules yet', N'لا توجد قواعد نهاية خدمة بعد', NULL),
    ('st.contribution', 'st', N'Contribution', N'الاشتراك', NULL),
    ('st.applies_to', 'st', N'Applies to', N'ينطبق على', NULL),
    ('st.applies_kuwaiti', 'st', N'Kuwaitis', N'الكويتيون', NULL),
    ('st.applies_gcc', 'st', N'GCC nationals', N'مواطنو دول الخليج', NULL),
    ('st.applies_expat', 'st', N'Expatriates', N'الوافدون', NULL),
    ('st.applies_all', 'st', N'Everyone', N'الجميع', NULL),
    ('st.basis', 'st', N'Basis', N'الأساس', NULL),
    ('st.basis_capped', 'st', N'Salary up to the ceiling', N'الراتب حتى الحد الأعلى', NULL),
    ('st.basis_band', 'st', N'Salary band (floor to ceiling)', N'شريحة الراتب (من الحد الأدنى إلى الأعلى)', NULL),
    ('st.basis_hint', 'st', N'Band: only the part of the salary between floor and ceiling (e.g. the supplementary scheme).', N'الشريحة: فقط الجزء من الراتب بين الحدين الأدنى والأعلى (مثل النظام التكميلي).', NULL),
    ('st.employee_rate', 'st', N'Employee rate', N'نسبة الموظف', NULL),
    ('st.employer_rate', 'st', N'Employer rate', N'نسبة صاحب العمل', NULL),
    ('st.government_rate', 'st', N'Government rate', N'نسبة الحكومة', NULL),
    ('st.salary_range', 'st', N'Salary range (KWD)', N'نطاق الراتب (د.ك)', NULL),
    ('st.salary_floor', 'st', N'Salary floor (KWD)', N'الحد الأدنى للراتب (د.ك)', NULL),
    ('st.salary_ceiling', 'st', N'Salary ceiling (KWD)', N'الحد الأعلى للراتب (د.ك)', NULL),
    ('st.salary_ceiling_hint', 'st', N'Empty = no cap', N'فارغ = بلا حد أعلى', NULL),
    ('st.no_cap', 'st', N'no cap', N'بلا حد', NULL),
    ('st.rates_and_salary', 'st', N'Rates and salary', N'النسب والراتب', NULL),
    ('st.effective', 'st', N'Effective', N'السريان', NULL),
    ('st.effective_from', 'st', N'Effective from', N'ساري من', NULL),
    ('st.effective_to', 'st', N'Effective to', N'ساري حتى', NULL),
    ('st.effective_to_hint', 'st', N'Empty = until changed', N'فارغ = حتى يتم التغيير', NULL),
    ('st.open_ended', 'st', N'open-ended', N'مفتوح', NULL),
    ('st.verified', 'st', N'Verified', N'مؤكد', NULL),
    ('st.not_verified', 'st', N'Not verified', N'غير مؤكد', NULL),
    ('st.verified_hint', 'st', N'Confirmed by finance / legal', N'أكدته المالية / الشؤون القانونية', NULL),
    ('st.notes', 'st', N'Notes', N'ملاحظات', NULL),
    ('st.notes_hint', 'st', N'Source of the value (law, circular, date checked)', N'مصدر القيمة (القانون، التعميم، تاريخ التحقق)', NULL),
    ('st.rule_set', 'st', N'Rule set', N'مجموعة القواعد', NULL),
    ('st.daily_divisor', 'st', N'Daily wage divisor', N'قاسم الأجر اليومي', NULL),
    ('st.daily_divisor_hint', 'st', N'Days a month''s wage is divided by (26 in Kuwait)', N'عدد الأيام التي يُقسم عليها الأجر الشهري (26 في الكويت)', NULL),
    ('st.cap_months', 'st', N'Cap (months)', N'الحد الأقصى (أشهر)', NULL),
    ('st.min_service_months', 'st', N'Minimum service (months)', N'الحد الأدنى للخدمة (أشهر)', NULL),
    ('st.slabs_factors', 'st', N'Slabs / factors', N'الشرائح / النسب', NULL),
    ('st.n_slabs_n_factors', 'st', N'{0} slabs · {1} factors', N'{0} شرائح · {1} نسب', NULL),
    ('st.service_slabs', 'st', N'Service slabs', N'شرائح سنوات الخدمة', NULL),
    ('st.service_slabs_hint', 'st', N'What each year of service earns, by band - e.g. 0 to 5 years: 15 days per year; 5 years and above: 1 month per year.', N'ما تستحقه كل سنة خدمة حسب الشريحة - مثال: من 0 إلى 5 سنوات: 15 يوماً عن كل سنة؛ 5 سنوات فأكثر: شهر عن كل سنة.', NULL),
    ('st.from_years', 'st', N'From (years)', N'من (سنوات)', NULL),
    ('st.to_years', 'st', N'To (years)', N'إلى (سنوات)', NULL),
    ('st.and_above', 'st', N'and above', N'فأكثر', NULL),
    ('st.entitlement', 'st', N'Entitlement', N'الاستحقاق', NULL),
    ('st.unit', 'st', N'Unit', N'الوحدة', NULL),
    ('st.days_per_year', 'st', N'Days per year', N'أيام عن كل سنة', NULL),
    ('st.months_per_year', 'st', N'Months per year', N'أشهر عن كل سنة', NULL),
    ('st.add_slab', 'st', N'Add slab', N'إضافة شريحة', NULL),
    ('st.entitlement_factors', 'st', N'Entitlement by separation', N'الاستحقاق حسب نوع إنهاء الخدمة', NULL),
    ('st.entitlement_factors_hint', 'st', N'The % of the indemnity actually paid - e.g. resignation with 3 to 5 years of service: 50 %.', N'النسبة المدفوعة فعلاً من المكافأة - مثال: الاستقالة بخدمة من 3 إلى 5 سنوات: 50 %.', NULL),
    ('st.separation', 'st', N'Separation', N'نوع إنهاء الخدمة', NULL),
    ('st.separation_other', 'st', N'Other', N'أخرى', NULL),
    ('st.paid_percent', 'st', N'Paid %', N'النسبة المدفوعة', NULL),
    ('st.add_factor', 'st', N'Add factor', N'إضافة نسبة', NULL),
    ('st.overtime', 'st', N'Overtime', N'العمل الإضافي', NULL),
    ('st.when', 'st', N'When worked', N'وقت العمل', NULL),
    ('st.ot_normal_day', 'st', N'Normal working day', N'يوم عمل عادي', NULL),
    ('st.ot_rest_day', 'st', N'Weekly rest day', N'يوم الراحة الأسبوعية', NULL),
    ('st.ot_public_holiday', 'st', N'Public holiday', N'عطلة رسمية', NULL),
    ('st.ot_night', 'st', N'Night', N'ليلي', NULL),
    ('st.ot_other', 'st', N'Other', N'أخرى', NULL),
    ('st.multiplier', 'st', N'Multiplier', N'المعامل', NULL),
    ('st.hourly_rate', 'st', N'Hourly rate', N'أجر الساعة', NULL),
    ('st.hourly_rate_formula', 'st', N'Salary ÷ {0} days ÷ {1} h', N'الراتب ÷ {0} يوماً ÷ {1} ساعات', NULL),
    ('st.hourly_divisor_days', 'st', N'Days in the hourly rate', N'الأيام في حساب أجر الساعة', NULL),
    ('st.hours_per_day', 'st', N'Hours per day', N'ساعات اليوم', NULL),
    ('st.hourly_rate_explained', 'st', N'Hourly rate = overtime base salary ÷ days ÷ hours per day; overtime pay = hours × hourly rate × multiplier.', N'أجر الساعة = راتب أساس العمل الإضافي ÷ الأيام ÷ ساعات اليوم؛ أجر العمل الإضافي = الساعات × أجر الساعة × المعامل.', NULL),
    ('st.limits', 'st', N'Limits', N'الحدود', NULL),
    ('st.max_hours_day', 'st', N'Maximum hours per day', N'الحد الأقصى للساعات يومياً', NULL),
    ('st.max_hours_year', 'st', N'Maximum hours per year', N'الحد الأقصى للساعات سنوياً', NULL),
    ('st.n_hours_day', 'st', N'{0} h/day', N'{0} س/يوم', NULL),
    ('st.n_hours_year', 'st', N'{0} h/year', N'{0} س/سنة', NULL),
    ('st.statutory_default', 'st', N'Statutory default', N'الافتراضي النظامي', NULL),
    ('st.statutory_default_all', 'st', N'Statutory default - every company', N'الافتراضي النظامي - كل الشركات', NULL),
    ('st.overtime_company_hint', 'st', N'A company''s own (more generous) multiplier takes precedence over the default for that company.', N'المعامل الخاص بالشركة (الأفضل للموظف) يتقدم على الافتراضي لتلك الشركة.', NULL),
    ('msg.st_svc_slab_one', 'msg', N'Add at least one service slab.', N'أضف شريحة خدمة واحدة على الأقل.', N'Add at least one service slab.'),
    ('msg.st_pifss_overlap', 'msg', N'Another active rate for this contribution and nationality group overlaps these dates. End-date the existing rate first.', N'توجد نسبة سارية أخرى لهذا الاشتراك وهذه الفئة تتداخل مع هذه التواريخ. حدّد تاريخ انتهاء للنسبة الحالية أولاً.', N'Another active rate for this contribution and nationality group overlaps these dates. End-date the existing rate first.'),
    ('msg.st_reactivate_overlap', 'msg', N'Another active rate overlaps these dates, so this one cannot be re-activated.', N'توجد نسبة سارية أخرى تتداخل مع هذه التواريخ، لذا لا يمكن إعادة تفعيل هذه.', N'Another active rate overlaps these dates, so this one cannot be re-activated.'),
    ('msg.st_pifss_check', 'msg', N'Check the rates (0 - 100 %), the salary floor / ceiling and the effective dates.', N'تحقق من النسب (0 - 100 %) والحدين الأدنى والأعلى للراتب وتواريخ السريان.', N'Check the rates (0 - 100 %), the salary floor / ceiling and the effective dates.'),
    ('msg.st_pifss_required', 'msg', N'Code, name, employee rate, employer rate and effective-from date are required.', N'الرمز والاسم ونسبة الموظف ونسبة صاحب العمل وتاريخ بدء السريان مطلوبة.', N'Code, name, employee rate, employer rate and effective-from date are required.'),
    ('msg.st_pifss_created', 'msg', N'Social security rate created successfully.', N'تم إنشاء نسبة التأمينات بنجاح.', N'Social security rate created successfully.'),
    ('msg.st_pifss_deleted', 'msg', N'Social security rate deleted successfully.', N'تم حذف نسبة التأمينات بنجاح.', N'Social security rate deleted successfully.'),
    ('msg.st_pifss_updated', 'msg', N'Social security rate updated successfully.', N'تم تحديث نسبة التأمينات بنجاح.', N'Social security rate updated successfully.'),
    ('msg.st_not_found', 'msg', N'That record no longer exists. Refresh and try again.', N'هذا السجل لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That record no longer exists. Refresh and try again.'),
    ('msg.st_ind_overlap', 'msg', N'Another active indemnity rule set is in force for overlapping dates. End-date it first.', N'توجد قواعد نهاية خدمة سارية أخرى لتواريخ متداخلة. حدّد لها تاريخ انتهاء أولاً.', N'Another active indemnity rule set is in force for overlapping dates. End-date it first.'),
    ('msg.st_ind_reactivate', 'msg', N'Another active rule set overlaps these dates, so this one cannot be re-activated.', N'توجد قواعد سارية أخرى تتداخل مع هذه التواريخ، لذا لا يمكن إعادة تفعيل هذه.', N'Another active rule set overlaps these dates, so this one cannot be re-activated.'),
    ('msg.st_ind_check', 'msg', N'Check the daily-wage divisor (1 - 31), the cap and the effective dates.', N'تحقق من قاسم الأجر اليومي (1 - 31) والحد الأقصى وتواريخ السريان.', N'Check the daily-wage divisor (1 - 31), the cap and the effective dates.'),
    ('msg.st_ind_required', 'msg', N'Code, name and effective-from date are required.', N'الرمز والاسم وتاريخ بدء السريان مطلوبة.', N'Code, name and effective-from date are required.'),
    ('msg.st_ind_factors', 'msg', N'Entitlement factors need a valid separation type, non-overlapping year ranges and a percentage between 0 and 100.', N'نسب الاستحقاق تتطلب نوع إنهاء خدمة صحيحاً ونطاقات سنوات غير متداخلة ونسبة بين 0 و100.', N'Entitlement factors need a valid separation type, non-overlapping year ranges and a percentage between 0 and 100.'),
    ('msg.st_ind_created', 'msg', N'Indemnity rule set created successfully.', N'تم إنشاء قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set created successfully.'),
    ('msg.st_ind_deleted', 'msg', N'Indemnity rule set deleted successfully.', N'تم حذف قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set deleted successfully.'),
    ('msg.st_ind_updated', 'msg', N'Indemnity rule set updated successfully.', N'تم تحديث قواعد نهاية الخدمة بنجاح.', N'Indemnity rule set updated successfully.'),
    ('msg.st_ind_on', 'msg', N'Rule set activated.', N'تم تفعيل مجموعة القواعد.', N'Rule set activated.'),
    ('msg.st_ind_off', 'msg', N'Rule set deactivated.', N'تم إيقاف مجموعة القواعد.', N'Rule set deactivated.'),
    ('msg.st_ind_slabs', 'msg', N'Service slabs need valid, non-overlapping year ranges and an entitlement in Days or Months.', N'شرائح الخدمة تتطلب نطاقات سنوات صحيحة وغير متداخلة واستحقاقاً بالأيام أو الأشهر.', N'Service slabs need valid, non-overlapping year ranges and an entitlement in Days or Months.'),
    ('msg.st_ind_factors_read', 'msg', N'The entitlement factors could not be read.', N'تعذّرت قراءة نسب الاستحقاق.', N'The entitlement factors could not be read.'),
    ('msg.st_ind_slabs_read', 'msg', N'The service slabs could not be read.', N'تعذّرت قراءة شرائح الخدمة.', N'The service slabs could not be read.'),
    ('msg.st_ot_overlap', 'msg', N'An active rate for this overtime type already covers overlapping dates. End-date it first.', N'توجد نسبة سارية لهذا النوع من العمل الإضافي لتواريخ متداخلة. حدّد لها تاريخ انتهاء أولاً.', N'An active rate for this overtime type already covers overlapping dates. End-date it first.'),
    ('msg.st_ot_check', 'msg', N'Check the multiplier, hours, divisor and effective dates.', N'تحقق من المعامل والساعات والقاسم وتواريخ السريان.', N'Check the multiplier, hours, divisor and effective dates.'),
    ('msg.st_ot_on', 'msg', N'Overtime rate activated.', N'تم تفعيل معامل العمل الإضافي.', N'Overtime rate activated.'),
    ('msg.st_ot_created', 'msg', N'Overtime rate created successfully.', N'تم إنشاء معامل العمل الإضافي بنجاح.', N'Overtime rate created successfully.'),
    ('msg.st_ot_off', 'msg', N'Overtime rate deactivated.', N'تم إيقاف معامل العمل الإضافي.', N'Overtime rate deactivated.'),
    ('msg.st_ot_deleted', 'msg', N'Overtime rate deleted successfully.', N'تم حذف معامل العمل الإضافي بنجاح.', N'Overtime rate deleted successfully.'),
    ('msg.st_ot_updated', 'msg', N'Overtime rate updated successfully.', N'تم تحديث معامل العمل الإضافي بنجاح.', N'Overtime rate updated successfully.'),
    ('msg.st_ot_required', 'msg', N'Overtime type, name, multiplier and effective-from date are required.', N'نوع العمل الإضافي والاسم والمعامل وتاريخ بدء السريان مطلوبة.', N'Overtime type, name, multiplier and effective-from date are required.'),
    ('st.title_banks', 'st', N'Banks & Accounts', N'البنوك والحسابات', N'Banks & Accounts'),
    ('st.banks_subtitle', 'st', N'The bank master and the company''s own salary accounts', N'البنوك وحسابات الرواتب الخاصة بالشركة', NULL),
    ('st.wps_banner_title', 'st', N'WPS codes come from the banks.', N'رموز نظام حماية الأجور تأتي من البنوك.', NULL),
    ('st.wps_banner_text', 'st', N'Leave a bank''s WPS code empty until the bank confirms it in its WPS file specification; payroll warns about banks without one.', N'اترك رمز البنك لنظام حماية الأجور فارغاً حتى يؤكده البنك في مواصفات ملفه؛ وينبّه مسير الرواتب إلى البنوك التي تفتقده.', NULL),
    ('st.company_accounts', 'st', N'Company salary accounts', N'حسابات رواتب الشركة', NULL),
    ('st.banks', 'st', N'Banks', N'البنوك', NULL),
    ('st.bank', 'st', N'Bank', N'البنك', NULL),
    ('st.add_bank', 'st', N'Add bank', N'إضافة بنك', NULL),
    ('st.edit_bank', 'st', N'Edit bank', N'تعديل البنك', NULL),
    ('st.add_company_account', 'st', N'Add account', N'إضافة حساب', NULL),
    ('st.edit_company_account', 'st', N'Edit company account', N'تعديل حساب الشركة', NULL),
    ('st.delete_bank_text', 'st', N'Delete this bank? It cannot be deleted while a company account uses it - deactivate it instead.', N'حذف هذا البنك؟ لا يمكن حذفه ما دام حساب شركة يستخدمه - أوقفه بدلاً من ذلك.', NULL),
    ('st.delete_account_text', 'st', N'Delete this company account?', N'حذف حساب الشركة هذا؟', NULL),
    ('st.search_banks', 'st', N'Search code, name or SWIFT', N'ابحث بالرمز أو الاسم أو رمز السويفت', NULL),
    ('st.search_accounts', 'st', N'Search account, IBAN or bank', N'ابحث بالحساب أو الآيبان أو البنك', NULL),
    ('st.1_bank', 'st', N'1 bank', N'بنك واحد', NULL),
    ('st.0_banks', 'st', N'{0} banks', N'{0} بنوك', NULL),
    ('st.1_account', 'st', N'1 account', N'حساب واحد', NULL),
    ('st.0_accounts', 'st', N'{0} accounts', N'{0} حسابات', NULL),
    ('st.no_banks_yet', 'st', N'No banks yet', N'لا توجد بنوك بعد', NULL),
    ('st.no_accounts_yet', 'st', N'No company accounts yet', N'لا توجد حسابات للشركة بعد', NULL),
    ('st.no_accounts_text', 'st', N'Add the account salaries are paid from - the WPS salary file is made for it.', N'أضف الحساب الذي تُصرف منه الرواتب - يُعد ملف حماية الأجور له.', NULL),
    ('st.swift', 'st', N'SWIFT / BIC', N'سويفت / BIC', NULL),
    ('st.iban_code', 'st', N'IBAN bank code', N'رمز البنك في الآيبان', NULL),
    ('st.iban_code_hint', 'st', N'The 4 letters after KWkk in an IBAN', N'الأحرف الأربعة بعد KWkk في الآيبان', NULL),
    ('st.wps_code', 'st', N'WPS code', N'رمز حماية الأجور', NULL),
    ('st.wps_code_hint', 'st', N'From the bank''s WPS file specification', N'من مواصفات ملف حماية الأجور لدى البنك', NULL),
    ('st.wps_missing', 'st', N'Not set', N'غير محدد', NULL),
    ('st.accounts', 'st', N'Accounts', N'الحسابات', NULL),
    ('st.short_name', 'st', N'Short name', N'الاسم المختصر', NULL),
    ('st.country', 'st', N'Country', N'الدولة', NULL),
    ('st.bank_codes', 'st', N'Codes', N'الرموز', NULL),
    ('st.account', 'st', N'Account', N'الحساب', NULL),
    ('st.account_title', 'st', N'Account title', N'اسم الحساب', NULL),
    ('st.account_number', 'st', N'Account number', N'رقم الحساب', NULL),
    ('st.select_bank', 'st', N'Select the bank', N'اختر البنك', NULL),
    ('st.iban', 'st', N'IBAN', N'الآيبان', NULL),
    ('st.iban_hint', 'st', N'With or without spaces - checked before saving', N'مع أو بدون مسافات - يتم التحقق منه قبل الحفظ', NULL),
    ('st.currency', 'st', N'Currency', N'العملة', NULL),
    ('st.branch', 'st', N'Branch', N'الفرع', NULL),
    ('st.wps', 'st', N'Wage Protection System (WPS)', N'نظام حماية الأجور', NULL),
    ('st.wps_employer_code', 'st', N'WPS employer code', N'رمز صاحب العمل في حماية الأجور', NULL),
    ('st.pam_file_no', 'st', N'PAM file no.', N'رقم ملف الهيئة العامة للقوى العاملة', NULL),
    ('st.default', 'st', N'Default', N'افتراضي', NULL),
    ('st.default_account', 'st', N'Default account', N'الحساب الافتراضي', NULL),
    ('st.default_account_hint', 'st', N'Salaries are paid from it unless another is chosen', N'تُصرف منه الرواتب ما لم يُختر غيره', NULL),
    ('msg.st_bk_swift', 'msg', N'A SWIFT / BIC code is 8 or 11 letters and digits.', N'رمز السويفت يتكون من 8 أو 11 حرفاً ورقماً.', N'A SWIFT / BIC code is 8 or 11 letters and digits.'),
    ('msg.st_bk_in_use', 'msg', N'A company bank account uses this bank, so it cannot be deleted. Deactivate it instead.', N'حساب شركة يستخدم هذا البنك لذا لا يمكن حذفه. أوقفه بدلاً من ذلك.', N'A company bank account uses this bank, so it cannot be deleted. Deactivate it instead.'),
    ('msg.st_ac_on', 'msg', N'Bank account activated.', N'تم تفعيل الحساب البنكي.', N'Bank account activated.'),
    ('msg.st_ac_off', 'msg', N'Bank account deactivated.', N'تم إيقاف الحساب البنكي.', N'Bank account deactivated.'),
    ('msg.st_bk_on', 'msg', N'Bank activated.', N'تم تفعيل البنك.', N'Bank activated.'),
    ('msg.st_bk_required', 'msg', N'Bank code and name are required.', N'رمز البنك واسمه مطلوبان.', N'Bank code and name are required.'),
    ('msg.st_bk_created', 'msg', N'Bank created successfully.', N'تم إنشاء البنك بنجاح.', N'Bank created successfully.'),
    ('msg.st_bk_off', 'msg', N'Bank deactivated.', N'تم إيقاف البنك.', N'Bank deactivated.'),
    ('msg.st_bk_deleted', 'msg', N'Bank deleted successfully.', N'تم حذف البنك بنجاح.', N'Bank deleted successfully.'),
    ('msg.st_bk_updated', 'msg', N'Bank updated successfully.', N'تم تحديث البنك بنجاح.', N'Bank updated successfully.'),
    ('msg.st_ac_created', 'msg', N'Company bank account created successfully.', N'تم إنشاء حساب الشركة بنجاح.', N'Company bank account created successfully.'),
    ('msg.st_ac_deleted', 'msg', N'Company bank account deleted successfully.', N'تم حذف حساب الشركة بنجاح.', N'Company bank account deleted successfully.'),
    ('msg.st_ac_updated', 'msg', N'Company bank account updated successfully.', N'تم تحديث حساب الشركة بنجاح.', N'Company bank account updated successfully.'),
    ('msg.st_ac_required', 'msg', N'Company, bank, account code and account title are required.', N'الشركة والبنك ورمز الحساب واسمه مطلوبة.', N'Company, bank, account code and account title are required.'),
    ('msg.st_ac_number', 'msg', N'Enter the IBAN or the account number.', N'أدخل الآيبان أو رقم الحساب.', N'Enter the IBAN or the account number.'),
    ('msg.st_ac_bank', 'msg', N'Select a valid bank.', N'اختر بنكاً صحيحاً.', N'Select a valid bank.'),
    ('msg.st_ac_iban', 'msg', N'That IBAN is not valid. Kuwait IBANs are 30 characters starting with KW - check for a mistyped digit.', N'هذا الآيبان غير صحيح. الآيبان الكويتي 30 خانة يبدأ بـ KW - تحقق من الأرقام.', N'That IBAN is not valid. Kuwait IBANs are 30 characters starting with KW - check for a mistyped digit.'),
    ('msg.st_ac_iban_dup', 'msg', N'This IBAN is already registered as a company account.', N'هذا الآيبان مسجل مسبقاً كحساب للشركة.', N'This IBAN is already registered as a company account.');
INSERT INTO [Core].[UiLabels] (LabelKey, Module, EnglishText, ArabicText, SourceText)
SELECT s.LabelKey, s.Module, s.EnglishText, s.ArabicText, s.SourceText
FROM   #Seed AS s
WHERE  NOT EXISTS (SELECT 1 FROM [Core].[UiLabels] AS l WHERE l.LabelKey = s.LabelKey AND l.Deleted = 0);

DECLARE @Inserted INT = @@ROWCOUNT;

UPDATE l
   SET l.ArabicText = ISNULL(NULLIF(l.ArabicText, N''), s.ArabicText),
       l.SourceText = ISNULL(l.SourceText, s.SourceText)
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.LabelKey = l.LabelKey
WHERE  l.Deleted = 0
  AND (   (NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL)
       OR (l.SourceText IS NULL AND s.SourceText IS NOT NULL));

DECLARE @Completed INT = @@ROWCOUNT;

/* messages harvested by an earlier run of db/33 (msg.auto_*) get their Arabic too */
UPDATE l
   SET l.ArabicText = s.ArabicText
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.Module = 'msg' AND l.EnglishText = s.EnglishText COLLATE Latin1_General_BIN
WHERE  l.Deleted = 0 AND l.LabelKey LIKE 'msg.auto[_]%' AND NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL;

PRINT CONCAT(N'Payroll Settings labels inserted: ', @Inserted, N', completed: ', @Completed);
DROP TABLE #Seed;
GO
