/* =====================================================================
   52_Bank_Accounting_Reports_Labels.sql  -  HRMS: English + Arabic labels
   of Bank Processing, Accounting and Payroll Reports (and the sidebar
   figures of their sub-sections)
   ---------------------------------------------------------------------
   Run after 49-51. Idempotent: new keys are inserted, existing keys only
   completed (text already edited in Core.UiLabels is never overwritten).

     fin.*      Bank Processing / Accounting / Payroll Reports screens
     layout.*   the sidebar figures
     js.fin_*   wwwroot/js/payroll-finance.js
     msg.fin_*  messages of db/50 and the controllers - matched by SourceText
   ===================================================================== */
SET NOCOUNT ON;
GO
IF OBJECT_ID(N'tempdb..#Seed') IS NOT NULL DROP TABLE #Seed;
CREATE TABLE #Seed (
    LabelKey    VARCHAR(150)   COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
    Module      VARCHAR(30)    COLLATE DATABASE_DEFAULT NOT NULL,
    EnglishText NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL,
    ArabicText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
    SourceText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL
);
INSERT INTO #Seed (LabelKey, Module, EnglishText, ArabicText, SourceText) VALUES
    ('js.fin_failed', 'js', N'The request could not be completed.', N'تعذّر إتمام الطلب.', NULL),
    ('js.fin_required', 'js', N'This is required.', N'هذا الحقل مطلوب.', NULL),
    ('js.fin_selected', 'js', N'{0} selected', N'{0} محدد', NULL),
    ('layout.nav_count_bank_files', 'layout', N'{0} closed payrolls without a bank file', N'{0} رواتب مغلقة بدون ملف بنك', NULL),
    ('layout.nav_count_payments_open', 'layout', N'{0} payments waiting, in a file or failed', N'{0} دفعات معلقة أو في ملف أو فاشلة', NULL),
    ('layout.nav_count_journals_to_make', 'layout', N'{0} closed payrolls without a journal', N'{0} رواتب مغلقة بدون قيد', NULL),
    ('layout.nav_count_journals_to_post', 'layout', N'{0} journals not posted yet', N'{0} قيود لم تُرحّل بعد', NULL),
    ('fin.0_payments', 'fin', N'{0} payments', N'{0} دفعات', NULL),
    ('fin.1_payment', 'fin', N'1 payment', N'دفعة واحدة', NULL),
    ('fin.0_payrolls', 'fin', N'{0} payrolls', N'{0} رواتب', NULL),
    ('fin.1_payroll', 'fin', N'1 payroll', N'راتب واحد', NULL),
    ('fin.0_rows', 'fin', N'{0} rows', N'{0} صفوف', NULL),
    ('fin.1_row', 'fin', N'1 row', N'صف واحد', NULL),
    ('fin.0_splits', 'fin', N'{0} splits', N'{0} توزيعات', NULL),
    ('fin.1_split', 'fin', N'1 split', N'توزيع واحد', NULL),
    ('fin.1_file', 'fin', N'1 file', N'ملف واحد', NULL),
    ('fin.1_journal', 'fin', N'1 journal', N'قيد واحد', NULL),
    ('fin.add_cost_center', 'fin', N'Add cost center', N'إضافة مركز تكلفة', NULL),
    ('fin.all_banks', 'fin', N'All banks', N'جميع البنوك', NULL),
    ('fin.all_methods', 'fin', N'All methods', N'جميع الطرق', NULL),
    ('fin.allocation_banner', 'fin', N'The payroll journal splits an employee''s earnings by the split in force at the month end; employees without a split use their own (or their department''s) cost center.', N'يوزّع قيد الرواتب استحقاقات الموظف حسب التوزيع الساري في نهاية الشهر؛ ومن ليس له توزيع يُحمّل على مركز تكلفته (أو مركز تكلفة إدارته).', NULL),
    ('fin.attempt_0', 'fin', N'Attempt {0}', N'المحاولة {0}', NULL),
    ('fin.audit_hint', 'fin', N'Who did what to each payroll, and when', N'من قام بماذا على كل راتب ومتى', NULL),
    ('fin.bank_file', 'fin', N'Bank file', N'ملف البنك', NULL),
    ('fin.bank_files', 'fin', N'Bank files', N'ملفات البنك', NULL),
    ('fin.bank_file_subtitle', 'fin', N'The salary (WPS) file of a closed payroll - reviewed per bank, built from the bank format', N'ملف الرواتب (حماية الأجور) لراتب مغلق - يُراجع لكل بنك ويُبنى حسب صيغة البنك', NULL),
    ('fin.bank_upload_ref', 'fin', N'Bank upload reference (optional)', N'مرجع الرفع لدى البنك (اختياري)', NULL),
    ('fin.banks_in_file', 'fin', N'Banks in the file', N'البنوك في الملف', NULL),
    ('fin.cash_cheque', 'fin', N'Cash / cheque', N'نقداً / شيك', NULL),
    ('fin.cash_cheque_hint', 'fin', N'No IBAN - not in the file; recorded on the payment register', N'بدون آيبان - خارج الملف؛ تُسجّل في سجل الدفعات', NULL),
    ('fin.cheque_voucher', 'fin', N'Cheque / voucher number (optional)', N'رقم الشيك / السند (اختياري)', NULL),
    ('fin.code_new', 'fin', N'New', N'جديد', NULL),
    ('fin.code_left', 'fin', N'Left', N'غادر', NULL),
    ('fin.code_changed', 'fin', N'Changed', N'تغيّر', NULL),
    ('fin.code_full', 'fin', N'Full', N'كامل', NULL),
    ('fin.code_retry', 'fin', N'Re-issue', N'إعادة إصدار', NULL),
    ('fin.code_generated', 'fin', N'Generated', N'تم الإنشاء', NULL),
    ('fin.code_sent', 'fin', N'Sent', N'أُرسل', NULL),
    ('fin.code_superseded', 'fin', N'Replaced', N'مُستبدل', NULL),
    ('fin.code_draft', 'fin', N'Draft', N'مسودة', NULL),
    ('fin.code_registered', 'fin', N'Registered', N'مسجل', NULL),
    ('fin.code_validation', 'fin', N'Validation', N'التحقق', NULL),
    ('fin.code_awaiting_approval', 'fin', N'Awaiting approval', N'بانتظار الاعتماد', NULL),
    ('fin.code_closed', 'fin', N'Closed', N'مغلق', NULL),
    ('fin.code_cancelled', 'fin', N'Cancelled', N'ملغي', NULL),
    ('fin.code_created', 'fin', N'Created', N'أُنشئ', NULL),
    ('fin.code_submitted', 'fin', N'Submitted', N'قُدّم', NULL),
    ('fin.code_approved', 'fin', N'Approved', N'اعتُمد', NULL),
    ('fin.code_rejected', 'fin', N'Rejected', N'رُفض', NULL),
    ('fin.code_returned', 'fin', N'Returned', N'أُعيد', NULL),
    ('fin.code_reopened', 'fin', N'Reopened', N'أُعيد فتحه', NULL),
    ('fin.code_recalculated', 'fin', N'Recalculated', N'أُعيد احتسابه', NULL),
    ('fin.col_action', 'fin', N'Action', N'الإجراء', NULL),
    ('fin.col_avg_salary', 'fin', N'Average salary', N'متوسط الراتب', NULL),
    ('fin.col_balance', 'fin', N'Balance', N'الرصيد', NULL),
    ('fin.col_change', 'fin', N'Change', N'التغيير', NULL),
    ('fin.col_current_net', 'fin', N'This month', N'هذا الشهر', NULL),
    ('fin.col_date', 'fin', N'Date', N'التاريخ', NULL),
    ('fin.col_description', 'fin', N'Description', N'الوصف', NULL),
    ('fin.col_difference', 'fin', N'Difference', N'الفرق', NULL),
    ('fin.col_employee_no', 'fin', N'Employee no.', N'رقم الموظف', NULL),
    ('fin.col_entries', 'fin', N'Entries', N'القيود', NULL),
    ('fin.col_failed', 'fin', N'Failed', N'فشل', NULL),
    ('fin.col_file', 'fin', N'File', N'الملف', NULL),
    ('fin.col_from', 'fin', N'From', N'من', NULL),
    ('fin.col_instalment', 'fin', N'Instalment', N'القسط', NULL),
    ('fin.col_left', 'fin', N'Instalments left', N'الأقساط المتبقية', NULL),
    ('fin.col_line', 'fin', N'Line', N'السطر', NULL),
    ('fin.col_loan_total', 'fin', N'Total', N'الإجمالي', NULL),
    ('fin.col_loans', 'fin', N'Loans', N'القروض', NULL),
    ('fin.col_max_salary', 'fin', N'Highest salary', N'أعلى راتب', NULL),
    ('fin.col_min_salary', 'fin', N'Lowest salary', N'أدنى راتب', NULL),
    ('fin.col_new', 'fin', N'New amount', N'المبلغ الجديد', NULL),
    ('fin.col_old', 'fin', N'Old amount', N'المبلغ السابق', NULL),
    ('fin.col_other', 'fin', N'Other', N'أخرى', NULL),
    ('fin.col_paid', 'fin', N'Paid', N'مدفوع', NULL),
    ('fin.col_payroll', 'fin', N'Payroll', N'الراتب', NULL),
    ('fin.col_pct_salary', 'fin', N'% of salary', N'% من الراتب', NULL),
    ('fin.col_pifss', 'fin', N'PIFSS', N'التأمينات', NULL),
    ('fin.col_previous_net', 'fin', N'Month before', N'الشهر السابق', NULL),
    ('fin.col_recovered', 'fin', N'Recovered', N'المسترد', NULL),
    ('fin.col_salary', 'fin', N'Salary', N'الراتب', NULL),
    ('fin.col_start', 'fin', N'Started', N'البداية', NULL),
    ('fin.col_to', 'fin', N'To', N'إلى', NULL),
    ('fin.col_total', 'fin', N'Total', N'الإجمالي', NULL),
    ('fin.col_total_cost', 'fin', N'Total cost', N'إجمالي التكلفة', NULL),
    ('fin.col_value_date', 'fin', N'Value date', N'تاريخ القيمة', NULL),
    ('fin.cost_hint', 'fin', N'Gross pay and the employer''s PIFSS share per department', N'إجمالي الرواتب وحصة صاحب العمل في التأمينات لكل إدارة', NULL),
    ('fin.cost_note', 'fin', N'Employer PIFSS is worked out from the rates in force at the month end (Payroll Rules), as the payroll does for the employee share.', N'تُحسب حصة صاحب العمل في التأمينات من النسب السارية في نهاية الشهر (قواعد الرواتب)، كما يحسب الراتب حصة الموظف.', NULL),
    ('fin.create_journal', 'fin', N'Create journal', N'إنشاء القيد', NULL),
    ('fin.create_journal_text', 'fin', N'The journal is saved as shown. Reverse it later to make a new one if the GL mapping changes.', N'يُحفظ القيد كما هو معروض. يمكن عكسه لاحقاً لإنشاء قيد جديد إذا تغيّر ربط دفتر الأستاذ.', NULL),
    ('fin.default_accounts', 'fin', N'Default accounts', N'الحسابات الافتراضية', NULL),
    ('fin.default_accounts_text', 'fin', N'The salaries payable account used for a pay item type with no GL mapping (the other side of its entry).', N'حساب الرواتب المستحقة المستخدم لنوع بند بدون ربط بدفتر الأستاذ (الطرف المقابل لقيده).', NULL),
    ('fin.default_format', 'fin', N'Default format', N'الصيغة الافتراضية', NULL),
    ('fin.delete_split_text', 'fin', N'The employee''s cost goes back to their own cost center from the next journal.', N'ستعود تكلفة الموظف إلى مركز تكلفته من القيد التالي.', NULL),
    ('fin.dept_hint', 'fin', N'Employees, gross, deductions and net per department', N'الموظفون والإجمالي والاستقطاعات والصافي لكل إدارة', NULL),
    ('fin.download', 'fin', N'Download', N'تنزيل', NULL),
    ('fin.download_named', 'fin', N'Download {0}', N'تنزيل {0}', NULL),
    ('fin.effective_to', 'fin', N'Effective to', N'ساري حتى', NULL),
    ('fin.effective_to_hint', 'fin', N'Leave empty while it applies.', N'اتركه فارغاً ما دام سارياً.', NULL),
    ('fin.failure_reason', 'fin', N'Why it failed', N'سبب الفشل', NULL),
    ('fin.file_generated', 'fin', N'Generated', N'تم الإنشاء', NULL),
    ('fin.file_sent', 'fin', N'Sent to bank', N'أُرسل للبنك', NULL),
    ('fin.file_superseded', 'fin', N'Replaced', N'مُستبدل', NULL),
    ('fin.files_of_payroll', 'fin', N'Files of this payroll', N'ملفات هذا الراتب', NULL),
    ('fin.generate_download', 'fin', N'Generate and download', N'إنشاء وتنزيل', NULL),
    ('fin.generate_hint', 'fin', N'The file is kept as generated and can be downloaded again from Payment History.', N'يُحفظ الملف كما أُنشئ ويمكن تنزيله مجدداً من سجل المدفوعات.', NULL),
    ('fin.generate_reissue', 'fin', N'Generate re-issue file', N'إنشاء ملف إعادة الإصدار', NULL),
    ('fin.grade_hint', 'fin', N'Lowest, average and highest salary per grade', N'أدنى ومتوسط وأعلى راتب لكل درجة', NULL),
    ('fin.history_subtitle', 'fin', N'Every salary file generated - download it again, mark it sent to the bank or paid', N'كل ملفات الرواتب المُنشأة - نزّلها مجدداً أو علّمها مرسلة للبنك أو مدفوعة', NULL),
    ('fin.in_force', 'fin', N'In force', N'سارٍ', NULL),
    ('fin.in_the_file', 'fin', N'In the file', N'في الملف', NULL),
    ('fin.journal_0', 'fin', N'Journal {0}', N'القيد {0}', NULL),
    ('fin.journal_preview', 'fin', N'Journal preview', N'معاينة القيد', NULL),
    ('fin.journal_subtitle', 'fin', N'The journal of a closed payroll from the GL mapping, grouped by account and cost center', N'قيد الراتب المغلق حسب ربط دفتر الأستاذ، مجمّعاً حسب الحساب ومركز التكلفة', NULL),
    ('fin.journals', 'fin', N'Journals', N'القيود', NULL),
    ('fin.jv_ready', 'fin', N'Ready', N'جاهز', NULL),
    ('fin.jv_exported', 'fin', N'Exported', N'مُصدّر', NULL),
    ('fin.jv_posted', 'fin', N'Posted', N'مُرحّل', NULL),
    ('fin.jv_reversed', 'fin', N'Reversed', N'معكوس', NULL),
    ('fin.jv_not_posted', 'fin', N'Not posted yet', N'لم يُرحّل بعد', NULL),
    ('fin.kpi_by_bank', 'fin', N'Paid by bank', N'بالدفع البنكي', NULL),
    ('fin.kpi_cash', 'fin', N'Cash / cheque', N'نقداً / شيك', NULL),
    ('fin.kpi_cash_note', 'fin', N'No IBAN on file', N'لا يوجد آيبان', NULL),
    ('fin.kpi_paid', 'fin', N'Paid', N'مدفوع', NULL),
    ('fin.kpi_failed', 'fin', N'Failed', N'فاشل', NULL),
    ('fin.kpi_in_file_note', 'fin', N'{0} awaiting the bank', N'{0} بانتظار البنك', NULL),
    ('fin.kpi_retry_note', 'fin', N'{0} re-issued, waiting for a file', N'{0} أُعيد إصدارها بانتظار ملف', NULL),
    ('fin.kwd_0', 'fin', N'KWD {0}', N'{0} د.ك', NULL),
    ('fin.loans_hint', 'fin', N'Instalment loans and advances still being recovered', N'القروض والسلف بالأقساط التي ما زالت تُسترد', NULL),
    ('fin.mark_cash_paid_text', 'fin', N'The salary was paid in cash or by cheque.', N'دُفع الراتب نقداً أو بشيك.', NULL),
    ('fin.mark_failed', 'fin', N'Mark failed', N'تعليم كفاشل', NULL),
    ('fin.mark_failed_text', 'fin', N'The bank returned the payment. It can be re-issued by bank or paid in cash afterwards.', N'أعاد البنك الدفعة. يمكن إعادة إصدارها بنكياً أو دفعها نقداً بعد ذلك.', NULL),
    ('fin.mark_file_paid', 'fin', N'Mark file paid', N'تعليم الملف كمدفوع', NULL),
    ('fin.mark_file_paid_text', 'fin', N'Every payment of this file still awaiting the bank is marked as paid.', N'تُعلَّم كل دفعات هذا الملف التي بانتظار البنك كمدفوعة.', NULL),
    ('fin.mark_paid', 'fin', N'Mark paid', N'تعليم كمدفوع', NULL),
    ('fin.mark_paid_text', 'fin', N'The bank confirmed the payment.', N'أكّد البنك الدفعة.', NULL),
    ('fin.mark_posted', 'fin', N'Mark posted', N'تعليم كمُرحّل', NULL),
    ('fin.mark_posted_text', 'fin', N'The journal was entered in the books. Enter the reference of the entry.', N'أُدخل القيد في الدفاتر. أدخل مرجع القيد.', NULL),
    ('fin.mark_sent', 'fin', N'Mark sent', N'تعليم كمُرسل', NULL),
    ('fin.mark_sent_text', 'fin', N'The file was uploaded to the bank.', N'رُفع الملف إلى البنك.', NULL),
    ('fin.method', 'fin', N'Method', N'الطريقة', NULL),
    ('fin.method_bank', 'fin', N'Bank', N'بنك', NULL),
    ('fin.method_cash', 'fin', N'Cash / cheque', N'نقداً / شيك', NULL),
    ('fin.missing_wps_note', 'fin', N'{0} bank(s) have no WPS code - add it in Payroll Settings > Banks & Accounts before sending the file.', N'{0} بنك بدون رمز حماية الأجور - أضفه في إعدادات الرواتب > البنوك والحسابات قبل إرسال الملف.', NULL),
    ('fin.n_lines', 'fin', N'{0} lines', N'{0} سطر', NULL),
    ('fin.n_unmapped', 'fin', N'{0} unmapped', N'{0} غير مربوط', NULL),
    ('fin.no_accounts_note', 'fin', N'The payroll''s company has no active salary account.', N'لا يوجد حساب رواتب نشط لشركة الراتب.', NULL),
    ('fin.no_closed_payrolls', 'fin', N'No closed payrolls in this period', N'لا توجد رواتب مغلقة في هذه الفترة', NULL),
    ('fin.no_closed_payrolls_text', 'fin', N'Bank files and journals are made for closed payrolls. Choose another month or close the payroll first.', N'تُنشأ ملفات البنك والقيود للرواتب المغلقة. اختر شهراً آخر أو أغلق الراتب أولاً.', NULL),
    ('fin.no_employer_code', 'fin', N'This account has no WPS employer code.', N'لا يوجد رمز صاحب العمل لهذا الحساب.', NULL),
    ('fin.no_files', 'fin', N'No bank files yet', N'لا توجد ملفات بنك بعد', NULL),
    ('fin.no_files_text', 'fin', N'Generate the file of a closed payroll under Bank File.', N'أنشئ ملف راتب مغلق من شاشة ملف البنك.', NULL),
    ('fin.no_formats_note', 'fin', N'There is no active bank format.', N'لا توجد صيغة بنك نشطة.', NULL),
    ('fin.no_journals', 'fin', N'No journals yet', N'لا توجد قيود بعد', NULL),
    ('fin.no_journals_text', 'fin', N'Create the journal of a closed payroll under Payroll Journal.', N'أنشئ قيد راتب مغلق من شاشة قيد الرواتب.', NULL),
    ('fin.no_payments', 'fin', N'No payments yet', N'لا توجد دفعات بعد', NULL),
    ('fin.no_payments_text', 'fin', N'Payments are recorded when the bank file of a payroll is generated.', N'تُسجّل الدفعات عند إنشاء ملف البنك للراتب.', NULL),
    ('fin.no_rows', 'fin', N'Nothing to report', N'لا يوجد ما يُعرض', NULL),
    ('fin.no_rows_text', 'fin', N'No figures for this period and filter.', N'لا توجد أرقام لهذه الفترة والتصفية.', NULL),
    ('fin.no_splits', 'fin', N'No cost splits yet', N'لا توجد توزيعات تكلفة بعد', NULL),
    ('fin.no_splits_text', 'fin', N'Add a split for an employee whose cost is shared by several cost centers.', N'أضف توزيعاً للموظف الذي تتوزع تكلفته على عدة مراكز تكلفة.', NULL),
    ('fin.nobody_by_bank', 'fin', N'Nobody in this payroll is paid by bank.', N'لا أحد في هذا الراتب يُدفع له بنكياً.', NULL),
    ('fin.nobody_to_pay', 'fin', N'Nobody to pay in this payroll', N'لا يوجد من يُدفع له في هذا الراتب', NULL),
    ('fin.none_in_period', 'fin', N'None in this period', N'لا يوجد في هذه الفترة', NULL),
    ('fin.not_balanced', 'fin', N'Not balanced', N'غير متوازن', NULL),
    ('fin.not_created', 'fin', N'Not created', N'لم يُنشأ', NULL),
    ('fin.not_generated', 'fin', N'Not generated', N'لم يُنشأ', NULL),
    ('fin.nothing_to_journal', 'fin', N'The payroll has no amounts to journal.', N'لا توجد مبالغ في الراتب لقيدها.', NULL),
    ('fin.off_cycle', 'fin', N'Off-cycle', N'خارج الدورة', NULL),
    ('fin.open_banks', 'fin', N'Open Banks & Accounts', N'فتح البنوك والحسابات', NULL),
    ('fin.open_gl_mapping', 'fin', N'Open GL Mapping', N'فتح ربط دفتر الأستاذ', NULL),
    ('fin.open_journal', 'fin', N'Open Payroll Journal', N'فتح قيد الرواتب', NULL),
    ('fin.open_settings', 'fin', N'Open Payroll Settings', N'فتح إعدادات الرواتب', NULL),
    ('fin.ot_note', 'fin', N'Overtime hours are not recorded on the payroll yet - the report shows the overtime paid.', N'لا تُسجّل ساعات العمل الإضافي في الراتب بعد - يعرض التقرير المبالغ المدفوعة.', NULL),
    ('fin.paid_date', 'fin', N'Paid on', N'تاريخ الدفع', NULL),
    ('fin.paid_failed', 'fin', N'{0} paid · {1} failed', N'{0} مدفوع · {1} فاشل', NULL),
    ('fin.pay_failed', 'fin', N'Failed', N'فاشل', NULL),
    ('fin.pay_in_file', 'fin', N'Awaiting bank', N'بانتظار البنك', NULL),
    ('fin.pay_paid', 'fin', N'Paid', N'مدفوع', NULL),
    ('fin.pay_pending', 'fin', N'Waiting', N'معلّق', NULL),
    ('fin.payment_register', 'fin', N'Payment register', N'سجل الدفعات', NULL),
    ('fin.payroll', 'fin', N'Payroll', N'الراتب', NULL),
    ('fin.posted_as_0', 'fin', N'Posted in the books as {0}.', N'رُحّل في الدفاتر بالمرجع {0}.', NULL),
    ('fin.posting_title', 'fin', N'No ERP link yet.', N'لا يوجد ربط بنظام محاسبي بعد.', NULL),
    ('fin.posting_steps', 'fin', N'Export the journal to Excel, enter it in the books, then record the posting reference here.', N'صدّر القيد إلى Excel، وأدخله في الدفاتر، ثم سجّل مرجع الترحيل هنا.', NULL),
    ('fin.posting_subtitle', 'fin', N'Export journals, record their posting reference, reverse them', N'تصدير القيود وتسجيل مرجع ترحيلها وعكسها', NULL),
    ('fin.preview_note', 'fin', N'A preview - create the journal to keep it; it then appears under GL Posting.', N'معاينة - أنشئ القيد لحفظه؛ ويظهر بعدها في ترحيل دفتر الأستاذ.', NULL),
    ('fin.print', 'fin', N'Print', N'طباعة', NULL),
    ('fin.reference', 'fin', N'Reference (optional)', N'المرجع (اختياري)', NULL),
    ('fin.regenerate_download', 'fin', N'Regenerate and download', N'إعادة الإنشاء والتنزيل', NULL),
    ('fin.regenerate_file', 'fin', N'Generate the file again', N'إعادة إنشاء الملف', NULL),
    ('fin.regenerate_reason', 'fin', N'Why it is generated again', N'سبب إعادة الإنشاء', NULL),
    ('fin.regenerated', 'fin', N'Regenerated', N'أُعيد إنشاؤه', NULL),
    ('fin.register_subtitle', 'fin', N'Every salary payment of the closed payrolls - by bank or cash / cheque - and what became of it', N'كل دفعات رواتب الرواتب المغلقة - بنكياً أو نقداً / بشيك - وما آلت إليه', NULL),
    ('fin.reissue', 'fin', N'Re-issue', N'إعادة إصدار', NULL),
    ('fin.reissue_bank', 'fin', N'Re-issue by bank', N'إعادة إصدار بنكياً', NULL),
    ('fin.reissue_bank_text', 'fin', N'The payment waits for a re-issue file of its payroll (Bank File).', N'تنتظر الدفعة ملف إعادة إصدار لراتبها (ملف البنك).', NULL),
    ('fin.reissue_cash', 'fin', N'Pay by cash / cheque', N'الدفع نقداً / بشيك', NULL),
    ('fin.reissue_cash_text', 'fin', N'The payment moves to cash / cheque - mark it paid once handed over.', N'تنتقل الدفعة إلى النقد / الشيك - علّمها كمدفوعة عند التسليم.', NULL),
    ('fin.reissue_file', 'fin', N'Re-issue failed payments', N'إعادة إصدار الدفعات الفاشلة', NULL),
    ('fin.reissue_file_text', 'fin', N'{0} re-issued payments (KWD {1}) wait for a bank file.', N'{0} دفعات أُعيد إصدارها ({1} د.ك) بانتظار ملف بنك.', NULL),
    ('fin.rep_ded_employee', 'fin', N'Deductions per employee', N'الاستقطاعات لكل موظف', NULL),
    ('fin.rep_ded_employee_hint', 'fin', N'PIFSS, loans and other deductions', N'التأمينات والقروض والاستقطاعات الأخرى', NULL),
    ('fin.rep_ot_dept', 'fin', N'Overtime by department', N'العمل الإضافي حسب الإدارة', NULL),
    ('fin.rep_ot_dept_hint', 'fin', N'Who works overtime, where', N'من يعمل وقتاً إضافياً وأين', NULL),
    ('fin.rep_ot_employee', 'fin', N'Overtime by employee', N'العمل الإضافي حسب الموظف', NULL),
    ('fin.rep_ot_employee_hint', 'fin', N'Overtime paid and its share of the salary', N'العمل الإضافي المدفوع ونسبته من الراتب', NULL),
    ('fin.rep_sal_grade', 'fin', N'Salary by grade', N'الرواتب حسب الدرجة', NULL),
    ('fin.reports', 'fin', N'Reports', N'التقارير', NULL),
    ('fin.reports_need_closed', 'fin', N'The reports show closed payrolls - close a payroll first.', N'تعرض التقارير الرواتب المغلقة - أغلق راتباً أولاً.', NULL),
    ('fin.reports_subtitle', 'fin', N'Closed payrolls by month or year - export to Excel or print', N'الرواتب المغلقة حسب الشهر أو السنة - التصدير إلى Excel أو الطباعة', NULL),
    ('fin.reverse', 'fin', N'Reverse', N'عكس', NULL),
    ('fin.reverse_text', 'fin', N'The journal is kept as reversed and the payroll can be journaled again. Reverse the entry in the books too.', N'يُحفظ القيد كمعكوس ويمكن قيد الراتب مجدداً. اعكس القيد في الدفاتر أيضاً.', NULL),
    ('fin.review_by_bank', 'fin', N'Review by bank', N'المراجعة حسب البنك', NULL),
    ('fin.salaries_payable', 'fin', N'Salaries payable account', N'حساب الرواتب المستحقة', NULL),
    ('fin.search_employee', 'fin', N'Search employee', N'ابحث عن موظف', NULL),
    ('fin.search_files', 'fin', N'Search file or payroll', N'ابحث بالملف أو الراتب', NULL),
    ('fin.search_journals', 'fin', N'Search journal, payroll or reference', N'ابحث بالقيد أو الراتب أو المرجع', NULL),
    ('fin.search_payments', 'fin', N'Search employee, reference or file', N'ابحث بالموظف أو المرجع أو الملف', NULL),
    ('fin.select_all', 'fin', N'Select all', N'تحديد الكل', NULL),
    ('fin.select_cost_center', 'fin', N'Select a cost center', N'اختر مركز تكلفة', NULL),
    ('fin.select_employee', 'fin', N'Select an employee', N'اختر موظفاً', NULL),
    ('fin.select_named', 'fin', N'Select {0}', N'تحديد {0}', NULL),
    ('fin.setup_needed', 'fin', N'Set up first.', N'أكمل الإعداد أولاً.', NULL),
    ('fin.trend_12_months', 'fin', N'12 months up to this period', N'12 شهراً حتى هذه الفترة', NULL),
    ('fin.trend_hint', 'fin', N'12 months of headcount, gross and net', N'12 شهراً من عدد الموظفين والإجمالي والصافي', NULL),
    ('fin.unknown_bank', 'fin', N'Bank not recognised', N'بنك غير معروف', NULL),
    ('fin.unknown_bank_note', 'fin', N'{0} employee(s) have an IBAN of a bank not in the bank master - they are in the file, but check the bank list.', N'{0} موظف لديهم آيبان لبنك غير موجود في قائمة البنوك - هم في الملف لكن راجع قائمة البنوك.', NULL),
    ('fin.unmapped', 'fin', N'Unmapped', N'غير مربوط', NULL),
    ('fin.unmapped_title', 'fin', N'{0} line(s) have no GL account.', N'{0} سطر بدون حساب دفتر أستاذ.', NULL),
    ('fin.unmapped_text', 'fin', N'Map their pay item types (or give them a GL code) before posting.', N'اربط أنواع بنودها (أو أعطها رمز حساب) قبل الترحيل.', NULL),
    ('fin.value_0', 'fin', N'Value {0}', N'القيمة {0}', NULL),
    ('fin.variance_hint', 'fin', N'Net against the month before, per employee', N'الصافي مقارنة بالشهر السابق لكل موظف', NULL),
    ('fin.view_journal', 'fin', N'View journal', N'عرض القيد', NULL),
    ('fin.view_only', 'fin', N'You can view the files; generating them needs the bank processing permission.', N'يمكنك عرض الملفات؛ ويتطلب إنشاؤها صلاحية معالجة البنك.', NULL),
    ('fin.view_payments', 'fin', N'View payments', N'عرض الدفعات', NULL),
    ('msg.fin_001', 'msg', N'A cost center does not belong to the employee''s company.', N'أحد مراكز التكلفة لا يتبع شركة الموظف.', N'A cost center does not belong to the employee''s company.'),
    ('msg.fin_002', 'msg', N'A file was already generated for this payroll. Enter the reason for generating it again.', N'أُنشئ ملف لهذا الراتب مسبقاً. أدخل سبب إعادة إنشائه.', N'A file was already generated for this payroll. Enter the reason for generating it again.'),
    ('msg.fin_003', 'msg', N'An employee has no IBAN any more - re-issue as cash / cheque, or add the IBAN first.', N'أحد الموظفين لم يعد لديه آيبان - أعد الإصدار نقداً / بشيك أو أضف الآيبان أولاً.', N'An employee has no IBAN any more - re-issue as cash / cheque, or add the IBAN first.'),
    ('msg.fin_004', 'msg', N'Bank file generated.', N'تم إنشاء ملف البنك.', N'Bank file generated.'),
    ('msg.fin_005', 'msg', N'Bank file marked as sent to the bank.', N'عُلّم ملف البنك كمُرسل للبنك.', N'Bank file marked as sent to the bank.'),
    ('msg.fin_006', 'msg', N'Choose paid or failed.', N'اختر مدفوع أو فاشل.', N'Choose paid or failed.'),
    ('msg.fin_007', 'msg', N'Cost split deleted.', N'تم حذف توزيع التكلفة.', N'Cost split deleted.'),
    ('msg.fin_008', 'msg', N'Cost split saved.', N'تم حفظ توزيع التكلفة.', N'Cost split saved.'),
    ('msg.fin_009', 'msg', N'Default accounts saved.', N'تم حفظ الحسابات الافتراضية.', N'Default accounts saved.'),
    ('msg.fin_010', 'msg', N'Each cost center can be listed once only.', N'يمكن إدراج كل مركز تكلفة مرة واحدة فقط.', N'Each cost center can be listed once only.'),
    ('msg.fin_011', 'msg', N'Enter the date the split applies from (and an end date after it).', N'أدخل تاريخ بدء التوزيع (وتاريخ انتهاء بعده).', N'Enter the date the split applies from (and an end date after it).'),
    ('msg.fin_012', 'msg', N'Enter the reason for reversing the journal.', N'أدخل سبب عكس القيد.', N'Enter the reason for reversing the journal.'),
    ('msg.fin_013', 'msg', N'Enter the reference of the entry in the books.', N'أدخل مرجع القيد في الدفاتر.', N'Enter the reference of the entry in the books.'),
    ('msg.fin_014', 'msg', N'Enter the salaries payable account.', N'أدخل حساب الرواتب المستحقة.', N'Enter the salaries payable account.'),
    ('msg.fin_015', 'msg', N'Enter the value date.', N'أدخل تاريخ القيمة.', N'Enter the value date.'),
    ('msg.fin_016', 'msg', N'Enter why the payment failed.', N'أدخل سبب فشل الدفعة.', N'Enter why the payment failed.'),
    ('msg.fin_017', 'msg', N'Every line needs a cost center and a share above 0.', N'يحتاج كل سطر إلى مركز تكلفة ونسبة أكبر من 0.', N'Every line needs a cost center and a share above 0.'),
    ('msg.fin_018', 'msg', N'Journal created.', N'تم إنشاء القيد.', N'Journal created.'),
    ('msg.fin_019', 'msg', N'Journal marked as posted.', N'عُلّم القيد كمُرحّل.', N'Journal marked as posted.'),
    ('msg.fin_020', 'msg', N'Journal reversed - the payroll can be journaled again.', N'عُكس القيد - يمكن قيد الراتب مجدداً.', N'Journal reversed - the payroll can be journaled again.'),
    ('msg.fin_021', 'msg', N'Only a generated file can be marked as sent to the bank.', N'يمكن تعليم الملف المُنشأ فقط كمُرسل للبنك.', N'Only a generated file can be marked as sent to the bank.'),
    ('msg.fin_022', 'msg', N'Only a journal that is not yet posted or reversed can be marked as posted.', N'يمكن تعليم القيد غير المُرحّل وغير المعكوس فقط كمُرحّل.', N'Only a journal that is not yet posted or reversed can be marked as posted.'),
    ('msg.fin_023', 'msg', N'Only failed payments can be re-issued.', N'يمكن إعادة إصدار الدفعات الفاشلة فقط.', N'Only failed payments can be re-issued.'),
    ('msg.fin_024', 'msg', N'Only payments sent in a bank file can be marked as failed.', N'يمكن تعليم الدفعات المرسلة في ملف بنك فقط كفاشلة.', N'Only payments sent in a bank file can be marked as failed.'),
    ('msg.fin_025', 'msg', N'Only payments sent in a bank file, or cash payments waiting, can be marked as paid.', N'يمكن تعليم الدفعات المرسلة في ملف بنك أو الدفعات النقدية المعلقة فقط كمدفوعة.', N'Only payments sent in a bank file, or cash payments waiting, can be marked as paid.'),
    ('msg.fin_026', 'msg', N'Payments marked as failed.', N'عُلّمت الدفعات كفاشلة.', N'Payments marked as failed.'),
    ('msg.fin_027', 'msg', N'Payments marked as paid.', N'عُلّمت الدفعات كمدفوعة.', N'Payments marked as paid.'),
    ('msg.fin_028', 'msg', N'Payments moved to cash / cheque.', N'نُقلت الدفعات إلى النقد / الشيك.', N'Payments moved to cash / cheque.'),
    ('msg.fin_029', 'msg', N'Payments of the current file are already recorded as paid or failed - it cannot be replaced. Re-issue the failed payments instead.', N'سُجّلت دفعات الملف الحالي كمدفوعة أو فاشلة - لا يمكن استبداله. أعد إصدار الدفعات الفاشلة بدلاً من ذلك.', N'Payments of the current file are already recorded as paid or failed - it cannot be replaced. Re-issue the failed payments instead.'),
    ('msg.fin_030', 'msg', N'Payments re-issued - generate a re-issue file for them.', N'أُعيد إصدار الدفعات - أنشئ ملف إعادة إصدار لها.', N'Payments re-issued - generate a re-issue file for them.'),
    ('msg.fin_031', 'msg', N'Select a closed payroll - a journal is made only for a closed payroll.', N'اختر راتباً مغلقاً - يُنشأ القيد للراتب المغلق فقط.', N'Select a closed payroll - a journal is made only for a closed payroll.'),
    ('msg.fin_032', 'msg', N'Select a closed payroll - salaries are paid only for a closed payroll.', N'اختر راتباً مغلقاً - تُدفع الرواتب للراتب المغلق فقط.', N'Select a closed payroll - salaries are paid only for a closed payroll.'),
    ('msg.fin_033', 'msg', N'Select a company.', N'اختر شركة.', N'Select a company.'),
    ('msg.fin_034', 'msg', N'Select an active bank format.', N'اختر صيغة بنك نشطة.', N'Select an active bank format.'),
    ('msg.fin_035', 'msg', N'Select an active salary account of the payroll''s company.', N'اختر حساب رواتب نشطاً لشركة الراتب.', N'Select an active salary account of the payroll''s company.'),
    ('msg.fin_036', 'msg', N'Select the employee.', N'اختر الموظف.', N'Select the employee.'),
    ('msg.fin_037', 'msg', N'Select the payments.', N'اختر الدفعات.', N'Select the payments.'),
    ('msg.fin_038', 'msg', N'That bank file no longer exists. Refresh and try again.', N'ملف البنك لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That bank file no longer exists. Refresh and try again.'),
    ('msg.fin_039', 'msg', N'That cost split no longer exists. Refresh and try again.', N'توزيع التكلفة لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That cost split no longer exists. Refresh and try again.'),
    ('msg.fin_040', 'msg', N'That journal no longer exists. Refresh and try again.', N'القيد لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That journal no longer exists. Refresh and try again.'),
    ('msg.fin_041', 'msg', N'The employee has another split starting within these dates. Change its dates first.', N'للموظف توزيع آخر يبدأ ضمن هذه التواريخ. غيّر تواريخه أولاً.', N'The employee has another split starting within these dates. Change its dates first.'),
    ('msg.fin_042', 'msg', N'The journal does not balance. Check the GL mapping and try again.', N'القيد غير متوازن. راجع ربط دفتر الأستاذ وحاول مجدداً.', N'The journal does not balance. Check the GL mapping and try again.'),
    ('msg.fin_043', 'msg', N'The payments changed while the file was being prepared. Refresh and generate it again.', N'تغيّرت الدفعات أثناء إعداد الملف. حدّث الصفحة وأنشئه مجدداً.', N'The payments changed while the file was being prepared. Refresh and generate it again.'),
    ('msg.fin_044', 'msg', N'The payroll has no amounts to journal.', N'لا توجد مبالغ في الراتب لقيدها.', N'The payroll has no amounts to journal.'),
    ('msg.fin_045', 'msg', N'The shares must add up to 100%.', N'يجب أن يكون مجموع النسب 100%.', N'The shares must add up to 100%.'),
    ('msg.fin_046', 'msg', N'The value date, file name and file content are required.', N'تاريخ القيمة واسم الملف ومحتواه مطلوبة.', N'The value date, file name and file content are required.'),
    ('msg.fin_047', 'msg', N'There are no payments to update. Refresh and try again.', N'لا توجد دفعات للتحديث. حدّث الصفحة وحاول مجدداً.', N'There are no payments to update. Refresh and try again.'),
    ('msg.fin_048', 'msg', N'There is nobody to pay in this file.', N'لا يوجد من يُدفع له في هذا الملف.', N'There is nobody to pay in this file.'),
    ('msg.fin_049', 'msg', N'This journal is already reversed.', N'هذا القيد معكوس مسبقاً.', N'This journal is already reversed.'),
    ('msg.fin_050', 'msg', N'This payroll already has a file for a different bank choice. Generate it again with the same bank choice.', N'لهذا الراتب ملف لاختيار بنوك مختلف. أعد إنشاءه بنفس اختيار البنوك.', N'This payroll already has a file for a different bank choice. Generate it again with the same bank choice.'),
    ('msg.fin_051', 'msg', N'This payroll already has a journal. Reverse it first to make a new one.', N'لهذا الراتب قيد مسبقاً. اعكسه أولاً لإنشاء قيد جديد.', N'This payroll already has a journal. Reverse it first to make a new one.'),
    ('fin.view', 'fin', N'View', N'عرض', NULL),
    ('fin.balance_check', 'fin', N'Debits = credits', N'المدين = الدائن', NULL),
    ('fin.n_employees', 'fin', N'{0} employees', N'{0} موظف', NULL),
    ('fin.defaults_saved_note', 'fin', N'A saved journal keeps its accounts - the default applies to journals created from now on.', N'يحتفظ القيد المحفوظ بحساباته - يُطبّق الحساب الافتراضي على القيود المنشأة من الآن.', NULL),
    ('layout.nav_keep_open', 'layout', N'Keep the sidebar open', N'إبقاء القائمة الجانبية مفتوحة', NULL),
    ('layout.nav_auto_minimize', 'layout', N'Auto-minimize the sidebar', N'تصغير القائمة الجانبية تلقائياً', NULL);
INSERT INTO [Core].[UiLabels] (LabelKey, Module, EnglishText, ArabicText, SourceText)
SELECT s.LabelKey, s.Module, s.EnglishText, s.ArabicText, s.SourceText
FROM   #Seed AS s
WHERE  NOT EXISTS (SELECT 1 FROM [Core].[UiLabels] AS l WHERE l.LabelKey = s.LabelKey AND l.Deleted = 0);

DECLARE @Inserted INT = @@ROWCOUNT;

UPDATE l
   SET l.ArabicText = ISNULL(NULLIF(l.ArabicText, N''), s.ArabicText),
       l.SourceText = ISNULL(l.SourceText, s.SourceText)
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.LabelKey = l.LabelKey
WHERE  l.Deleted = 0
  AND (   (NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL)
       OR (l.SourceText IS NULL AND s.SourceText IS NOT NULL));

DECLARE @Completed INT = @@ROWCOUNT;

/* messages harvested by an earlier run of db/33 (msg.auto_*) get their Arabic too */
UPDATE l
   SET l.ArabicText = s.ArabicText
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.Module = 'msg' AND l.EnglishText = s.EnglishText COLLATE Latin1_General_BIN
WHERE  l.Deleted = 0 AND l.LabelKey LIKE 'msg.auto[_]%' AND NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL;

PRINT CONCAT(N'Bank, Accounting and Reports labels inserted: ', @Inserted, N', completed: ', @Completed);
DROP TABLE #Seed;
GO
