/* =====================================================================
   58_Security_Labels.sql  -  HRMS: English + Arabic labels of Security >
   Create Roles / Manage Users, and of their messages
   ---------------------------------------------------------------------
   Run after db/57. Idempotent: new keys are inserted, existing keys only
   completed (text already edited in Core.UiLabels is never overwritten).

     sec.*      the Views/Security pages, Security/AccessCatalog.cs
     layout.*   the sidebar's Security group
     js.sec_*   wwwroot/js/security.js
     msg.sec_*  messages of db/57 and SecurityController (matched by SourceText)
   ===================================================================== */
SET NOCOUNT ON;
GO
IF OBJECT_ID(N'tempdb..#Seed') IS NOT NULL DROP TABLE #Seed;
CREATE TABLE #Seed (
    LabelKey    VARCHAR(150)   COLLATE DATABASE_DEFAULT NOT NULL PRIMARY KEY,
    Module      VARCHAR(30)    COLLATE DATABASE_DEFAULT NOT NULL,
    EnglishText NVARCHAR(1000) COLLATE DATABASE_DEFAULT NOT NULL,
    ArabicText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL,
    SourceText  NVARCHAR(1000) COLLATE DATABASE_DEFAULT NULL
);
INSERT INTO #Seed (LabelKey, Module, EnglishText, ArabicText, SourceText) VALUES
    ('layout.security', 'layout', N'Security', N'الأمان', NULL),
    ('layout.create_roles', 'layout', N'Create Roles', N'إنشاء الأدوار', NULL),
    ('layout.assign_roles', 'layout', N'Assign Roles', N'تعيين الأدوار', NULL),          -- kept: replaced by Manage Users
    ('js.sec_failed', 'js', N'The request could not be completed.', N'تعذّر إتمام الطلب.', NULL),
    ('js.sec_discard_changes', 'js', N'Discard the changes to this role?', N'هل تريد تجاهل التغييرات على هذا الدور؟', NULL),
    ('js.sec_summary', 'js', N'{0} pages · {1} functions · {2} approval rights', N'{0} صفحات · {1} وظائف · {2} صلاحيات اعتماد', NULL),
    ('js.sec_expand_all', 'js', N'Expand all', N'توسيع الكل', NULL),
    ('js.sec_collapse_all', 'js', N'Collapse all', N'طي الكل', NULL),
    ('js.sec_name_code', 'js', N'Enter the role name and a code (letters, digits and _).', N'أدخل اسم الدور ورمزاً له (حروف وأرقام و _).', NULL),
    ('sec.roles_subtitle', 'sec', N'Create a role and choose what it may read, change and approve on every page', N'أنشئ دوراً واختر ما يمكنه عرضه وتعديله واعتماده في كل صفحة', NULL),
    ('sec.assign_subtitle', 'sec', N'Give users their roles - their access is the rights of all their roles', N'امنح المستخدمين أدوارهم - صلاحياتهم هي مجموع صلاحيات أدوارهم', NULL),
    ('sec.roles', 'sec', N'Roles', N'الأدوار', NULL),
    ('sec.role', 'sec', N'Role', N'الدور', NULL),
    ('sec.new_role', 'sec', N'New role', N'دور جديد', NULL),
    ('sec.new_role_text', 'sec', N'Name the role, then tick what it may do on each page.', N'سمِّ الدور ثم حدّد ما يمكنه فعله في كل صفحة.', NULL),
    ('sec.search_roles', 'sec', N'Search roles', N'ابحث في الأدوار', NULL),
    ('sec.no_roles', 'sec', N'No roles yet.', N'لا توجد أدوار بعد.', NULL),
    ('sec.pick_role', 'sec', N'Choose a role', N'اختر دوراً', NULL),
    ('sec.pick_role_text', 'sec', N'Pick a role on the left to see and change its access, or create a new one.', N'اختر دوراً من القائمة لعرض صلاحياته وتعديلها، أو أنشئ دوراً جديداً.', NULL),
    ('sec.n_users', 'sec', N'{0} users', N'{0} مستخدمين', NULL),
    ('sec.n_rights', 'sec', N'{0} rights', N'{0} صلاحيات', NULL),
    ('sec.role_meta', 'sec', N'{0} users · {1} rights', N'{0} مستخدمين · {1} صلاحيات', NULL),
    ('sec.system', 'sec', N'System', N'نظام', NULL),
    ('sec.system_role', 'sec', N'System role', N'دور النظام', NULL),
    ('sec.system_role_text', 'sec', N'System Administrator always has every right. It cannot be changed or deleted.', N'مسؤول النظام يملك جميع الصلاحيات دائماً، ولا يمكن تعديله أو حذفه.', NULL),
    ('sec.read_only', 'sec', N'Read-only', N'للعرض فقط', NULL),
    ('sec.read_only_text', 'sec', N'You can see this role but not change it (it is shared by every company, or you have no right to edit roles).', N'يمكنك عرض هذا الدور دون تعديله (مشترك بين جميع الشركات أو ليست لديك صلاحية تعديل الأدوار).', NULL),
    ('sec.role_name', 'sec', N'Role name', N'اسم الدور', NULL),
    ('sec.role_code', 'sec', N'Role code', N'رمز الدور', NULL),
    ('sec.all_companies', 'sec', N'All companies', N'جميع الشركات', NULL),
    ('sec.active', 'sec', N'Active', N'نشط', NULL),
    ('sec.inactive', 'sec', N'Inactive', N'غير نشط', NULL),
    ('sec.description', 'sec', N'Description', N'الوصف', NULL),
    ('sec.description_hint', 'sec', N'What this role is for, e.g. "Prepares the monthly payroll"', N'الغرض من هذا الدور، مثل "يُعِدّ الرواتب الشهرية"', NULL),
    ('sec.page_access', 'sec', N'Page access', N'صلاحيات الصفحات', NULL),
    ('sec.page_access_text', 'sec', N'Tick Read, Write or Full for each page and its functions. A page tick applies to its functions; open a page to fine-tune them.', N'حدّد عرض أو كتابة أو كامل لكل صفحة ووظائفها. تحديد الصفحة ينطبق على وظائفها، وافتح الصفحة لضبط كل وظيفة.', NULL),
    ('sec.search_pages', 'sec', N'Search pages and functions', N'ابحث في الصفحات والوظائف', NULL),
    ('sec.quick_set', 'sec', N'Quick set', N'تحديد سريع', NULL),
    ('sec.all_read', 'sec', N'Read everything', N'عرض الكل', NULL),
    ('sec.all_full', 'sec', N'Full everywhere', N'كامل للكل', NULL),
    ('sec.clear_all', 'sec', N'Clear all', N'مسح الكل', NULL),
    ('sec.expand_all', 'sec', N'Expand all', N'توسيع الكل', NULL),
    ('sec.legend', 'sec', N'Legend', N'دليل الألوان', NULL),
    ('sec.read', 'sec', N'Read', N'عرض', NULL),
    ('sec.write', 'sec', N'Write', N'كتابة', NULL),
    ('sec.full', 'sec', N'Full', N'كامل', NULL),
    ('sec.read_hint', 'sec', N'see it, read-only', N'الاطلاع فقط', NULL),
    ('sec.write_hint', 'sec', N'add, edit, process', N'إضافة وتعديل ومعالجة', NULL),
    ('sec.full_hint', 'sec', N'write + delete, cancel, reopen', N'الكتابة + الحذف والإلغاء وإعادة الفتح', NULL),
    ('sec.page_function', 'sec', N'Page / function', N'الصفحة / الوظيفة', NULL),
    ('sec.all_0_in_1', 'sec', N'{0} for every page of {1}', N'{0} لكل صفحات {1}', NULL),
    ('sec.0_on_1', 'sec', N'{0}: {1}', N'{0}: {1}', NULL),
    ('sec.functions_of_0', 'sec', N'Functions of {0}', N'وظائف {0}', NULL),
    ('sec.n_functions', 'sec', N'{0} functions', N'{0} وظائف', NULL),
    ('sec.not_applicable', 'sec', N'Not applicable', N'لا ينطبق', NULL),
    ('sec.with_page', 'sec', N'Read with its page', N'العرض مع الصفحة', NULL),
    ('sec.no_pages_match', 'sec', N'No pages or functions match.', N'لا توجد صفحات أو وظائف مطابقة.', NULL),
    ('sec.approval_rights', 'sec', N'Approval rights', N'صلاحيات الاعتماد', NULL),
    ('sec.approval_rights_text', 'sec', N'Who reviews (level 1), who approves (level 2) and who may approve their own submissions, per process.', N'من يراجع (المستوى 1) ومن يعتمد (المستوى 2) ومن يمكنه اعتماد ما قدّمه بنفسه، لكل عملية.', NULL),
    ('sec.process', 'sec', N'Process', N'العملية', NULL),
    ('sec.level_1', 'sec', N'Level 1', N'المستوى 1', NULL),
    ('sec.level_1_hint', 'sec', N'HR review', N'مراجعة الموارد البشرية', NULL),
    ('sec.level_2', 'sec', N'Level 2', N'المستوى 2', NULL),
    ('sec.level_2_hint', 'sec', N'Finance approval', N'اعتماد المالية', NULL),
    ('sec.self_approve', 'sec', N'Approve own', N'اعتماد الذاتي', NULL),
    ('sec.self_approve_hint', 'sec', N'their own submissions', N'ما قدّموه بأنفسهم', NULL),
    ('sec.approval_note', 'sec', N'The amount limits and the roles of each level are set on Payroll Settings > Approval Workflow.', N'حدود المبالغ وأدوار كل مستوى تُضبط في إعدادات الرواتب > مسار الاعتماد.', NULL),
    ('sec.unsaved', 'sec', N'Unsaved changes', N'تغييرات غير محفوظة', NULL),
    ('sec.discard', 'sec', N'Discard', N'تجاهل', NULL),
    ('sec.create_role', 'sec', N'Create role', N'إنشاء الدور', NULL),
    ('sec.save_role', 'sec', N'Save role', N'حفظ الدور', NULL),
    ('sec.delete_role', 'sec', N'Delete role', N'حذف الدور', NULL),
    ('sec.delete_confirm', 'sec', N'Delete the role {0}? Users must not have it any more.', N'هل تريد حذف الدور {0}؟ يجب ألا يكون مُسنداً لأي مستخدم.', NULL),
    ('sec.mod_workforce', 'sec', N'Workforce', N'القوى العاملة', NULL),
    ('sec.mod_organization', 'sec', N'Organization setup', N'إعداد المنشأة', NULL),
    ('sec.mod_payroll', 'sec', N'Payroll processing', N'معالجة الرواتب', NULL),
    ('sec.mod_payslips', 'sec', N'Payslips', N'قسائم الرواتب', NULL),
    ('sec.mod_finance', 'sec', N'Bank, accounting & reports', N'البنك والمحاسبة والتقارير', NULL),
    ('sec.mod_settings', 'sec', N'Payroll settings', N'إعدادات الرواتب', NULL),
    ('sec.mod_security', 'sec', N'Security', N'الأمان', NULL),
    ('sec.pg_employees', 'sec', N'Employees', N'الموظفون', NULL),
    ('sec.pg_employees_hint', 'sec', N'list, add an employee (Write), delete / deactivate (Full)', N'القائمة، إضافة موظف (كتابة)، حذف / تعطيل (كامل)', NULL),
    ('sec.fn_personal', 'sec', N'Personal info & employment', N'البيانات الشخصية والوظيفية', NULL),
    ('sec.fn_personal_hint', 'sec', N'read with the profile; Write = edit', N'تُعرض مع الملف؛ الكتابة = التعديل', NULL),
    ('sec.fn_compliance', 'sec', N'Kuwait compliance', N'الامتثال الكويتي', NULL),
    ('sec.fn_dependents', 'sec', N'Dependents', N'المُعالون', NULL),
    ('sec.fn_documents', 'sec', N'Documents', N'المستندات', NULL),
    ('sec.fn_documents_hint', 'sec', N'Write = upload, Full = remove', N'الكتابة = الرفع، الكامل = الإزالة', NULL),
    ('sec.pg_organization', 'sec', N'Organization setup', N'إعداد المنشأة', NULL),
    ('sec.pg_organization_hint', 'sec', N'branches, departments, sections, designations, positions, locations, cost centers', N'الفروع والأقسام والوحدات والمسميات والوظائف والمواقع ومراكز التكلفة', NULL),
    ('sec.fn_companies', 'sec', N'Companies', N'الشركات', NULL),
    ('sec.fn_companies_hint', 'sec', N'add / edit companies (Write), delete (Full)', N'إضافة / تعديل الشركات (كتابة)، حذف (كامل)', NULL),
    ('sec.pg_payroll_dashboard', 'sec', N'Payroll dashboard', N'لوحة الرواتب', NULL),
    ('sec.pg_payrolls', 'sec', N'Payrolls', N'الرواتب', NULL),
    ('sec.pg_payrolls_hint', 'sec', N'create, register, validate and submit; history', N'الإنشاء والتسجيل والتحقق والإرسال؛ السجل', NULL),
    ('sec.fn_run_exclude', 'sec', N'Exclude / include employees', N'استبعاد / إعادة إدراج الموظفين', NULL),
    ('sec.fn_run_cancel', 'sec', N'Cancel a payroll', N'إلغاء الرواتب', NULL),
    ('sec.fn_run_reopen', 'sec', N'Reopen a closed payroll', N'إعادة فتح رواتب مغلقة', NULL),
    ('sec.pg_calendar', 'sec', N'Payroll calendar & pay periods', N'تقويم الرواتب وفترات الدفع', NULL),
    ('sec.pg_calendar_hint', 'sec', N'pay groups and their periods', N'مجموعات الدفع وفتراتها', NULL),
    ('sec.pg_pay_items', 'sec', N'Pay items & loans', N'بنود الرواتب والقروض', NULL),
    ('sec.pg_pay_items_hint', 'sec', N'earnings, deductions, salary changes, loans', N'الاستحقاقات والاستقطاعات وتغييرات الراتب والقروض', NULL),
    ('sec.pg_settlement', 'sec', N'Final settlement', N'التسوية النهائية', NULL),
    ('sec.fn_fs_pay', 'sec', N'Mark as paid', N'تعليم كمدفوعة', NULL),
    ('sec.pg_payslips', 'sec', N'Payslips', N'قسائم الرواتب', NULL),
    ('sec.pg_payslips_hint', 'sec', N'employee payslips; Write = generate', N'قسائم الموظفين؛ الكتابة = الإنشاء', NULL),
    ('sec.fn_payslip_email', 'sec', N'Email payslips', N'إرسال القسائم بالبريد', NULL),
    ('sec.pg_bank', 'sec', N'Bank processing', N'المعالجة البنكية', NULL),
    ('sec.pg_bank_hint', 'sec', N'bank files and the payment register', N'ملفات البنك وسجل المدفوعات', NULL),
    ('sec.pg_accounting', 'sec', N'Accounting', N'المحاسبة', NULL),
    ('sec.pg_accounting_hint', 'sec', N'payroll journal, GL posting, cost allocation', N'قيد الرواتب والترحيل ومراكز التكلفة', NULL),
    ('sec.pg_reports', 'sec', N'Payroll reports', N'تقارير الرواتب', NULL),
    ('sec.pg_payroll_settings', 'sec', N'Payroll settings', N'إعدادات الرواتب', NULL),
    ('sec.pg_payroll_settings_hint', 'sec', N'rules, pay item types, deductions, proration, approvals, banks, GL mapping', N'القواعد وأنواع البنود والاستقطاعات والتناسب والاعتماد والبنوك وربط الحسابات', NULL),
    ('sec.pg_roles', 'sec', N'Create roles', N'إنشاء الأدوار', NULL),
    ('sec.pg_roles_hint', 'sec', N'Write = create / change roles, Full = delete', N'الكتابة = إنشاء / تعديل الأدوار، الكامل = الحذف', NULL),
    ('sec.pg_assign', 'sec', N'Assign roles', N'تعيين الأدوار', NULL),
    ('sec.pg_assign_hint', 'sec', N'Write = give and remove roles', N'الكتابة = منح الأدوار وإزالتها', NULL),
    ('sec.apr_payroll', 'sec', N'Payroll run', N'دورة الرواتب', NULL),
    ('sec.apr_payroll_hint', 'sec', N'submitted payrolls', N'الرواتب المُرسلة للاعتماد', NULL),
    ('sec.apr_pay_items', 'sec', N'Pay items, salary changes & loans', N'بنود الرواتب وتغييرات الراتب والقروض', NULL),
    ('sec.apr_pay_items_hint', 'sec', N'items waiting for approval', N'البنود بانتظار الاعتماد', NULL),
    ('sec.apr_settlement', 'sec', N'Final settlement', N'التسوية النهائية', NULL),
    ('sec.apr_settlement_hint', 'sec', N'end of service, resignation, encashment', N'نهاية الخدمة والاستقالة وصرف الإجازات', NULL),
    ('sec.search_users', 'sec', N'Search name, username or email', N'ابحث بالاسم أو اسم المستخدم أو البريد', NULL),
    ('sec.all_roles', 'sec', N'All roles', N'جميع الأدوار', NULL),
    ('sec.no_role', 'sec', N'No role', N'بدون دور', NULL),
    ('sec.users', 'sec', N'Users', N'المستخدمون', NULL),
    ('sec.user', 'sec', N'User', N'المستخدم', NULL),
    ('sec.1_user', 'sec', N'1 user', N'مستخدم واحد', NULL),
    ('sec.n_users_count', 'sec', N'{0} users', N'{0} مستخدمين', NULL),
    ('sec.no_users', 'sec', N'No users yet.', N'لا يوجد مستخدمون بعد.', NULL),
    ('sec.no_users_match', 'sec', N'No users match.', N'لا يوجد مستخدمون مطابقون.', NULL),
    ('sec.last_sign_in', 'sec', N'Last sign-in', N'آخر دخول', NULL),
    ('sec.assign_roles', 'sec', N'Assign roles', N'تعيين الأدوار', NULL),
    ('sec.view_roles', 'sec', N'View roles', N'عرض الأدوار', NULL),
    ('sec.roles_of_0', 'sec', N'Roles of {0}', N'أدوار {0}', NULL),
    ('sec.save_roles', 'sec', N'Save roles', N'حفظ الأدوار', NULL),
    ('sec.assign_hint', 'sec', N'Tick the roles this user has. Their access is everything their roles allow; changes apply within a minute.', N'حدّد أدوار هذا المستخدم. صلاحياته هي كل ما تسمح به أدواره، وتسري التغييرات خلال دقيقة.', NULL),
    ('sec.cannot_assign', 'sec', N'You can only give roles whose rights you hold yourself', N'يمكنك منح الأدوار التي تملك صلاحياتها فقط', NULL),
    ('msg.sec_role_gone', 'msg', N'That role no longer exists. Refresh and try again.', N'هذا الدور لم يعد موجوداً. حدّث الصفحة وحاول مجدداً.', N'That role no longer exists. Refresh and try again.'),
    ('msg.sec_system_rights', 'msg', N'System Administrator is a system role - it always has every right.', N'مسؤول النظام دور نظام - يملك جميع الصلاحيات دائماً.', N'System Administrator is a system role - it always has every right.'),
    ('msg.sec_shared_change', 'msg', N'Only a System Administrator can change a role shared by every company.', N'فقط مسؤول النظام يمكنه تعديل دور مشترك بين جميع الشركات.', N'Only a System Administrator can change a role shared by every company.'),
    ('msg.sec_code_name', 'msg', N'Enter the role code and name.', N'أدخل رمز الدور واسمه.', N'Enter the role code and name.'),
    ('msg.sec_code_rule', 'msg', N'The role code may use letters, digits and _ only, and cannot be SYSADMIN.', N'رمز الدور يقبل الحروف والأرقام و _ فقط، ولا يمكن أن يكون SYSADMIN.', N'The role code may use letters, digits and _ only, and cannot be SYSADMIN.'),
    ('msg.sec_code_taken', 'msg', N'Another role already uses this code.', N'هناك دور آخر يستخدم هذا الرمز.', N'Another role already uses this code.'),
    ('msg.sec_role_created', 'msg', N'Role created.', N'تم إنشاء الدور.', N'Role created.'),
    ('msg.sec_role_saved', 'msg', N'Role saved.', N'تم حفظ الدور.', N'Role saved.'),
    ('msg.sec_role_created_kept', 'msg', N'Role created. Rights you do not hold yourself were left out.', N'تم إنشاء الدور. الصلاحيات التي لا تملكها لم تُضَف.', N'Role created. Rights you do not hold yourself were left out.'),
    ('msg.sec_role_saved_kept', 'msg', N'Role saved. Rights you do not hold yourself were left as they were.', N'تم حفظ الدور. الصلاحيات التي لا تملكها بقيت كما هي.', N'Role saved. Rights you do not hold yourself were left as they were.'),
    ('msg.sec_system_delete', 'msg', N'System Administrator is a system role and cannot be deleted.', N'مسؤول النظام دور نظام ولا يمكن حذفه.', N'System Administrator is a system role and cannot be deleted.'),
    ('msg.sec_shared_delete', 'msg', N'Only a System Administrator can delete a role shared by every company.', N'فقط مسؤول النظام يمكنه حذف دور مشترك بين جميع الشركات.', N'Only a System Administrator can delete a role shared by every company.'),
    ('msg.sec_role_in_use', 'msg', N'Users still have this role. Remove it from them on Assign Roles first.', N'ما زال هذا الدور مُسنداً لمستخدمين. أزله منهم في تعيين الأدوار أولاً.', N'Users still have this role. Remove it from them on Assign Roles first.'),
    ('msg.sec_role_deleted', 'msg', N'Role deleted.', N'تم حذف الدور.', N'Role deleted.'),
    ('msg.sec_user_gone', 'msg', N'That user was not found.', N'لم يُعثر على هذا المستخدم.', N'That user was not found.'),
    ('msg.sec_sysadmin_only', 'msg', N'Only a System Administrator can give or remove the System Administrator role.', N'فقط مسؤول النظام يمكنه منح دور مسؤول النظام أو إزالته.', N'Only a System Administrator can give or remove the System Administrator role.'),
    ('msg.sec_last_admin', 'msg', N'This is the last active System Administrator - give the role to another user first.', N'هذا آخر مسؤول نظام نشط - امنح الدور لمستخدم آخر أولاً.', N'This is the last active System Administrator - give the role to another user first.'),
    ('msg.sec_roles_saved', 'msg', N'Roles saved. They apply to the user within a minute.', N'تم حفظ الأدوار، وتسري على المستخدم خلال دقيقة.', N'Roles saved. They apply to the user within a minute.'),
    ('msg.sec_no_escalation', 'msg', N'You can only give or remove roles whose rights you hold yourself.', N'يمكنك منح أو إزالة الأدوار التي تملك صلاحياتها فقط.', N'You can only give or remove roles whose rights you hold yourself.'),
    ('msg.sec_record_gone', 'msg', N'That record was not found. Refresh and try again.', N'لم يُعثر على السجل. حدّث الصفحة وحاول مجدداً.', N'That record was not found. Refresh and try again.'),
    ('msg.sec_record_missing', 'msg', N'That record was not found.', N'لم يُعثر على السجل.', N'That record was not found.'),
    ('msg.sec_no_right', 'msg', N'You do not have permission to do this.', N'ليست لديك صلاحية للقيام بذلك.', N'You do not have permission to do this.'),
    ('layout.manage_users', 'layout', N'Manage Users', N'إدارة المستخدمين', NULL),
    ('common.view', 'common', N'View', N'عرض', NULL),
    ('js.sec_add_user', 'js', N'Add user', N'إضافة مستخدم', NULL),
    ('js.sec_confirm_activate', 'js', N'Activate {0}? They can sign in again.', N'هل تريد تفعيل {0}؟ سيتمكن من تسجيل الدخول مجدداً.', NULL),
    ('js.sec_confirm_deactivate', 'js', N'Deactivate {0}? They are signed out and can no longer sign in.', N'هل تريد إيقاف {0}؟ سيتم تسجيل خروجه ولن يتمكن من تسجيل الدخول.', NULL),
    ('js.sec_employee_company_first', 'js', N'Choose the company first to link an employee.', N'اختر الشركة أولاً لربط موظف.', NULL),
    ('js.sec_linked_employee_hint', 'js', N'Optional - the employee this person is (for My Payslips and their own records).', N'اختياري - الموظف الذي يمثله هذا الشخص (لكشوف رواتبي وسجلاته الخاصة).', NULL),
    ('js.sec_enter_password', 'js', N'Enter a password.', N'أدخل كلمة المرور.', NULL),
    ('js.sec_enter_username', 'js', N'Enter the user name.', N'أدخل اسم المستخدم.', NULL),
    ('sec.users_subtitle', 'sec', N'Add the people who sign in, reset their passwords and choose their roles', N'أضف الأشخاص الذين يسجلون الدخول، وأعد تعيين كلمات مرورهم، واختر أدوارهم', NULL),
    ('sec.pg_users', 'sec', N'Manage users', N'إدارة المستخدمين', NULL),
    ('sec.pg_users_hint', 'sec', N'Write = add and edit users, reset passwords, give roles · Full = also deactivate', N'الكتابة = إضافة المستخدمين وتعديلهم وإعادة تعيين كلمات المرور ومنح الأدوار · الكامل = والإيقاف أيضاً', NULL),
    ('sec.add_user', 'sec', N'Add user', N'إضافة مستخدم', NULL),
    ('sec.save_user', 'sec', N'Save user', N'حفظ المستخدم', NULL),
    ('sec.user_0', 'sec', N'User: {0}', N'المستخدم: {0}', NULL),
    ('sec.account', 'sec', N'Account', N'الحساب', NULL),
    ('sec.account_hint', 'sec', N'How the person signs in and which company they work in', N'طريقة تسجيل دخول الشخص والشركة التي يعمل بها', NULL),
    ('sec.username', 'sec', N'User name', N'اسم المستخدم', NULL),
    ('sec.email', 'sec', N'Email', N'البريد الإلكتروني', NULL),
    ('sec.linked_employee', 'sec', N'Linked employee', N'الموظف المرتبط', NULL),
    ('sec.linked_employee_hint', 'sec', N'Optional - the employee this person is (for My Payslips and their own records).', N'اختياري - الموظف الذي يمثله هذا الشخص (لكشوف رواتبي وسجلاته الخاصة).', NULL),
    ('sec.employee_company_first', 'sec', N'Choose the company first to link an employee.', N'اختر الشركة أولاً لربط موظف.', NULL),
    ('sec.no_employee', 'sec', N'No employee', N'بدون موظف', NULL),
    ('sec.active_account', 'sec', N'Active - may sign in', N'نشط - يمكنه تسجيل الدخول', NULL),
    ('sec.active_account_hint', 'sec', N'An inactive user cannot sign in; open sessions end within a minute.', N'لا يمكن للمستخدم غير النشط تسجيل الدخول، وتنتهي جلساته المفتوحة خلال دقيقة.', NULL),
    ('sec.cannot_deactivate_self', 'sec', N'You cannot deactivate your own account.', N'لا يمكنك إيقاف حسابك.', NULL),
    ('sec.never', 'sec', N'Never', N'أبداً', NULL),
    ('sec.locked', 'sec', N'Locked', N'مقفل', NULL),
    ('sec.locked_hint', 'sec', N'Too many wrong passwords - resetting the password unlocks the account', N'محاولات خاطئة كثيرة - إعادة تعيين كلمة المرور تفتح الحساب', NULL),
    ('sec.first_sign_in', 'sec', N'Must change password', N'يجب تغيير كلمة المرور', NULL),
    ('sec.must_change_hint', 'sec', N'Chooses a new password at the next sign-in', N'سيختار كلمة مرور جديدة عند تسجيل الدخول التالي', NULL),
    ('sec.password', 'sec', N'Password', N'كلمة المرور', NULL),
    ('sec.password_new_hint', 'sec', N'The first password - give it to the user in person', N'كلمة المرور الأولى - سلّمها للمستخدم شخصياً', NULL),
    ('sec.password_reset_hint', 'sec', N'Set a new password when the user has forgotten theirs', N'عيّن كلمة مرور جديدة إذا نسي المستخدم كلمة مروره', NULL),
    ('sec.reset_password', 'sec', N'Reset the password', N'إعادة تعيين كلمة المرور', NULL),
    ('sec.new_password', 'sec', N'New password', N'كلمة المرور الجديدة', NULL),
    ('sec.confirm_password', 'sec', N'Confirm password', N'تأكيد كلمة المرور', NULL),
    ('sec.must_change', 'sec', N'Ask for a new password at the first sign-in', N'طلب كلمة مرور جديدة عند أول تسجيل دخول', NULL),
    ('sec.reset_signs_out', 'sec', N'Resetting signs the user out of every session and unlocks the account.', N'تؤدي إعادة التعيين إلى تسجيل خروج المستخدم من كل الجلسات وفتح الحساب.', NULL),
    ('sec.user_roles_hint', 'sec', N'Tick the roles this user has. Their access is everything their roles allow.', N'حدّد أدوار هذا المستخدم. صلاحياته هي كل ما تسمح به أدواره.', NULL),
    ('sec.roles_company_hint', 'sec', N'Roles of other companies are not shown - a user gets shared roles and their own company''s roles.', N'لا تظهر أدوار الشركات الأخرى - يحصل المستخدم على الأدوار المشتركة وأدوار شركته.', NULL),
    ('sec.user_locked_title', 'sec', N'Read only.', N'للقراءة فقط.', NULL),
    ('sec.user_locked_text', 'sec', N'This account has rights you do not hold yourself, so only a System Administrator can change it.', N'لهذا الحساب صلاحيات لا تملكها، لذا لا يغيّره إلا مدير النظام.', NULL),
    ('msg.sec_role_in_use_users', 'msg', N'Users still have this role. Remove it from them on Manage Users first.', N'ما زال هذا الدور مُسنداً لمستخدمين. أزله منهم في إدارة المستخدمين أولاً.', N'Users still have this role. Remove it from them on Manage Users first.'),
    ('msg.sec_self_deactivate', 'msg', N'You cannot deactivate your own account.', N'لا يمكنك إيقاف حسابك.', N'You cannot deactivate your own account.'),
    ('msg.sec_admin_account', 'msg', N'Only a System Administrator can change a System Administrator''s account.', N'لا يغيّر حساب مدير النظام إلا مدير النظام.', N'Only a System Administrator can change a System Administrator''s account.'),
    ('msg.sec_user_activated', 'msg', N'User activated.', N'تم تفعيل المستخدم.', N'User activated.'),
    ('msg.sec_user_deactivated', 'msg', N'User deactivated. They are signed out within a minute.', N'تم إيقاف المستخدم. سيتم تسجيل خروجه خلال دقيقة.', N'User deactivated. They are signed out within a minute.'),
    ('msg.sec_enter_username', 'msg', N'Enter the user name.', N'أدخل اسم المستخدم.', N'Enter the user name.'),
    ('msg.sec_username_rule', 'msg', N'The user name needs at least 3 characters: letters, digits and . _ - @ only.', N'يحتاج اسم المستخدم إلى 3 أحرف على الأقل: حروف وأرقام و . _ - @ فقط.', N'The user name needs at least 3 characters: letters, digits and . _ - @ only.'),
    ('msg.sec_username_taken', 'msg', N'Another user already has this user name.', N'اسم المستخدم مستخدم لدى مستخدم آخر.', N'Another user already has this user name.'),
    ('msg.sec_email_taken', 'msg', N'Another user already has this email address.', N'البريد الإلكتروني مستخدم لدى مستخدم آخر.', N'Another user already has this email address.'),
    ('msg.sec_choose_company', 'msg', N'Choose the user''s company.', N'اختر شركة المستخدم.', N'Choose the user''s company.'),
    ('msg.sec_company_before_employee', 'msg', N'Choose the user''s company before linking an employee.', N'اختر شركة المستخدم قبل ربط موظف.', N'Choose the user''s company before linking an employee.'),
    ('msg.sec_employee_company', 'msg', N'The linked employee must belong to the user''s company.', N'يجب أن يتبع الموظف المرتبط شركة المستخدم.', N'The linked employee must belong to the user''s company.'),
    ('msg.sec_employee_has_user', 'msg', N'This employee already has a user account.', N'لهذا الموظف حساب مستخدم بالفعل.', N'This employee already has a user account.'),
    ('msg.sec_password_new_user', 'msg', N'Enter a password for the new user.', N'أدخل كلمة مرور للمستخدم الجديد.', N'Enter a password for the new user.'),
    ('msg.sec_user_created', 'msg', N'User created.', N'تم إنشاء المستخدم.', N'User created.'),
    ('msg.sec_user_saved', 'msg', N'User saved. Changes apply to them within a minute.', N'تم حفظ المستخدم. تسري التغييرات خلال دقيقة.', N'User saved. Changes apply to them within a minute.'),
    ('msg.sec_manage_own_rights', 'msg', N'You can only change accounts whose rights you hold yourself.', N'يمكنك تغيير الحسابات التي تملك صلاحياتها فقط.', N'You can only change accounts whose rights you hold yourself.'),
    ('msg.sec_choose_employee_again', 'msg', N'Choose the employee again.', N'اختر الموظف مرة أخرى.', N'Choose the employee again.'),
    ('msg.sec_enter_password', 'msg', N'Enter a password.', N'أدخل كلمة المرور.', N'Enter a password.'),
    ('msg.sec_passwords_differ', 'msg', N'The two passwords don''t match.', N'كلمتا المرور غير متطابقتين.', N'The two passwords don''t match.');
INSERT INTO [Core].[UiLabels] (LabelKey, Module, EnglishText, ArabicText, SourceText)
SELECT s.LabelKey, s.Module, s.EnglishText, s.ArabicText, s.SourceText
FROM   #Seed AS s
WHERE  NOT EXISTS (SELECT 1 FROM [Core].[UiLabels] AS l WHERE l.LabelKey = s.LabelKey AND l.Deleted = 0);

DECLARE @Inserted INT = @@ROWCOUNT;

UPDATE l
   SET l.ArabicText = ISNULL(NULLIF(l.ArabicText, N''), s.ArabicText),
       l.SourceText = ISNULL(l.SourceText, s.SourceText)
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.LabelKey = l.LabelKey
WHERE  l.Deleted = 0
  AND (   (NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL)
       OR (l.SourceText IS NULL AND s.SourceText IS NOT NULL));

DECLARE @Completed INT = @@ROWCOUNT;

/* messages harvested by an earlier run of db/33 (msg.auto_*) get their Arabic too */
UPDATE l
   SET l.ArabicText = s.ArabicText
FROM   [Core].[UiLabels] AS l
JOIN   #Seed AS s ON s.Module = 'msg' AND l.EnglishText = s.EnglishText COLLATE Latin1_General_BIN
WHERE  l.Deleted = 0 AND l.LabelKey LIKE 'msg.auto[_]%' AND NULLIF(l.ArabicText, N'') IS NULL AND s.ArabicText IS NOT NULL;

PRINT CONCAT(N'Security labels inserted: ', @Inserted, N', completed: ', @Completed);
DROP TABLE #Seed;
GO
